### ISSUE TITLE
Thumbnails with slides are not synced

### ISSUE THREAD

**Issue by isaadansari** [bqworks/slider-pro#103]
Thumbnails with slides are not synced if width of the thumbnails are set to viewport or exceeds.

I am using the following code which does not work

<pre>var timeSlides = $('.timeline-slides');
        timeSlides.sliderPro({
            width: '100%',
            height: 500,
            thumbnailsPosition: 'top',
            visibleSize: '100%',
            forceSize: 'fullWidth',
            arrows: true,
            buttons: false,
            waitForLayers: false,
            thumbnailWidth: 80,
            thumbnailHeight: 36,
            thumbnailPointer: false,
            autoplay: false,
            autoScaleLayers: true,
            breakpoints: {
                767: {
                    thumbnailWidth: $(window).width(),
                    height:300,
                    thumbnailHeight: 50,
                    fadeArrows: false,
                }
            },</pre>

**Comment by davidghi** [comment]
Hi. The thumbnails are not meant to be used that way, but there is an alternative solution. Please see this discussion: https://github.com/bqworks/slider-pro/issues/81

Cheers
