### ISSUE TITLE
unwanted selection is occurred when next arrow button is double clicked

### ISSUE THREAD

**Issue by tangeedad** [bqworks/slider-pro#106]
On Chrome Browser
unwanted selection is occurred when next arrow button is double clicked.
when you navigate the pictures attached, you may click them fast.
then, the background color is changed to blue.
I found out that it is because selection is occurred.
It happens when you click the 'next' button not the 'previous' button.
It's maybe there's no image under the next button. You don't use images for the button to navigate.
I thought that's a good idea but, the selection is bugging me there.. 
please fix this when you could...
thanks!!

**Comment by davidghi** [comment]
You can use this code: 

```
jQuery( '.sp-arrow' ).mousedown(function( event ) {
    return false;
})
```

Cheers
