### ISSUE TITLE
Deep linking url start from 1 instead of 0?

### ISSUE THREAD

**Issue by vincentccw** [bqworks/slider-pro#108]
Is it possible for the custom url to start from 1: 
http://domain.com/page#my-slider/1

instead of 0:
http://domain.com/page#my-slider/0

The reason is non-tech savvy people might find gallery image start with 0 odd most of the time.

**Comment by davidghi** [comment]
You can use a slide id instead of the index, or you can make a small edit to the code to have the indexes start from 1.

Cheers
