### ISSUE TITLE
keep selected thumbnail at center and scroll thumbnails along slides

### ISSUE THREAD

**Issue by mandar-k** [bqworks/slider-pro#109]
hello,
I am using slider just like the first example http://bqworks.com/slider-pro/#example1 with full screen width,
what i'm facing is that i want to keep active slide and respective thumbnail at center of slider and rest should  scroll.
as in usual way slider slides new slide and thumbnail scrolls. instead i want active thumbnail at center and keep thumbnails also scrolling  along with the slides how to achieve that ???
a example slider from jssor is http://www.jssor.com/demos/image-gallery.slider shown here.
and good work. very nice slider with so many customization options just add this functionality and i am good to go.
thank you.

**Comment by davidghi** [comment]
Hi. That option is not available. You would have to edit some JavaScript if you want to achieve it.

Cheers.

**Comment by mandar-k** [comment]
thnx for the suggestion.
