### ISSUE TITLE
Stop autoplay on click

### ISSUE THREAD

**Issue by Honza-B** [bqworks/slider-pro#111]
Hi,

Are there any possibilities, how stop autoplay on clickt inside the slider?

I'he tried pause slider with 

`var slider = $('slider').sliderPro();`
`...`
`slider.sliderPro( 'autoplay', false );`

 but it's not worked.

Thanks for answers

**Comment by davidghi** [comment]
Hi. This is the correct code to stop the slider programatically: `$('#my-slider').sliderPro( 'autoplay', false );`

Cheers.
