### ISSUE TITLE
slide changes blank only 2 items

### ISSUE THREAD

**Issue by Yamama** [bqworks/slider-pro#112]
my english is very poor, sorry

slide changes blank only 2 items.

no problem
```html
<ul class="sp-slides">
	<li class="sp-slide"><img src="1.png"></li>
	<li class="sp-slide"><img src="2.png"></li>
	<li class="sp-slide"><img src="3.png"></li>
</ul>
```

blank problem
```html
<ul class="sp-slides">
	<li class="sp-slide"><img src="1.png"></li>
	<li class="sp-slide"><img src="2.png"></li>
</ul>
```

please show this.
![sliderpro-problem](https://cloud.githubusercontent.com/assets/41526/12259132/f0ecd9e2-b956-11e5-9b35-1de5f26565b7.jpg)

**Comment by davidghi** [comment]
Hi. You need to disable looping if you have only two slides. It has been discussed here: https://github.com/bqworks/slider-pro/issues/5

**Comment by Yamama** [comment]
Number of slides may change by the program.
The number of the slide may also be made to one.
Is not dependent on the number of slides, JavaScript will want to use without changing.

I want to support because it is very easy to use and convenient library.

#### common.js
```javascript
$(function() {
	$("#my-slider").sliderPro();
});
```

#### index.php
```php
<script type="text/javascript" src="jquery.min.js"></script>
<script type="text/javascript" src="common.js"></script>
<div id="my-slider">
	<div class="sp-slides">
		<?php
			$images = array(
				"path/to/image1.jpg",
				"path/to/image2.jpg",
				// ...EX) get image path from database
			);
			
			foreach($images as $image) {
				echo("<div class='sp-slide'><img src='$image'></div>");
			}
		?>
	</div>
</div>
```

**Comment by davidghi** [comment]
You could programmatically set the `loop` option to `true` or `false` based on the number of slides.

**Comment by Yamama** [comment]
understood, thx
