### ISSUE TITLE
Move to next slide on Hover

### ISSUE THREAD

**Issue by DeysonOrtiz** [bqworks/slider-pro#114]
Hello and good day!  First off what a beautiful script.  Thank you for sharing.

I had wanted to know if this is possible.  Could we have an image in the first slide and when a person hover over the image it slide to a Vimeo that autoplays.  If the user hovers out the slide goes back to the first slide image and the video resets.

In addition it would also be great if a user may click on a button while it can take them to the third slide which holds more information about the image and video.  Please let me know if any of this possible.  Thank you for all your hard work and have an amazing day! :)

**Comment by davidghi** [comment]
Hi there,

Yes, it's all possible by using the slider's API. Please take a look here: https://github.com/bqworks/slider-pro/blob/master/docs/api.md#2-public-methods What you would have to do is add some mouse event listeners for hover of the image and click on the button and then call the appropriate slider methods.

Cheers!
