### ISSUE TITLE
Current Slide Number / Total slides count

### ISSUE THREAD

**Issue by iryska** [bqworks/slider-pro#116]
Hi Guys,

I need to add on slider counter, that will show total count of slides and current number of active slide. (Something like 2/12).

Any ideas how it's can be done?

Thanks

**Comment by iryska** [comment]
I found it :)

`
		var slider = jQuery( this ).data( 'sliderPro' );
		jQuery(this).append('<div class="counter"><span class="active">'+(parseInt(slider.getSelectedSlide()) + 1) +'</span>/'+slider.getTotalSlides()+'</div>');
		slider.on( 'gotoSlide', function( event ) {
			jQuery(this).find('.counter .active').text(event.index + 1);
		});`

**Comment by markgenest** [comment]
Hi,

I've tried the code above but get the console error:

`slider is undefined, can't access property "getSelectedSlide" of it`

Is there some other step needed to initialize this? Does `getSelectedSlide` need to have a class or id bound to it?

I am using the code below:

```
// Instantiate SliderPro
$(document).ready(function($) {
  $('.slider-pro').sliderPro({
    width: '100%',
    autoHeight: true,
    arrows: true,
    fadeArrows: false,
    buttons: false,
    fade: true,
    thumbnailPosition: 'center',
    thumbnailWidth: 75,
    thumbnailHeight: 75,
    thumbnailPointer: false,
    autoplay: false
  });
});

var slider = jQuery( this ).data( 'sliderPro' );
 jQuery(this).append('<div class="counter"><span class="active">'+(parseInt(slider.getSelectedSlide()) + 1) +'</span>/'+slider.getTotalSlides()+'</div>');
 slider.on( 'gotoSlide', function( event ) {
     jQuery(this).find('.counter .active').text(event.index + 1);
 });
```

Any help would be greatly appreciated.

Thanks!
Mark

**Comment by markgenest** [comment]
How does this work if you have multiple slides on a page with “.slider-pro”? Right now it only works on the first slider. 

Thanks!
