### ISSUE TITLE
TypeError: this.slides[index] is undefined 	

### ISSUE THREAD

**Issue by Kate-es** [bqworks/slider-pro#121]
Hi,
I'm getting the below error:

`TypeError: this.slides[index] is undefined
animatedLayers = this.slides[ index ].animatedLayers,`

I've written a js code to read Slides information form a SharePoint list and build the HTML dynamically. When the page loads, my js file needs to run first to build the HTML. Then the jquery.sliderPro.js should run to build the slideshow. 
  
So I've added the below interval to each `;(function( window, $ )`  to check if the HTML is created and ready. 

`var checkExist = setInterval(function() {
   if ($('.sp-slide').length) {	  
      console.log("Exists!");
      clearInterval(checkExist);
   }
}, 100); // check every 100ms`

If I put an `alert("Show something");` anywhere in the SlidePro.js functions, then all works fine.

If I remove the alert, then I'll get the error.

This is happening because there is  setTimeout() inside loop. when I put alert, browser will wait for user action therefore it works.

Please advise how to fix this issue. 

Thanks,

Kate

**Comment by Kate-es** [comment]
Any respond?

**Comment by Kate-es** [comment]
I've managed to fix this issue!

**Comment by davidghi** [comment]
For future reference, this error is frequent when there are no slides in the slider.

Cheers.

**Comment by developer-vivacity** [comment]
@davidghi 
I am facing this error when I have less than 5 slides in the slider.
How to fix this error? I don't want to see the error in console.

**Comment by phalsarath** [comment]
How to use slider pro with IONIC?
