### ISSUE TITLE
Double sliding because of another css transition

### ISSUE THREAD

**Issue by qahar** [bqworks/slider-pro#123]
When I click the arrow or grab the slide, it will sliding twice.
For anyone who get similiar issue, do not apply another css transition to slider pro element.

In my case, this code cause it :yum: 

    * {
      -webkit-transition: all .2s ease;
      -moz-transition: all .2s ease;
      -ms-transition: all .2s ease;
      -o-transition: all .2s ease;
      transition: all .2s ease;
    }

It would be good if slider-pro can negate code above, if not it's fine.
I hope this will usefull for others.

Thank you for your awesome works :+1:

**Comment by davidghi** [comment]
Thank you for sharing! I will leave particular situations like this to be handled particularly.

Cheers.
