### ISSUE TITLE
Issue with responsive option and width 100%

### ISSUE THREAD

**Issue by zlatevbg** [bqworks/slider-pro#124]
The slider is not responsive (i.e. it doesn't scale) if the options are set as follows:

`width: '100%'`
`height: 400`
`responsive: true` (default)
`autoHeight: false` (default)

However if I change the width to fixed value then it works.

It also works correctly if I set the `autoHeight` option to `true` however in my case I can't do that because of another issue: #125

**Comment by davidghi** [comment]
If you use a percentage width you need to indicate an aspect ratio manually by using the aspectRatio property.

Cheers.
