### ISSUE TITLE
Issue with non-static layers and autoHeight

### ISSUE THREAD

**Issue by zlatevbg** [bqworks/slider-pro#125]
If the layers are not static (sp-static) and the `autoHeight` option is set to `true` the first time you navigate to every next slide the navigational **arrows** and **buttons** are pushed down.

However if you navigate back to the previous slide or resize the browser windows and repeat, the navigational **arrows** and **buttons** are returned to their correct position and this position is remembered.

If the layers are static everything works as intended.

**Comment by zlatevbg** [comment]
A quick fix for me was to change the function `calculateSize` as follows:

```
var rect = element.getBoundingClientRect();

if ( rect.height > height ) {
    height = rect.height;
}

if ( rect.width > width ) {
    width = rect.width;
}
```

**Comment by makerlabs** [comment]
This also fix wrong height for the ".sp-mask" element (when navigating for the first time to the next slide).
Thanks.
