### ISSUE TITLE
Carousel with variable item-sizes

### ISSUE THREAD

**Issue by zlatevbg** [bqworks/slider-pro#127]
Hi,

Does the slider support displaying different sized images?
What I need is a scrolling thumbnails/logos slider with fixed height and variable width images.

See the example here: https://dev7studios.com/caroufredsel-old/examples/variable-visible-variable-size.php

Thanks.

**Comment by davidghi** [comment]
Hi. This feature is not available at the moment.

Cheers

**Comment by davidghi** [comment]
The latest version, 1.3, adds this feature.
