### ISSUE TITLE
When shuffle is enabled `gotoSlide` should be disabled ?

### ISSUE THREAD

**Issue by gautamz07** [bqworks/slider-pro#130]
For further information see here http://stackoverflow.com/questions/35780590/gotoslide-index-not-working-in-sliderpro

FIDDLE HERE https://jsfiddle.net/ybphbLqL/

**Comment by davidghi** [comment]
The 'shuffle' option is disabled by default and its role is to randomize the slides. It has nothing to do with `gotoSlide`.

Cheers.
