### ISSUE TITLE
Vidéo and SSL

### ISSUE THREAD

**Issue by dutom007** [bqworks/slider-pro#131]
Hi,

When i use un vidéo link like :
https://www.youtube.com/embed/OD3ZPxdOFE4

and click on play button, the iframe create by the plugin not use https et create mixed content error.

**Comment by davidghi** [comment]
Hi. Please make sure you use the latest version of the slider.

Cheers.

**Comment by dutom007** [comment]
Hi, I changed your to add the "s"  on youtube link. 
It's work
Le 12 mars 2016 13:33, David Ghiurau <notifications@github.com> a écrit :Hi. Please make sure you use the latest version of the slider.

Cheers.
