### ISSUE TITLE
SASS/LESS files.

### ISSUE THREAD

**Issue by dobromir-hristov** [bqworks/slider-pro#133]
The only complaint I have so far, is that the src folder for the css files is not usable with build tools. I use scss and its impossible to use the provided files.

**Comment by graciano** [comment]
I'm using the project with sass and it works fine. Can I help you?

**Comment by dobromir-hristov** [comment]
How do you import css into sass?

**Comment by graciano** [comment]
@dobromir-hristov  The line `@import "relative-path/to/file.css";` [works in css](https://developer.mozilla.org/pt-BR/docs/Web/CSS/@import). But if the relative path of the resulting css file is different from the sass file, it's enough to omit the extension, as in  `@import "relative-path/to/file";` so you will end up using the import from sass [as you can see in the documentation](http://sass-lang.com/guide).
