### ISSUE TITLE
I have to click twice on a link to work

### ISSUE THREAD

**Issue by Kate-es** [bqworks/slider-pro#134]
I'm using slider pro with images and Text.

Inside the thumbnail text, there are links with the 'sp-selectable' class.

But I have to click twice on a link to work. If the slide changes automatically, then the link will work. But if the user clicks on a thumbnail to change the slide, then the link should be clicked twice.

Could you please let me know if there is a fix for it?

Thanks

**Comment by Kate-es** [comment]
Any idea?

**Comment by davidghi** [comment]
Hi. Please share a link.

**Comment by Kate-es** [comment]
I was able to fix it myself by removing the // Disable click events on links part.
