### ISSUE TITLE
on the left side of the movement will be a blank, when div.sp-slide less than four, i add a settimeout to solve the problem

### ISSUE THREAD

**Issue by jishichang** [bqworks/slider-pro#135]
`
_updateSlidesPosition: function() {

```
        var _this = this;

        setTimeout(function () {

            var selectedSlidePixelPosition = parseInt( _this.$slides.find( '.sp-slide' ).eq( _this.selectedSlideIndex ).css( _this.positionProperty ), 10 );

            for ( var slideIndex = 0; slideIndex < _this.slidesOrder.length; slideIndex++ ) {
                var slide = _this.$slides.find( '.sp-slide' ).eq( _this.slidesOrder[ slideIndex ] );
                slide.css( _this.positionProperty, selectedSlidePixelPosition + ( slideIndex - _this.middleSlidePosition  ) * ( _this.slideSize + _this.settings.slideDistance ) );
            }
        }, 1000);
    },`
```

**Comment by gsarig** [comment]
+1

jishichang 's solution fixes the issue, but still, if you drag the slide to the opposite direction (from left to right, as if you want to go back) the previous slide remains blank.

**Comment by razmarin** [comment]
+ 1

**Comment by razmarin** [comment]
I have noticed the issue occurs on drag from left to right, when there are two slides or one slide. From three slides all is fine. Any fixes?

**Comment by davidghi** [comment]
The infinite loop will work correctly only if there are at least 3 slides. If you have less, then it's better to set `loop` to false. Also, when another slide is selected, the slider will first rearrange the slides in the new order before starting the animation, so if you have only 3 or 4 slides in the slider and also have multiple visible slides at the same time, you might some blank areas at the sides of the slider when it rearranges the slides in the new correct order.

Cheers!
