### ISSUE TITLE
Safari slider image bug - images are positioned wrong sometimes

### ISSUE THREAD

**Issue by benjamin3105** [bqworks/slider-pro#137]
My client uses Safari and the Slider Pro is showing some strange things sometimes. The images in the sliders are positioned wrong sometimes and this only happens in Safari. I got a screenshot to show what I mean. Is this a known problem or complete new one? 

Normally the image has to be right after the red header but it renders like the screenshot.

![safari_bug](https://cloud.githubusercontent.com/assets/12101063/14014874/9d0297c6-f1b5-11e5-90db-3c68de72970e.jpg)

**Comment by gautamz07** [comment]
@benjamin3105 which version of safari ?

**Comment by benjamin3105** [comment]
I dont know the version of the Safari but I know what caused it. It apears adblocker was causing this bug. When my client deactivated it the slider weng back to normal.

**Comment by davidghi** [comment]
This happens when the size of the image is not calculated correctly (this calculation is done in order to center the image inside the slide) and it could be because AdBlock interferes with this calculation.  A solution would be to set `ceterImage` to `false`.

Cheers
