### ISSUE TITLE
Animation bug when transitioning to next slide to quickly.

### ISSUE THREAD

**Issue by wpexplorer** [bqworks/slider-pro#138]
If you try going to the next slide (using Fade Animation) and the animation hasn't finished it causes this issue: http://cl.ly/1z1Y3c2u1o0n

Would be be possible to prevent the "flash"? Like this example: http://cl.ly/0E3V082q060V (different script).

I am willing to help pay for the fix, your plugin is freaking awesome! And if you need a live example please let me know.

- AJ

**Comment by davidghi** [comment]
Hi AJ,

I will take a look at this issue soon, and the remaining opened issues. I've been a little busy with something else lately and didn't have time to respond to all the issues.

You don't have to pay for the fix, but any help in promoting this script and/or the WordPress version is greatly appreciated :)

Cheers,
David

**Comment by wpexplorer** [comment]
Great! I'll at least update our page to make it better and move it higher on the list - http://www.wpexplorer.com/slider-pro-responsive-slider-wordpress-plugin/

Thanks for everything!

**Comment by davidghi** [comment]
Thank you! I appreciate it a lot! :) By the way, please try to set the `fadeOutPreviousSlide` option to false (it's set to true by default). This will prevent the blankness because it animates only one slide, not both of them. Anyway, I'm looking now into the situation when `fadeOutPreviousSlide` is set to true as well.

Cheers!

**Comment by wpexplorer** [comment]
Cool thanks!

**Comment by davidghi** [comment]
The latest update, 1.3, address this issue. The fade effect will run smoother now, even if `fadeOutPreviousSlide` is set to true.

**Comment by wpexplorer** [comment]
Thanks! It does seem better ;) I think what I'm going to do though is add my own fade module (not sure if you want to add this as a setting) so that when set to fade it stacks all the images always and it animates with fade even on touch - I believe it would really smooth things out even more and speed things up since you aren't having to modify the position of the slides.
