### ISSUE TITLE
IE Issue Can't Click Links On Slider

### ISSUE THREAD

**Issue by wpexplorer** [bqworks/slider-pro#140]
I noticed a bug on IE when a slider has a link on it, it would require clicking the link twice (2x) in order for it to work. I thought maybe it has something to do with the touch function but I wasn't able to locate the issue because it seems once you click on it twice it works from then on.

Can anyone else recreate that problem?

Here is a live example: http://totaltheme.wpengine.com/features/builder-modules/recent-post-slider/

Thanks!

**Comment by davidghi** [comment]
I just checked this in IE on Win10 and couldn't replicate the issue. The links worked for me from the first try; both the image links and the text links. Let me know if I'm overlooking something.

Cheers.

**Comment by wpexplorer** [comment]
Thanks for checking. I was testing on IE Edge. Maybe the have sense fixed the bug (if it was browser related) I'll check again.

ps: Is there anyway I can help you support this project? This is one of the best slider scripts out there ;)

**Comment by davidghi** [comment]
I just tested in Edge and it seems to be working well as well; maybe they've fixed it or it was something isolated.

In the last months I've been slowed down by some personal issues but lately I've started picking things up, so I will be more responsive in the future and release some updates. However, any help is appreciated if you feel like you would like to do it.

Cheers

**Comment by wpexplorer** [comment]
Yes, I tested as well and can't recreate the problem. Thank you for your time!

ps: If you release some new things on CodeCanyon you should consider releasing a slider extension for the Visual Composer. I think it could do pretty well since there is so much demand for the Visual Composer plugin.

**Comment by davidghi** [comment]
I will consider this. Thank you for the suggestion! I might also bundle the extension in the main plugin.
