### ISSUE TITLE
Select dropdown is not working in android 5.0

### ISSUE THREAD

**Issue by phonegap20** [bqworks/slider-pro#141]
Hello,
I implemented this library in one of application..everything is working as expected but if i put select dropdown inside sdlider pro div that's not working even onchange event is not getting fired...i am not sure on which line i have to modify to make it working.
If i put touchSwipe: false everything is working fine..if i put it as true..since it's by default true..it allows selection from dropdown but selected value is not visible on dropdown.
I need touchSwipe feature in my app but it's causing issue as users are not able to see selected values.

Please check it at your end on android 5.0 and help me to provide a fix.

Thanks a lot.

**Comment by davidghi** [comment]
Please add the 'sp-selectable' class to the dropdown element.

Cheers.
