### ISSUE TITLE
Pressing "Enter" results in a uncaught TypeError

### ISSUE THREAD

**Issue by danielfuerst** [bqworks/slider-pro#142]
Hey there
I have found a strange behaviour of slider-pro. When pressing the enter key it results in following error message:
`Uncaught TypeError: Cannot read property 'click' of undefined
(anonymous function) @ jquery.sliderPro.min.js:8
n.event.dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3`
Check it out on the demo site: [Demo](http://bqworks.com/slider-pro/)

Is there an easy way to prevent this?

**Comment by davidghi** [comment]
Hi,

For now you can prevent it by setting the 'keyboard' option to false, but I'll add a fix for it in a future update.

Cheers.

**Comment by davidghi** [comment]
The latest update, 1.3, addresses this issue.
