### ISSUE TITLE
problem with fade effect

### ISSUE THREAD

**Issue by fabiobonzini** [bqworks/slider-pro#143]
Hello, i have a strange bug with fade effect :
I've ,in my wordpress project, a slider with image and text. when i've 4 slides on my slider, fade transition between slides is really not fluid.
BUT when i've just 3 slides in the same slider, problem with fade effect is less pronounced.
AND with just 2 slides, fade effect is perfect !
very strange !
i've test on FF, CHROME and SAFARI, same problem.

Have you a idea to resolve ?

**Comment by fabiobonzini** [comment]
a precision :
this fade effect bug is just when i slide n the normal direction (slide 1 > slide 2 > slide 3, ...). fade effect works good in the inverse direction (slide 3 > slide 2 > slide 1, ...)

**Comment by Snowbell92** [comment]
I am having kind of the same problem, with the swipe. on android chrome (50.0.2661.89, android 4.4.4) the swipe is not fluid. the image "pauses" for milliseconds before sliding to the next one.

**Comment by fabiobonzini** [comment]
look this animated gif to view the problem <iframe src="//giphy.com/embed/U6ou6GgiixSdG" width="480" height="366" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/U6ou6GgiixSdG">via GIPHY</a></p>
look this without problem <iframe src="//giphy.com/embed/fqrPlEanedg6Q" width="480" height="298" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/fqrPlEanedg6Q">via GIPHY</a></p>

**Comment by davidghi** [comment]
Hi,

Please try to set the 'fadeOutPreviousSlide' option to false.

Cheers.

**Comment by fabiobonzini** [comment]
hi david, i tried this, but it's worst ! my slider with 2 slides bug too with this property.
problem comes to number of slides. 1 and 2 slides => fade effect ok. more slide => fade effect bug

any other solution ?

**Comment by davidghi** [comment]
I tried locally with some images and text and the transition was pretty smooth. Can you post a link to your example?

**Comment by fabiobonzini** [comment]
hi david, look this another site web where i've same problem but also with just 2 slide: http://bit.ly/1WPyjsB 
slider configuration :
`	$( '#my-slider' ).sliderPro({
	    width: '100%',
	    height: 300,
	    fade : true,
	    fadeDuration : '1000',
	    arrows : false,
	    fadeArrows : false,
	    fadeOutPreviousSlide: false,
	    touchSwipe : true,
	    autoplayDelay : 3000,
	    autoplayOnHover : 'none',
	    buttons : true,
	    autoplay : true
	});
`
thanks !

**Comment by fabiobonzini** [comment]
hi david, 
i've resolve my problem, i had a transition property in an element on slides ! sorry for disturbance its my fault !

thanks for all
