### ISSUE TITLE
swiping animation is not smooth

### ISSUE THREAD

**Issue by Snowbell92** [bqworks/slider-pro#144]
First, the plugin is awesome, if I can get this fixed. The swiping transition seems to make the slide image "hesitate" for a few milliseconds before transitioning to the new slide. I tested using desktop firefox and and android chrome. I am using twitter bootstrap and my slide page also has a owl-carousel. Can you help me with this issue?

**Comment by davidghi** [comment]
Hi. Does this happen on desktop browsers as well or only mobile?

Cheers

**Comment by Snowbell92** [comment]
on both. very noticeable in Blackberry z30 (it starts wiping after about 1 second or so), slightly noticeable on android chrome (50.0.2661.89, android 4.4.4) and firefox 46.0.1. I'm uploading a screencast shortly so that you can view the problem. 

here's my slider setting: 

     $(document).ready(function () {
            $( '#slider' ).sliderPro({
                width: 1600,
                height: 600,
                arrows:true,
                fade: true,
                fadeArrows: false,
                autoplayOnHover: "none",
                fadeDuration : 700,
                waitForLayers: false

            });
            });

Thanks.

**Comment by Snowbell92** [comment]
actually, desktop doesn't look too bad ( i can live it with it). I am trying to take a screencast for mobiles.

**Comment by Snowbell92** [comment]
turns out, the smoothing problem was being created by my fixed positioned background. I changed that and everything is okay now.
