### ISSUE TITLE
"AutoPlay" with "loop" false should stop on last slide

### ISSUE THREAD

**Issue by wpexplorer** [bqworks/slider-pro#145]
The autoplay feature is awesome but it always goes through the slides. If the main "loop" parameter is set to false then autoplay should be destroyed once it reaches the last slide.

Thanks!

**Comment by davidghi** [comment]
I will consider this, but for now you can use this custom JavaScript:

```
$( '.slider-pro' ).on( 'gotoSlide', function( event ) {
	if ( event.index === $( this ).find( '.sp-slide' ).length - 1 ) {
		$( this ).data( 'sliderPro' ).stopAutoplay();
	}
});
```

Cheers!

**Comment by wpexplorer** [comment]
Awesome, Thanks!

**Comment by davidghi** [comment]
You're welcome!
