### ISSUE TITLE
Responsive is not working when width:100%

### ISSUE THREAD

**Issue by felipegrin** [bqworks/slider-pro#146]
I'm having problems setting my sliders as responsive when I set a width of 100%. When i change the width to any other value, it works normally. 

Here's a test I've made: http://www.felipegrin.com/test/

Is there any way to fix it? Maybe I'm doing something wrong?

**Comment by davidghi** [comment]
When you use a percentage width or height the slider can't calculate how it should scale down correctly, so you will have to help it a little by using the `aspectRatio` and the `autoScaleReference` options.

Cheers.

**Comment by felipegrin** [comment]
what shoud i put at autoScaleReference  since my slide is 100%?

**Comment by davidghi** [comment]
The size from which you want the content inside (i.e. layers) to start scaling down. For example, you could add 960.
