### ISSUE TITLE
Cannot overwrite youtube params

### ISSUE THREAD

**Issue by adamsheridan** [bqworks/slider-pro#148]
I have a youtube video inserted into SP:

`<a class="sp-video" data-event-action="playedHighlightsVideo" data-event-category="testButtons" href="//www.youtube.com/watch?v=YOUTUBEID?api=1&amp;autoplay=1&amp;modestbranding=1&amp;controls=0&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1&amp;allowfullscreen=true&amp;wmode=transparent&amp;iv_load_policy=3&amp;html5=1&amp;widgetid=1" data-video-preinit="true"></a>`

On click of the play button SP inserts the iframe URL as such:
`<iframe src="//www.youtube.com/embed/rNC6Pgvy5w8?enablejsapi=1&amp;wmode=opaque" class="sp-video" frameborder="0" allowfullscreen="allowfullscreen" data-video-init="true" id="widget2"></iframe>`

From what I can see this is caused by the following code: 
`src = provider === 'youtube' ? '//www.youtube.com/embed/' + id + '?enablejsapi=1&wmode=opaque' : '//player.vimeo.com/video/'+ id +'?api=1';`
[Source](https://github.com/bqworks/slider-pro/blob/master/src/js/jquery.sliderPro.video.js#L142)

Is there an example to overwrite these params? Specifically I would like to add modestbranding=0 and controls=0 without modifying the original SP code.

Thanks,
Adam

**Comment by davidghi** [comment]
Hi, Adam. If you need to specify additional parameters you can add them in the initial YouTube link: `<a class="sp-video" href="//www.youtube.com/watch?v=oaDkph9yQBs&controls=0&modestbranding=0">`

Cheers
