### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by wpexplorer** [bqworks/slider-pro#149]
I wasn't able to locate anything regarding this. Is it integrated already and if so how would I use it? Mostly the issues are with the thumbnails since they become a carousel they must be aligned to the right instead of the left and then rotate to the left instead of the right.

I am happy to pay/sponsor an update for RTL as well. Just let me know!

Thanks!!

**Comment by davidghi** [comment]
It's not supported yet, but I don't think it's difficult to add. I'll try it this week and let you know.

Cheers!

**Comment by wpexplorer** [comment]
Cool!

By any chance do you do custom work for hire? - I would love to pay you for an "audit" of one of my theme's javascript. I am not as good as you and would love your input.

And I am also looking for a freelancer to help with a demo importer for the same thing - is that something that would interest you? I will pay good money for that - it's about 70% finished but need some help finishing it.

Let me know if you would be interested in either. Thanks!

- Aj

**Comment by davidghi** [comment]
Hi, Aj. I didn't do much custom work lately, except for customizations for my CodeCanyon products, because I was focused on that, but since it's summer and business is not as good on CodeCanyon, I could do some freelancing. If you would like to discuss it, please email me at david.ghiurau@gmail.com

Cheers,
David

**Comment by davidghi** [comment]
I managed to add rtl support. You can check it out and let me know how it works for you. To enable it, you have to set the newly added `rightToLeft` option to true. This will set the direction to RTL for the slides, thumbnails and buttons/bullets, as well as swap the positions of the next and previous arrows.

Cheers!

**Comment by wpexplorer** [comment]
Awesome, thanks! Will send you a quick email ;)
