### ISSUE TITLE
Why i cant see the full image?

### ISSUE THREAD

**Issue by kfir91** [bqworks/slider-pro#151]
The image cut off in the small size and in the big size...
How can i set that the slider show the full image without crop it...?

**Comment by davidghi** [comment]
Please take a look at the `imageScaleMode` option. Depending on what look and functionality you want to achieve, you might also want to look at the `autoSlideSize` and `autoHeight` options.

Cheers.

**Comment by kfir91** [comment]
ok, tnx the problem solved
