### ISSUE TITLE
autoSlideSize not working on portrait images

### ISSUE THREAD

**Issue by apjmason** [bqworks/slider-pro#153]
Thanks for an amazing plugin!

I'm having trouble getting the autoSlideSize property to work correctly.  I've got a mix of landscape and portrait images, and my sense from the docs is that this property should display both at the same height but a mix of widths based on the image dimensions, as in [example 2](http://bqworks.com/slider-pro/#example2).

When I try to set it true, though, the width seems to be set based on the dimensions of the first image in the slider, so portrait images are cropped. For example, [this still](https://www.dropbox.com/s/puiiulbccb2sy8l/Screen%20Shot%202016-07-21%20at%2011.24.08%20AM.png?dl=0) shows the issue.

Here's my current code:

`$( '.slider-pro' ).sliderPro({
                width:'80%',
                arrows: true,
                fadeArrows: false,
                height:450,
                buttons:true,
                autoplay:true,
                autoSlideSize:true,
                visibleSize:'100%',
    }`

Is there some combination of what I have here that is overriding the autoSlideSize behavior? Thanks!

**Comment by davidghi** [comment]
Hi. Can you share a link to the actual implementation? I can't identify the problem from the screenshot.

Cheers!

**Comment by apjmason** [comment]
Hi, thanks for the response.  The code is implemented in a custom plugin for Omeka, and the site is not yet public, so it took me a while to set up an example implementation, but you should be able to see it at the link below.

[https://religionsmn.carleton.edu/exhibits/show/slider-test/peppers](https://religionsmn.carleton.edu/exhibits/show/slider-test/peppers)

The image of the single pepper is portrait (1920 × 2880 in the original) but is cropped to match the aspect ratio of the original.  

Thanks!

**Comment by davidghi** [comment]
Hi. It seems that the script you're using is an older one. Please download the latest version.

Cheers.

**Comment by apjmason** [comment]
The latest version did the trick.  Should have updated first!   Thanks
