### ISSUE TITLE
Loading Issue on Joomla SIte

### ISSUE THREAD

**Issue by monicawebmage** [bqworks/slider-pro#155]
Hello,

I have installed the slider on a Joomla! site here: http://www.stainlesscleans.co.uk/home-test

The issue is that occasionally when the page is first loaded the content from all slider layers seems to all display at once for a second which makes the slider look a bit distorted on first load.

Do you know what is causing this and how to fix it please?
![slider-pro-joomla-issue](https://cloud.githubusercontent.com/assets/17324096/17084197/fc979baa-51af-11e6-8eda-fed353802cd4.jpg)

Thanks,
Monica.

**Comment by davidghi** [comment]
Hi, Monica. There is a small delay until the slider's JavaScript code is executed and the slider rendered properly. However, you can control how the slider is styled before its code is executed by using the `.sp-no-js` class. For example, you could hide it completely: `.sp-no-js {visibility: hidden}`.

Cheers!

**Comment by monicawebmage** [comment]
Hi David,

Thanks so much - that's really good to know!

Monica.
