### ISSUE TITLE
Thumbnail resize issues when resizing below breakpoint value.

### ISSUE THREAD

**Issue by razmarin** [bqworks/slider-pro#159]
Hello. So I have the following issue. If i resize the window below the specified breakpoint value, I get a "Uncaught TypeError: Cannot read property 'setIndex' of undefined".

Example:  
My slider pro configuration: 
{  
   autoplay:false,
   width:250,
   height:370,
   imageScaleMode:'contain',
   orientation:'vertical',
   arrows:true,
   thumbnailsPosition:'left',
   thumbnailArrows:true,
   buttons:false,
   thumbnailWidth:70,
   thumbnailHeight:70,
   touchSwipeThreshold:10,
   loop:false,
   breakpoints:{  
      325:{  
         thumbnailWidth:50,
         thumbnailHeight:50
      }
   }
}

Browser: Google Chrome 51.0.2704.106 (64-bit), having device toolbar activated.
Issue: Resizing below 325 generates "Uncaught TypeError: Cannot read property 'setIndex' of undefined" -> line in question being:

```
  that.thumbnails[ index ].setIndex( index );
```

Thanks in advance.

**Comment by davidghi** [comment]
Can you share a link?
