### ISSUE TITLE
Weird Issue on Resizing

### ISSUE THREAD

**Issue by nnarbone** [bqworks/slider-pro#16]
Hey,
First off thanks for the plugin. Do you realize how hard it is to find a vertical tabbed content slider?? Anyways, I seem to be having a very weird issue: http://rs.rotaryswing.com/rst-golf-instruction-articles

Notice when you land on this page the slider looks funny. The thumbs sit on top of the poster image. Not cool. But when you resize the browser and bring it back to a full browser window it seems to increase the slider width just how I specified in the js options you provide. I have not added anything additional to this page or your code. I migrated over the examples.css as well as the minified js file and the css file you provide in the .zip

It is a weird bug and I sat up for the last couple hours trying to remedy it before coming to you.

Any help will be much appreciated. Thanks!

**Comment by davidghi** [comment]
Update 1.2.0 includes the CSS code above.
