### ISSUE TITLE
Position centerCenter doesn't work properly at lower resolutions

### ISSUE THREAD

**Issue by spin80** [bqworks/slider-pro#160]
Hi,

Something is wrong with scaling layers. The layer, which should be at the center moves to the right
![screen1](https://cloud.githubusercontent.com/assets/21078664/17732418/f089287c-6471-11e6-9d2b-596b37a46e9c.png)
![screen2](https://cloud.githubusercontent.com/assets/21078664/17732444/12394f60-6472-11e6-982c-02c25a8cdc64.png)

My settings:

`$('.slider_pro').sliderPro({
        height: 458,
        width: 114,             
        responsive: true,
        aspectRatio: -1,
        imageScaleMode: "cover",
        centerImage: false,
        autoHeight: false,
        autoSlideSize: false,
        startSlide: 0,
        shuffle: false,
        allowScaleUp: false,
        orientation: "horizontal",
        forceSize: "none",
        loop: true,
        slideDistance: 0,
        slideAnimationDuration: 700,
        heightAnimationDuration: 700,
        visibleSize: "auto",
        fade: true,
        fadeOutPreviousSlide: true,
        fadeDuration: 500,
        autoplay: true,
        autoplayDelay: 5000,
        autoplayDirection: "normal",
        autoplayOnHover: "pause",
        arrows: false,
        fadeArrows: true,
        buttons: false,
        keyboard: true,
        keyboardOnlyOnFocus: false,
        touchSwipe: false,
        touchSwipeThreshold: 50,
        fadeCaption: true,
        captionFadeDuration: 500,
        fullScreen: true,
        fadeFullScreen: true,
        waitForLayers: false,
        autoScaleLayers: true,
        autoScaleReference: -1,
        smallSize: 480,
        mediumSize: 768,
        largeSize: 1024,
        updateHash: false,
        thumbnailWidth: 100,
        thumbnailHeight: 80,
        thumbnailsPosition: "bottom",
        thumbnailPointer: false,
        thumbnailArrows: false,
        fadeThumbnailArrows: true,
        tumbnailTouchSwipe: true,
        centerSelectedSlide: false,`
Layer setting:
`<div class="sp-layer" 
       data-vertical = "10%"                         
       data-position = "centerCenter"                        
       data-show-transition = "down"                         
       data-show-offset = "50"                          
       data-show-duration = "400"                          
       data-show-delay = "800"                          
       data-hide-transition = "left"                         
       data-hide-offset = "50"                       
       data-hide-duration = "400"                        
       data-hide-delay = "10"                       
        data-show-duration = "-1" >

```
    <div class="uppercase font-bold block">
        <p class="font-withe" style="text-align: center;"><span class="color-white font-size-40">Smart Business Solutions</span></p>  
    </div>
```

</div>`

I tried different layer width settings (px and %) and nothing helped.

**Comment by spin80** [comment]
The problem is when the width of the element is larger than the screen width.

**Comment by davidghi** [comment]
I would recommend using CSS media queries to set a smaller font size on smaller screens.

Cheers!

**Comment by spin80** [comment]
Maybe if the layer is longer than the width of the slider, the width of the layer should be 100%
