### ISSUE TITLE
Full height centered background

### ISSUE THREAD

**Issue by Lolandez** [bqworks/slider-pro#161]
Is possible to stay with the background at full height and centered at any resolution?
I mean that the height can be assign like: height:100% without distort its width, it is just centered across all the available space.

Like in the imagen bellow

![example](https://cloud.githubusercontent.com/assets/21281772/18030529/2cbbc962-6c7e-11e6-8070-ce0b2b66e321.jpg)

**Comment by davidghi** [comment]
If I understand your requirement correctly, I guess it would be possible. In addition to setting the `height` to 100%, you need to set `imageScaleMode` to `cover`.

Cheers!
