### ISSUE TITLE
Half the slide not visible on Safari

### ISSUE THREAD

**Issue by finkbg** [bqworks/slider-pro#162]
On Safari (Mac) half the slides are not visible. I suspect this only occurs when an adblocker is enabled, but cannot be sure. The funniest thing is it happens sporadically. On the next refresh of the page everything works fine. I pinned it down to an inline style for img.sp-image, and specifically the margin-left property, which seems to be incorrectly set. It appears this is set through js with marginLeft, but my skills in js are extremely limited. I hope someone can help. 

Thanks.

**Comment by davidghi** [comment]
Hi,

Yes, it's mostly likely the ad block extension, which interferes with the JavaScript code. You can prevent this by setting the `centerImage` option to false.

Cheers!
