### ISSUE TITLE
Slide transition lagging on mobile devices

### ISSUE THREAD

**Issue by amyth** [bqworks/slider-pro#163]
First of, Thanks for such a feature rich plugin. I am using slider-pro in one of my projects and the slide transition between screens are really lagging on some of the mobile devices especially android. on iOS (iPhone 6) it works pretty well but user could feel a very slight lag just after the slide transition is about 70-75% completed.

you can check the project at http://staging.gigzag.in

Any idea about what might be wrong ?

**Comment by davidghi** [comment]
Hi. It's because of the content inside the slider, which is a little more complex than simple images. Less performant devices might cause lagging like that. The slider is already optimized, so there's not much you can do.
