### ISSUE TITLE
Slide transitions with 2 slides

### ISSUE THREAD

**Issue by jeremyraymond** [bqworks/slider-pro#167]
Hello! Thanks for the plugin, it's very good. However, I ran into a bit of an issue when I just had two slides. When the slide transitions, the slide that was just displayed immediately disappears and goes to the right of the next slide. This makes for a very jarring transition. I also can't drag the slide to the right and get the slide that was just displayed, I only get whitespace. Is there a way for me to fix this?

Thanks!

**Comment by davidghi** [comment]
Hi. If you're using only two or three slides, you should set the `loop` option to false. It has been discussed here: https://github.com/bqworks/slider-pro/issues/5

Cheers!
