### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by ali-hellani** [bqworks/slider-pro#168]
Hi,

Does this plugin support **RTL** (right to left) languages  ?!

**Comment by davidghi** [comment]
Hi. Yes, you need to set `rightToLeft` to true.

Cheers!

**Comment by ali-hellani** [comment]
Oops, it's my mistake, i didn't notice it in the properties, i was searching for the word (RTL) :)
Anyway thanks for your quick reply.

**Comment by davidghi** [comment]
You're welcome! :)
