### ISSUE TITLE
Deep Linking Question

### ISSUE THREAD

**Issue by hudsonperalta** [bqworks/slider-pro#17]
First of all thanks a million for building this. I've been scouring Earth for something like this. I plan on purchasing your WP plugin to show my appreciation.

My question is, when the arrows or buttons are clicked can they use my custom ID (ie. /my-slider or /slide-name) in the link as apposed to /0 or /1?

Thanks again, and I look forward to hearing back from you.

**Comment by davidghi** [comment]
Hi. I'm glad you like the slider. By default, it's not possible, but it's easy to add. I will consider adding this feature in a future update, but for now what you need to do is go inside the 'initDeepLinking' function and replace

`window.location.hash = that.$slider.attr( 'id' ) + '/' + event.index;`

with this:

`window.location.hash = that.$slider.attr( 'id' ) + '/' + that.$slider.find( '.sp-slide' ).eq( event.index ).attr( 'id' );`

**Comment by hudsonperalta** [comment]
@davidghi Perfect! Thanks so much!
