### ISSUE TITLE
Opacity background big problem

### ISSUE THREAD

**Issue by smolek1980** [bqworks/slider-pro#170]
Welcome

sorry for my english :)

i want ask how i can remove a black screen when i open a image ( example 3 ) when i clixk image fullscreen i will get all ok but i want to add opacity and see background website now i have a black background i tried all what i can do with css doesnt work... Can you explain how can i do opacity fullscreen background ?

Ty very much

![st1](https://cloud.githubusercontent.com/assets/22807953/19337604/07c1d67a-9117-11e6-86f1-2006ad88ca35.jpg)

**Comment by davidghi** [comment]
Hi. It's not possible to make the background transparent, only change its color. However, you could use the lightbox instead of the HTML5 fullscreen capability if you want to have visible content under the image.

Cheers!
