### ISSUE TITLE
Put slider in pause with fancybox

### ISSUE THREAD

**Issue by mdrick** [bqworks/slider-pro#173]
Hi,

I need some help please.

I don't find a callback function to put slider pro in pause with fancybox.
When someone click on a photo I would like to put the slider on pause.

Thank you

**Comment by davidghi** [comment]
Hi. Please try this code:

<pre>
$( ".slider-pro" ).each(function(){
	var slider = $( this );

	slider.find( ".sp-image" ).parent( "a" ).on( "click", function( event ) {
		event.preventDefault();
	
		if ( slider.hasClass( "sp-swiping" ) === false ) {
			var sliderInstance = slider.data( "sliderPro" ),
				isAutoplay = sliderInstance.settings.autoplay;

			$.fancybox.open( slider.find( ".sp-image" ).parent( "a" ), {
				index: $( this ).parents( ".sp-slide" ).index(),
				afterShow: function() {
					if ( isAutoplay === true ) {
						sliderInstance.settings.autoplay = false;
						sliderInstance.stopAutoplay();
					}
				},
				afterClose: function() {
					if ( isAutoplay === true ) {
						sliderInstance.settings.autoplay = true;
						sliderInstance.startAutoplay();
					}
				}
					
			});
		}
	});
});
</pre>

Cheers.
