### ISSUE TITLE
add remove slide

### ISSUE THREAD

**Issue by rtrepis** [bqworks/slider-pro#174]
I can remove & add image (slide) with button  ?¿

**Comment by davidghi** [comment]
Yes, it's possible. You just have to call the `update` method after you add/remove slides: 

<pre>
slider.find( '.sp-slide' ).eq( 0 ).remove();
slider.find( '.sp-slide' ).eq( 1 ).remove();

slider.find( '.sp-slides' ).append('<div class="sp-slide"><img class="sp-image" src="http://bqworks.com/accordion-slider/images/image4.jpg"/><p class="sp-layer">Layer 1</p><div class="sp-layer as-static as-white">Layer 2</div><h4 class="sp-layer">Layer 3</h4></div>');

$( '#my-slider' ).sliderPro( 'update' );
</pre>

Cheers!
