### ISSUE TITLE
Full Screen Button Not Display In Safari Browser

### ISSUE THREAD

**Issue by infigosoftware** [bqworks/slider-pro#175]
I tested slider pro demo into all browsers.

There is only one problem, **Fullscreen Button** appears on slide not working into **Safari Browser**.

Check the screenshots.

**1 Fullscreen Button Displaying in Google Chrome**

![full screen button in google chrome](https://cloud.githubusercontent.com/assets/23446119/20255587/d887438e-aa63-11e6-9481-79cffe8b18d7.png)

**2 Fullscreen Button Displaying in Mozilla Firefox**

![full screen button mozilla firefox](https://cloud.githubusercontent.com/assets/23446119/20255595/e2f46c34-aa63-11e6-99d0-300e46c2e657.png)

**3 Fullscreen Button Not Displaying in Safari**

![full-screen button not in safari browser](https://cloud.githubusercontent.com/assets/23446119/20255598/e802123a-aa63-11e6-9e7b-ef5689397e55.png)

Please, I need your help to resolve this issue. I think is's a character encoding problem, the fullscreen button is created using ASCII code, which is not supporting into Safari Browser.

Do I replace the icon with another one?

Any help is really appreciated.

Thanks

**Comment by davidghi** [comment]
Hi. Is that Safari for Windows (because the button works fine in Safari for OSX) ? That version was discontinued, so it's quite outdated and people shouldn't be using it anyway. I think its market share tends to 0.

Cheers.

**Comment by padisio** [comment]
I have the same problem, I can see the button in pc and android phone but not in my iphone X. The icon is gone so I'm unnable to use the fullscreen feature.

**Comment by davidghi** [comment]
Hi. The iPhone doesn't support the HTML5 full-screen API.
