### ISSUE TITLE
How to vertically show multiple slides while rotating 1 in 1 out

### ISSUE THREAD

**Issue by buaziz** [bqworks/slider-pro#18]
i want to start by saying that this is a great project, very clean  code and nice  documentation.

but i did not see any examples of a vertical slide while showing multiple slides in the visible area.

let me explain more.

if you have a vertical box of height 500px
and each slide is 100px
and you have 10 slides
i want to show 5 slides in the visible area once the slider is initiated
then move 1 slide out of the visible area from the top, while entering an new slide from the bottom.

can this be achieved.

thanks

**Comment by davidghi** [comment]
Hi. Thank you for the compliments! Obviously, I can't create examples for every possible variation, but what you're describing is possible. You just have to set the height to 100, visibleSize to 500 and orientation to 'vertical'.

**Comment by buaziz** [comment]
i forgot to mention that i was not using "sp-image" i was using "sp-layer"
i figured it out. 
i needed to add "sp-static" to the div with "sp-layer". then the whole slide containing images and other content showed in the "visibleSize"
thanks.
