### ISSUE TITLE
BreakPoints

### ISSUE THREAD

**Issue by rahisarm** [bqworks/slider-pro#183]
Hi..Is it possible to change the data-position when resized.I need to change the data-position of my slide to bottomCenter when it resized to mobile version.
Thanks in advance.

**Comment by davidghi** [comment]
Hi. If the layer was already initiated, you can't update its properties. However, if you really want to achieve that functionality, you could destroy the slider when it's resized to mobile version, update the HTML with the new data-position, and then re-instantiate it.

Cheers!
