### ISSUE TITLE
Full screen mode when clicking on the image?

### ISSUE THREAD

**Issue by Lutex** [bqworks/slider-pro#187]
Hi, I'm trying to open in browsers with Full Screen support, directly in full screen when I click on the main slider. But I can not.
Can you tell me how I could do this?

**Comment by davidghi** [comment]
Hi. You could manually trigger a click on the fullscreen button:

```
jQuery( '.sp-slide' ).click(function(){
    jQuery( '.sp-full-screen-button' ).trigger( 'click' );
});
```

Cheers!

**Comment by Lutex** [comment]
https://github.com/bqworks/slider-pro/issues/237

**Comment by padisio** [comment]
> Hi. You could manually trigger a click on the fullscreen button:
> 
> ```
> jQuery( '.sp-slide' ).click(function(){
>     jQuery( '.sp-full-screen-button' ).trigger( 'click' );
> });
> ```
> 
> Cheers!

This work pretty well in all devices except on iphone. Any solution?
Thanks

**Comment by davidghi** [comment]
Hi. The iPhone doesn't support the HTML5 full-screen API.
