### ISSUE TITLE
Please Add the Pre Loader

### ISSUE THREAD

**Issue by infigosoftware** [bqworks/slider-pro#188]
Every time slider load on page.

All images are scattered on whole page.

I read about lazy loading but not going to work.

REQUEST: Could you please add a preloader settings option?

Thanks

**Comment by davidghi** [comment]
Hi. That happens before the JavaScript is executed. If you want, you can hide the slider until it's styled properly. First, you add the `sp-no-js` class next to the 'slider-pro' class. Then, add this CSS:

```
.sp-no-js {
     visibility: hidden;
}
```

This would be the easiest approach, but there are others too if you want to have something visible while the slider is loading.

Cheers!
