### ISSUE TITLE
Slider.update() don't show the correct thumbnails in order.

### ISSUE THREAD

**Issue by Leetcore** [bqworks/slider-pro#189]
Hello,

i add dynamically new slides to slider and call slider.update() after that. But sliderpro adds the thumbnail to the end of the list and not where they should be in HTML order.

document.querySelector('#my-slider .sp-slides').insertAdjacentHTML('afterbegin', renderHTML)
renderHTML is the slide HTML (sp-slide div)
var slider = $( '#my-slider' ).data( 'sliderPro' );
slider.update()

I want to add the new slide between the other slides.

What happens: New slide is the first one. New thumbnail is the last one. Linking is mixed up.

The first thumbnail has now a wrong link to the new slide and the new thumbnail is at the end of the list and linked also wrong to the old first slide.

Can anyone help me or reproduce the problem?

Best regards!

**Comment by davidghi** [comment]
Hi. This will work fine if you add slides and thumbnails at the end of the slider. In other cases, I would recommend destroying the slider before updating the HTML and then re-instantiate it. This should work without problems.

Cheers!

**Comment by Leetcore** [comment]
Thanks for your comment.
I know that it worked if i add the slide at the end. I want to add the new slide at position Destroying (HTML stays the same) and reinitialize also didn't work. :-( I think because it does'nt reset the HTML to the state before the init.

**Comment by davidghi** [comment]
I actually tested it before commenting and it worked fine for me. If you want, please share a link and I'll take a look.

**Comment by Leetcore** [comment]
Thanks for your help.

Here is my demo: https://jsfiddle.net/gq1gjm8b/3/

Click "new slide" and after that click some thumbnails. Did i something wrong?

**Comment by Leetcore** [comment]
I tested destroy and init. It worked in my example. I try this in the my project again.

**Comment by Leetcore** [comment]
Could be a race condition problem.
