### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by SaphiLC** [bqworks/slider-pro#191]
line 2834 
this.$slide.find( '.sp-layer:not([ data-layer-init ])' ).each(function() {

the space in _])' ).each_ is not a real space, deleting that space and adding  a new one or leaving it without space fixed the issue, so its probably a weird symbol that looks like a space

![error](https://cloud.githubusercontent.com/assets/18705494/24676252/e9c3d11e-1947-11e7-8c8e-5774bf6e10f4.png)

**Comment by davidghi** [comment]
Hi. This is quite strange. I'm pretty sure I added a space when I wrote the code and it also wasn't reported before. Anyway, thank you for letting me know.

Cheers!
