### ISSUE TITLE
Thumbnails don't seem to work for me

### ISSUE THREAD

**Issue by andrewmoise** [bqworks/slider-pro#194]
I'm using Slider Pro (via manual inclusion, not through the plugin) on this page:

http://www.oomyungdoe-ne.com/home-page-2017-04/

It looks excellent! Thank you very much for making this. The thumbnails don't behave like I want them to though; clicking on the middle thumbnail always behaves as if I'd clicked the one one step to the right (generally it seems like it's processing clicks on the thumbnails incorrectly). I don't *think* I've set up anything on the page in a way that would lead things to fail (though of course I could be wrong). Is this a failure with Slider Pro, or something I need to look into / debug on my own?

Thanks for your help.

**Comment by davidghi** [comment]
Hi.

There seems to be some problems in the HTML markup. There are </p> and <br/> tags inside the slider's HTML, in places where they shouldn't be.

Regarding the thumbnails, it seems you've removed them. If you add them back I'll take a look at the issue you've mentioned.

Cheers!
