### ISSUE TITLE
Not work in the 'Bootstrap Tabs and Pills'

### ISSUE THREAD

**Issue by 5987dogking** [bqworks/slider-pro#195]
Not work in the 'Bootstrap Tabs and Pills'
0.0

**Comment by davidghi** [comment]
Hi. If the slider was instantiated inside a hidden tab or pill, it can't resize itself properly; you will need to programatically resize by using $('#my-slider').sliderPro('resize') it once the tab becomes visible.

Cheers

**Comment by jarodium** [comment]
Still having the margin issue stated in #82  
The margin is being applied inline by the script. I will check css to see if I can solve this.
