### ISSUE TITLE
Fullscreen on smartphone or tablet (Safari browser)

### ISSUE THREAD

**Issue by baden32** [bqworks/slider-pro#196]
Fullscreen display can be activated on desktop and android browser but no way to get the same behaviour on Safari browser (iMac, iPhone or iPad). Is the html5 fullscreen option not available on these devices?

**Comment by davidghi** [comment]
Hi. Safari on iOS doesn't support the HTML5 FullScreen API, so the feature feature is disabled there.

Cheers
