### ISSUE TITLE
WP version issue...

### ISSUE THREAD

**Issue by mnakalay** [bqworks/slider-pro#199]
Hello,
I know this is not the place but I saw the WP version of Slider Pro on a client's website and since I'm not a client on Code Canyon I don't think I can leave you this message there.

When you update a slider, you are supposed to delete all slides and all slide layers before inserting them again. But in your save_slider() function you are deleting the slides twice but not the layers so all the layers are left in place in the DB referencing slides IDs that don't exist anymore.

Line 669:

```
$wpdb->query( $wpdb->prepare( "DELETE FROM " . $wpdb->prefix . "slider_pro_slides WHERE slider_id = %d", $id ) );

$wpdb->query( $wpdb->prepare( "DELETE FROM " . $wpdb->prefix . "slider_pro_slides WHERE slider_id = %d", $id ) );
```

I thought I'd let you know

Take care

**Comment by davidghi** [comment]
Thank you for the heads up! I will correct it. By the way, there is a dedicated support system for the WordPress version: support.bqworks.com

Cheers!

**Comment by mnakalay** [comment]
I'll keep that in mind if I find another bug :)
