### ISSUE TITLE
100% width and height of viewport

### ISSUE THREAD

**Issue by timkirtley** [bqworks/slider-pro#20]
Hi,

I'm trying to create a slider that is 100% the width and height of the viewport.   I have the slider inside a div that is already has an explicit height set, but when I set the slider to '100%' I dont have any luck - it just collapses to 0 height.  I've tried adding the following css:

.slider-pro,
.sp-slides-container,
.sp-slides {
	height: 100%;
}

and that means my .sp-image slide is now full height of its container but the image for some reason is not centered in the slide, there is a margin-left that is pushing the image halfway out of the viewport.

What I have tried is when initialising the plugin, setting the height to a variable that contains the viewport height which means when the slider loads it does indeed fill the viewport and with correctly centered slides.  The problem is, if the browser window is resized then the height of the slider remains at the initial height.  Is there a way I can re-set the height value via the api once the slider is going?

**Comment by hudsonperalta** [comment]
Try setting the width & height in Properties

```
$( '.slider-pro' ).sliderPro({
    width: '100%',
    height: '100%',
    forceSize: 'fullWidth'
});
```

**Comment by davidghi** [comment]
@timkirtley If you set the height to 100%, you must make sure that the container in which you add the slider also has a height of 100%. If that container doesn't have any defined height, then 100% out of nothing will be nothing. That's why the slider collapses. So, if you add the slider directly in the `body`, you would need to add this CSS:

```
html, body {
    height: 100%;
}
```

The other option is to set the `forceSize` option to `fullWindow`.

**Comment by timkirtley** [comment]
Thanks for the reply.  The slider is indeed inside a div that has a px height set which is what I dont understand..  .actually inspecting the main slider container '.slider-pro.sp-horizontal', it gets 'width: 100%' and 'max-width:100%' added to it but no height style?

**Comment by davidghi** [comment]
A link to your page would help. Also, please remove the extra CSS you added.

**Comment by davidghi** [comment]
No further answer, so I assume the issue is resolved.

**Comment by timkirtley** [comment]
Hi David,
Sorry, I had to change the slideshow for one I've used in the past as was up against it with a deadline.  I'll have another try with it later.
Thanks for getting back to me though.

**Comment by davidghi** [comment]
No problem :) I like to keep the Issues section clean, so I close issues if there's no response from the user AND if the reported issue doesn't seem to be a bug. If you'll have another try later and experience problems feel free to reopen the issue or submit a new one.

**Comment by timkirtley** [comment]
Yeah I noticed that - tidy issues section was one of the reasons I tried the plugin in the first place :)


On 30 Jan 2015, at 12:18, David Ghiurau <notifications@github.com> wrote:

No problem :) I like to keep the Issues section clean, so I close issues if there's no response from the user AND if the reported issue doesn't seem to be a bug. If you'll have another try later and experience problems feel free to reopen the issue or submit a new one.
