### ISSUE TITLE
couple of glitches

### ISSUE THREAD

**Issue by ukguy** [bqworks/slider-pro#202]
Hi there, brilliant slider.
I have a couple of glitches I'm struggling to find the solution for:

See https://xxxxtemporarily-removedxxxx
Scroll down abit for the slider-pro

1. It's set to forceSize: 'fullWindow' but some images don't resize - this can be seen at with the browser at 1000px wide. If you do a very slight window resize, it corrects itself. I wonder if I can add a resize event somewhere?

2. Images use data-src and conditional sizes, but lazy load does not work. This slows the page load down. I've tried everything but can't find why.

If you can help that would be appreciated!

**Comment by davidghi** [comment]
Hi. If you add the slider back, please let me know and I'll take a look.

Cheers!
