### ISSUE TITLE
responsive problem in display:table container

### ISSUE THREAD

**Issue by farbodchitsaz** [bqworks/slider-pro#203]
i'm using pro slider in my project and i embeded slider element in a container that is display:table , when i resize browser to smaller slider element does not be smaller too, and crash the responsive design, what can i do?
![problem](https://cloud.githubusercontent.com/assets/28596093/25897081/cfd82dde-359b-11e7-9aad-fbd752defa09.png)

**Comment by davidghi** [comment]
Do you have the site online or only locally? I would like to take look.

Cheers
