### ISSUE TITLE
Black Image on Chrome Android 

### ISSUE THREAD

**Issue by frenchdonah** [bqworks/slider-pro#205]
Hi, 

At this link I've a sliderpro
https://www.websitetests2.it/viator-offerte/5042NYCBAT/crociera-con-cena-in-battello-a-new-york/

It works well everywhere, Only I have a problem with Chrome for some models of Android, for example in asus zen phone 3 (Android 7.0) or in nexus 4, the big image is always black even if I click on the thumbnails.

Here is a screenshot: 

![img-20170523-wa0024](https://cloud.githubusercontent.com/assets/24420115/26360812/64f51836-3fd9-11e7-95f2-4999d3782584.jpg)

Thank you for your attention

**Comment by davidghi** [comment]
Hi. I can't access your page, but did you test to see if the problem occurs with the showcased examples as well or only in your page? It could be an implementation error.
