### ISSUE TITLE
problem with item on slide

### ISSUE THREAD

**Issue by fabienlm** [bqworks/slider-pro#208]
Hi, 
i've a problem on a website that I can not solve.
look on http://www.lamaisondesarchis.com/#carousel (carousel which title is "nos produits phares du moment").
On sliding to left, item on left disappear. i would like this item don't disappear, just sliding out of window (like on your example n°2 on http://bqworks.com/slider-pro/#example2)

Ahve you any idea ?

**Comment by davidghi** [comment]
Hi. The problem is that there are too few slides in the slider. I've discussed the issue here: https://github.com/bqworks/slider-pro/issues/5 

If you want to prevent that behaviour, you need to either add more slides or disable the `loop` option.

Cheers!
