### ISSUE TITLE
.sp-selected Added to main slide

### ISSUE THREAD

**Issue by hudsonperalta** [bqworks/slider-pro#21]
If I change slides the class .sp-selected gets added to the .sp-slide but if I go to the main page with no hashtags the class doesn't get added to the first slide. Is there a way to get the class added to the main slide after initialization?

**Comment by davidghi** [comment]
You could try to add it directly in the HTML code you create.

**Comment by hudsonperalta** [comment]
Yea, I tried that, I am doing CSS animations once the class .sp-selected gets added so if I hard code it then they don't animate. I was thinking ```if index 0 then add class .sp-selected```

I'll keep trying thank you.

**Comment by davidghi** [comment]
You can use the `init` event to add the class immediately after the initialization. You will need to pass the handler to this event in the list of options because if you pass it later it will be too late and it won't fire:

```
$( '.slider-pro' ).sliderPro({
    ...
    init: function() {}
});
```

**Comment by hudsonperalta** [comment]
How do I get the index in the init?

So then I can do ```if( index === 0 ) { ... }```

**Comment by davidghi** [comment]
The `init` is fired only once, so you don't need to check the index; you simply add the class to the first slide.

**Comment by davidghi** [comment]
The 'sp-selected' class is added by default to the initially selected slide in version 1.2.0.

**Comment by hudsonperalta** [comment]
@davidghi Awesome! Thank you
