### ISSUE TITLE
Remove th sp-layers on smaller screens

### ISSUE THREAD

**Issue by roboticdogmodz** [bqworks/slider-pro#210]
Hi! I really like your slider-pro however I cannot remove the 

**p** class="sp-layer sp-black">ipsum lorem text box <**/p** 

 tag on say a mobile device.

![comp01](https://user-images.githubusercontent.com/30252019/28300668-41c1548e-6bc0-11e7-9197-c6afe7d61ed4.JPG)

If you have a look at the image, the left picture displays the slider on a mobile device however I want to remove the text altogether.

If you could please help with the syntax, I would really appreciate it! (I am _not_ using wordpress)

Or what are my options? can I attach it underneath?
Thanks

**Comment by davidghi** [comment]
Hi. You can try this: `@media(max-width:500px){ .sp-layer{ display: none; } }`

Cheers!
