### ISSUE TITLE
Resize images full screen on mobile

### ISSUE THREAD

**Issue by felipelop** [bqworks/slider-pro#211]
Currently, images are adjusted by the size of screen, but this distorts them. I would like to change images size when i'm in full screen. In the element style of the image, this css appears: 
style="width: auto; 
         height: 100%; 
         margin-left: -453px; 
         margin-top: 0px;"

And I would like to change for that:
style="width: 100%; 
          height: auto; 
          margin-left: 0px; 
          margin-top: 190.875px;"

This example is for screen 375x667. Thanks.

**Comment by davidghi** [comment]
Hi. You could change the imageScaleMode option from 'cover' to 'contain', so the image will become fully visible instead of it being cropped.

Cheers

**Comment by felipelop** [comment]
Man, you're the best! Thank you so much.

**Comment by davidghi** [comment]
You're welcome! :)

**Comment by markgenest** [comment]
Hi,

There is a problem with this function when clicking into and out of full screen mode.

**Desired Function:**
When images are set to full width/auto height, clicking into full screen mode set to `imageScaleMode: 'contain'` should show entire image (uncropped) in full screen. When exiting full screen mode, images should be resized back to full width/auto height.

**Actual Function**
When images are set to full width/auto height, clicking into full screen mode set to `imageScaleMode: 'contain'` shows entire image (uncropped) in full screen. When clicking out of full screen mode, image widths are now set to 'contain' and DO NOT resize back to full width/auto height. 

Is there a way to fix this? Something like:

```
fullScreen: {
    enabled: true,
    trigger: 'click',
    imageScaleMode: 'contain'
}
```

So the imageScaleMode will only function for the full screen mode?

Everything else works great! Thanks in advance.

**Comment by davidghi** [comment]
Hi,

If you want to have `imageScaleMode: cover` when the slider is not in full-screen mode and `imageScaleMode: contain` when the slider is in full-screen mode, you can use this code:

```javascript
$( '.slider-pro' ).on( 'sliderResize', function() {
	var slider = $( this ),
	    scaleMode = slider.data( 'sliderPro' ).settings.imageScaleMode;
				
	if ( slider.hasClass( 'sp-full-screen' ) && scaleMode !== 'contain' ) {
		slider.sliderPro( 'imageScaleMode', 'contain' );
	} else if ( ! slider.hasClass( 'sp-full-screen' ) && scaleMode !== 'cover' ) {
		slider.sliderPro( 'imageScaleMode', 'cover' );
	}
} );
``` 

Cheers!

**Comment by markgenest** [comment]
I managed to use css to modify but I will try that. Thanks!

**Comment by davidghi** [comment]
You're welcome!
