### ISSUE TITLE
opacity layer on next and previous images that are visible on the sides

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#213]
is there a way to add a colored opacity layer on the previous and next images?  this gets tricky when the slider is really wide and more than 3 images are visible but if set up that way the center image would be visible but then the partial images on the sides for the previous and next images would have an adjustable opacity layer to slightly gray them out as an example.  this creates a focus on the main image but still shows images left and right.  some other sliders have this feature and would be nice if this were added or available.

Here is an example of another carousel with the opacity layers added:
http://coolcarousels.frebsite.nl/c/2/coolcarousel.html

**Comment by davidghi** [comment]
It easy to achieve something similar with CSS. Instead of using static opacity layers on top of the slider, you can change the opacity of the side slides:

```
.sp-slide {
    opacity: 0.3;
    transition: opacity 1s;
}

.sp-selected {
    opacity: 1;
}
```

Cheers!

**Comment by walkoffhomerun** [comment]
that worked.  for anyone else i just added the code above as the very last lines to the CSS file and it worked just fine

**Comment by walkoffhomerun** [comment]
david....this on is 2 yrs old and  you were able to get me the faded opacity on the previous and next sliders but is there a way to make it a faded color overlay?  your method just reduced the opacity of the image itself but i would like a darker overlay like 50% black.  i have tried 'color' and 'background-color' on ".sp-slide" but it does not work.

**Comment by davidghi** [comment]
Hi. Adding an overlay would be more complicated, but you can add the black background to the slide and set the transparency only on the image, not the entire slide:

```css
.sp-slide {
    background-color: #000;
}

.sp-image {
    opacity: 0.5;
    transition: opacity 0.5s !important;
}

.sp-slide:hover .sp-image,
.sp-selected .sp-image {
    opacity: 1;
}
```
Best,
David
