### ISSUE TITLE
Version 1.3 not available in bower

### ISSUE THREAD

**Issue by alexcoroza** [bqworks/slider-pro#219]
I am experiencing a bug in version 1.2.2 and I read that it was fixed in version 1.3 so I ran "bower install slider-pro#1.3 --save" but it said that the version doesnt exist. Tried running "bower install slider-pro --save" but it only installs version 1.2.2

**Comment by davidghi** [comment]
Thank you for the heads up, I will take a look. In the mean time you can download the updated files from Github.

Cheers
