### ISSUE TITLE
Slider Pro with foundation 5

### ISSUE THREAD

**Issue by boducoscar** [bqworks/slider-pro#22]
Hi there,

Your slider is working pretty good with many property that can be control with js scripts.

However, i'm stuck with the layout below.

Since the structure with foundation 5 is:

<div class="row>
<div class="large-12 columns">
<div class="large-8 columns">
Main photo in here
</div>
<div class="large-4 columns">
Descriptions in here
</div>
</div>
<div class="large-12 columns">
Thumbnails in here
</div>
</div>

![homepage](https://cloud.githubusercontent.com/assets/1105500/5756427/0853f06c-9ce2-11e4-9758-a8d2399b7318.jpg)

I notice that your script moving main photo, descriptions to your div, then make my div empty to make your slideshow.

Is there anyway for me to keep my html format?

Best regards,

**Comment by davidghi** [comment]
Hi,

If you add a main slide image, it will be moved inside a container element. This has some purposes. This can be avoided by not adding the `sp-image` class to the image, but then it won't be resized automatically anymore. Also, you can chose to add your image as a layer.

Cheers.
