### ISSUE TITLE
update() not working correctly

### ISSUE THREAD

**Issue by nikocraft** [bqworks/slider-pro#221]
I am trying to use slider pro with my vue application.

Here is a problem I have, when running the update the plugin does not refresh it the slides and does not reinitialize correctly.

Here is some simple code:

            <div :id="'sliderpro-'+this.uniqueId" class="slider-pro">
                <div class="sp-slides">
                    <div v-if="slides.length" class="sp-slide">
                        <img class="sp-image" src="/uploads/2017/10/5/lamborghini-aventador-zaragoza-wide-1_large.jpg"/>
                        <span class="sp-layer sp-white sp-padding" style="cursor: pointer;" data-position="centerCenter">slide added</span>
                    </div>

                    <div v-else class="sp-slide">
                        <img class="sp-image" src="/uploads/2017/10/5/lamborghini-aventador-zaragoza-wide-1_large.jpg"/>
                        <span class="sp-layer sp-white sp-padding" style="cursor: pointer;" data-position="bottomCenter">initilized</span>
                    </div>
                </div>
            </div>

where is v-if I check if array of slides has any elements added to it, and then vue js renders that part. I am supposed to have a for loop inside v-if div but for now just to see that I can get update to work I have a simple slide with image and text.

What happens is slider pro is initialized correctly and v-else part is rendered by vue since user did not add any slides yet. When I manually add a slide I update the plugin like this

    $('#sliderpro-'+this.uniqueId).data('sliderPro').update()

now that vue has switched to the v-if and I've run the update, nothing much happens, change for sp-layer from data-position="bottomCenter" to "centerCenter" is ignored and also padding of the previous layer is still around and has not "grown" to accommodate larger text.

I made a video that demonstrates the problem. I'd be greatfull if I recieved some help to make the update work correctly for me. I need to allow user to change any of the settings manually throught the interface and I need the slider pro to be able to pick up any changes, either classes, options or data settings.

Is this possible? If now how much $ would it cost me to pay who ever is mantaining this great plugin to work with me to implement update function that works for my case?

Video of the issues is right here: https://youtu.be/mshEnOUMUU0

**Comment by davidghi** [comment]
This could also be a problem in your setup, as with the other issue, because updating the slides works fine in my tests. However, please note that `update` will update the slider when slides are being added or removed, it will not work for slides that have their content or configuration changed. If you want to change the configuration of a slide or layer, you should remove that slide and add it with the new configuration. However, rather than doing this, it would be better to control the style of layers directly with CSS, not by data attributes.

Cheers
