### ISSUE TITLE
Touch swipe and vertical scrolling issue on iOS

### ISSUE THREAD

**Issue by MacMah0n** [bqworks/slider-pro#226]
Hello,

There is an issue with the touch swipe on iOS.
When you swipe slider horizontally , the vertical scrolling must be disabled to avoid to move on the page.
Everything is ok on android but not on iOS. How to fix this ?

Thank you

**Comment by davidghi** [comment]
Hi,

In jquery.sliderPro.touchSwipe.js, on line 124, please replace:

```javascript
if ( Math.abs( distance ) > Math.abs( oppositeDistance ) ) {
     event.preventDefault();
} else {
     return;
}
```

with

```javascript
if ( Math.abs( distance ) < Math.abs( oppositeDistance ) ) {
     return;
}
			
event.preventDefault();
```

Cheers
