### ISSUE TITLE
Slider Stops Working When Hide/Show Using Angular2 *ngIf

### ISSUE THREAD

**Issue by Mayocampo** [bqworks/slider-pro#228]
I have SliderPro inside an Angular2 Material Dialog. On user interaction, i need slider to hide and another component to show (thats working fine, even with angular animations), but, when i do the opposite (hide component and show Slider again), slider lost all of its behaviour. Images shown one over another and no slide functionality. I've tried with destroy it on user interaction event handler and then re-reinitialize it, i've tried with update, i've tried doing nothing after user interaction.... nothing seems to work. Any ideas? Thank you so much.

**Comment by davidghi** [comment]
Hi. Can you share a link to the page?
