### ISSUE TITLE
Caching of images

### ISSUE THREAD

**Issue by katie366** [bqworks/slider-pro#229]
How do I stop the images being cached? I don't use WordPress, and am just using the jquery file with 
` $('#my-slider').sliderPro({
                width: 750,
                height: 500,
                fade: true,
                arrows: true,
                buttons: false,
                fullScreen: true,
                shuffle: false,
                smallSize: 500,
                mediumSize: 1000,
                largeSize: 3000,
                thumbnailArrows: true,
                autoplay: true,
                reachVideoAction: 'playVideo'
            });
`Which works great on the first slider, but when I then try to look at another slideshow all the images are from the previous slideshow, dispite different images being referenced in the HTML. If I could disable the cache this would solve my isssues.

Thank you.

**Comment by davidghi** [comment]
Hi. This doesn't seem like a caching issue. Can you share a link to the pages where you use the sliders?

Cheers
