### ISSUE TITLE
Thumbnail click event does not work on FF 35.0 Windows 8.1

### ISSUE THREAD

**Issue by mfran** [bqworks/slider-pro#23]
Use case: browse to a Slider-Pro example that uses thumbnails (ex's 1,3 & 5 on bqworks.com) and click on any of the thumbnails below the active slider. The goToSlider event is not fired and the slider does not advance.

Problem: thumbnailClick does not appear to fire when a thumbnail is clicked on Windows 8.1 Firefox ver 35.0. Somethign is interfering with the binding but cannot figure it out. Can confirm it works on Windows 8.1 on Chrome 42.0.2277.0 canary (64-bit), IE 11.0.9600.17498, Safari 5.1.7

great plugin btw.

**Comment by boducoscar** [comment]
The same problem with Version 40 & 41

**Comment by davidghi** [comment]
Do you use a touch-enabled screen?

**Comment by mfran** [comment]
My tests were on desktop versions. Testing on Android 5.0.1: FF ver 35 works with no issue, Chrome 39.0.2171.93 works with no issue.

**Comment by davidghi** [comment]
I'm referring to your desktop monitor. Is it touch-enabled?

**Comment by mfran** [comment]
No not touch enabled.

**Comment by boducoscar** [comment]
For my desktop, touch is enable

**Comment by davidghi** [comment]
I will get my hands on a laptop with a touch-enabled screen by the end of this week, and I will investigate the issue. I wasn't able to replicate it on non-touch screen, though. @mfran are you able to replicate the issue on other machines as well? Also, please try to disable the browser extensions; some can interfere.

**Comment by mfran** [comment]
I restarted FF in safe mode with all add-ons disabled and the issue persists. The arrows work, it's just the thumbnails that do not work below the slide. I'm in an office that is exclusively Windoze :( - but will try to find another OS. I can only confirm the issue on Win 8.1 FF 35.0 desktop atm.

**Comment by mfran** [comment]
It's working on a colleague's machine with FF 35 on Win 8.1 Pro so there must be something specific to my desktop environment that's preventing it from working. Frustrating....sry for the red herring.

**Comment by davidghi** [comment]
@mfran and @boducoscar Please try to test with the latest release.

**Comment by mfran** [comment]
Just downloaded latest release and tested against FF 35.0.1 and it now works.

**Comment by davidghi** [comment]
Great! The latest release addresses an issue with machines that have touch-enabled monitors (not mobile phones or tables, but laptops and desktop with touch-enabled screens), so your FF issue might have been related to this problem. Although it's a little strange if you say you don't have a touch-enabled monitor.
