### ISSUE TITLE
Elements within slides collapse into each other

### ISSUE THREAD

**Issue by sunilw** [bqworks/slider-pro#230]
In a minimal setup, the elements within a single slide will occupy the same area within the slide.

My test case can be seen here: https://codepen.io/anon/pen/aEOgdL?editors=1111

If you go to the last slide, you'll see that elements are jumbled.

**Comment by davidghi** [comment]
Hi. By default, the layers have `absolute` positioning. You will have to use CSS or data attributes to control their position.

Cheers
