### ISSUE TITLE
Full screen button

### ISSUE THREAD

**Issue by wagelelcee** [bqworks/slider-pro#233]
Hello Sir,

Is there a way to have a link or button users can click to go full screen?

Currently, users only see the small full-screen icon top right when they mouse over the slider. They often miss it.  I would like to encourage and notify the user that they can go full-screen by giving them a visible button to clock on.

How can I do this?

Thank you so much for your great work!

Wag

**Comment by davidghi** [comment]
Hi Wag,

You can trigger a click on the slider's full screen icon programatically when your button/link is clicked. For example:

```javascript
$( '.my-custom-button' ).on( 'click', function() {
	$( '.sp-full-screen-button' ).trigger( 'click' );
});
```

Cheers!

**Comment by Lutex** [comment]
https://github.com/bqworks/slider-pro/issues/237

https://github.com/bqworks/slider-pro/issues/187
