### ISSUE TITLE
Use with Angular ..

### ISSUE THREAD

**Issue by 4inn** [bqworks/slider-pro#236]
Hello ... I am using this module in Angular ... in a moment it works fine ... but when I go to another page and return to the main page (here is the slider) it does not appear ..

Do you have any examples of how to use it in Angular or do you recommend me to use another module?

Thank you

**Comment by davidghi** [comment]
Hi. If you still need a solution to this, can you share a page so I can see what happens? I don't have examples with Angular.

Cheers
