### ISSUE TITLE
Full Screen When Clicking On Image

### ISSUE THREAD

**Issue by aureliomora** [bqworks/slider-pro#237]
This tip works but the image does not scroll when clicking.

jQuery( '.sp-slide' ).click(function(){
    jQuery( '.sp-full-screen-button' ).trigger( 'click' );
});

**Comment by davidghi** [comment]
Hi. If you want to use something like that you need to check when there's intention for a click and when there's a swiping action. One way to do that is to check if the `sp-swiping` class exists because this class is added only during a swiping event:

```javascript
jQuery( '.sp-slide' ).click(function(){
     if( ! jQuery('.slider-pro').hasClass('sp-swiping') ) {
          jQuery( '.sp-full-screen-button' ).trigger( 'click' );
     }
});
```

Cheers!

**Comment by aureliomora** [comment]
Thank you very much, it worked as I wanted. Cheers!

Aurélio Moraes.

2018-03-14 16:41 GMT-03:00 David Ghiurau <notifications@github.com>:

**Comment by davidghi** [comment]
You're welcome!

**Comment by markgenest** [comment]
This only seems to work if you have one slider on a page. But, if you have more than one, it will only show the slides from the first slider and override the others. Is there a way to make the click to full screen mode work for multiple sliders on a page being called by `.slider-pro`?

**Comment by davidghi** [comment]
It's possible to do it for multiple sliders:

```javascript
$( '.sp-slide' ).click(function(){
     var slider = $( this ).parents( '.slider-pro' );
     if( ! slider.hasClass('sp-swiping') ) {
          slider.find( '.sp-full-screen-button' ).trigger( 'click' );
     }
});
```

Cheers!

**Comment by markgenest** [comment]
Perfect, thanks!

**Comment by davidghi** [comment]
You're welcome!

**Comment by michas0602** [comment]
Hmm, does not work for me. I am actually playing with
`        $(".sp-slide").on('click', function() {
            $(".sp-full-screen-button")[0].click();
});
`
but without success. Any ideas what I am doing wrong?

**Comment by davidghi** [comment]
You need to use the adjusted code above, for the situation when you have multiple sliders on the page. Here's a variation of it:

```javascript
jQuery('.slider-pro').each( function() {
    var $slider = jQuery( this ),
        $fullscreen = $slider.find( '.sp-full-screen-button' );

    $slider.find( '.sp-slide' ).on( 'click', function() {
        if( ! $slider.hasClass( 'sp-swiping' ) ) {
            $fullscreen.trigger( 'click' );
        }
    });
});
```

Best,
David

**Comment by michas0602** [comment]
Hi,
did a quick test and do not get it to work
(https://www.nachtlicht-fotografie.de/portfolio/fraktalkunst/).

Not even a simple
//    $('.sp-slide').on('click', function() {
//        $('.sp-full-screen-button')[0].click();
//    });

does work, and I have no idea why.
I am using a css-right-click-blocker:
         .sp-thumbnail, .sp-image {
            pointer-events: none;
} 

and in JS
    // Rechtsklickblocker 1
        $(function() {  
        $('img').bind('contextmenu', function() {  
        return false;
        });
});
and already have disabled these lines, but without success. 

Do you have some idea what I could try next to solve this maybe? Many thanks,
Micha

**Comment by davidghi** [comment]
Hi Micha,

You need to add the JavaScript code I gave you after the sliders' instantiation code:

```javascript
$( document ).ready(function( $ ) {
        $( '#my-slider1' ).sliderPro({
            ...
        });

        $( '#my-slider2' ).sliderPro({
            ...
        });

        $( '#my-slider3' ).sliderPro({
            ...
        });

        jQuery('.slider-pro').each( function() {
            var $slider = jQuery( this ),
            $fullscreen = $slider.find( '.sp-full-screen-button' );

            $slider.find( '.sp-slide' ).on( 'click', function() {
                if( ! $slider.hasClass( 'sp-swiping' ) ) {
                    $fullscreen.trigger( 'click' );
                }
            });
        });
});
```

Best,
David

**Comment by michas0602** [comment]
Works like a charm, many many thanks!!
Greets, Michael

**Comment by davidghi** [comment]
You're welcome!
