### ISSUE TITLE
continuous scroll

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#239]
David i saw you responded to someone about adding a "tweak" for continuous scroll.

has that been officially added?  I just want a carousel to scroll with no stops but do it at a slow or normal speed.  no clicks needed on images so no lightbox integration.  just scrolling logos.

would not even know where to start on this

**Comment by davidghi** [comment]
Hi. There isn't a built-in feature for this, but you can replicate the functionality with this code:

```css
.sp-slides {
     transition-timing-function: linear !important;
}
```

```javascript
setTimeout(function(){
     $( '.slider-pro' ).sliderPro( 'nextSlide' );
}, 5000);

$( '.slider-pro' ).on( 'gotoSlideComplete', function() {
    $( '.slider-pro' ).sliderPro( 'nextSlide' );
} );
```

Also, the `autoplay` option needs to be disabled.

It might now work flawlessly, a better implementation depends on your configuration.

Cheers!

**Comment by walkoffhomerun** [comment]
Top part looks css. Lower part looks js. Not sure exactly these code sections go. But, will this turn ALL slides into continuous or van this be triggered for only 1 slider and the rest stay normal?


Try the top-rated email app 
 
  On Tue, Apr 3, 2018 at 3:38 AM, David Ghiurau<notifications@github.com> wrote:   
Hi. There isn't a built-in feature for this, but you can replicate the functionality with this code:
.sp-slides {
     transition-timing-function: linear !important;
}setTimeout(function(){
     $( '.slider-pro' ).sliderPro( 'nextSlide' );
}, 5000);

$( '.slider-pro' ).on( 'gotoSlideComplete', function() {
    $( '.slider-pro' ).sliderPro( 'nextSlide' );
} );
Also, the autoplay option needs to be disabled.

It might now work flawlessly, a better implementation depends on your configuration.

Cheers!

**Comment by davidghi** [comment]
If you look at my response in GitHub, it will be clearer: you can see that there are two blocks of code.

The code targets all the sliders that have the `slider-pro` class. If you want to target a single slider, you can reference it by its ID:

```css
#logo-slider .sp-slides {
     transition-timing-function: linear !important;
}
```

```javascript
setTimeout(function(){
     $( '#logo-slider' ).sliderPro( 'nextSlide' );
}, 5000);

$( '#logo-slider' ).on( 'gotoSlideComplete', function() {
    $( '#logo-slider' ).sliderPro( 'nextSlide' );
} );
```

Typo correction: "It might ~~now~~ not work flawlessly, a better implementation depends on your configuration."

**Comment by walkoffhomerun** [comment]
david i finally had a chance to get this working.  it is a little fast.  i notice the 5000 in the set timeout function but is there a way to slow it down?

**Comment by walkoffhomerun** [comment]
i figured it out.  added "slideAnimationDuration" line into the setup js on page and it slowed it down.  700 is default and that made the slide way too fast.  changing to a much higher number slows it way down.  i chose 4000 and it gives it a much smoother and slower speed

slideAnimationDuration: 4000,
