### ISSUE TITLE
NO images display, random event, but arrow button show on hover

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#241]
I am stumped on this one.  I have slider pro working flawlessly on another website and this issue has NEVER happened.  However, I am moving over to another website template and REMOVED the built in Owl slider and replaced it with the slider pro because it can do a ton more.  However, images fail to show about 30-50% of the time but it seems it is ONLY on Opera, Vivaldi, and Chrome DESKTOP browsers.  I do NOT think this has ever happened on Firefox and I am pretty sure that it has NEVER happened on any mobile browser, even opera and chrome mobile browsers.  So this got me thinking several culprits......but before i get to this some notes. 
1) refreshing may or may not make the images reappear.  if images do NOT display the left and right arrow buttons as well as the top right expand full screen button still appear when hovered over.  
2) so that means some parts of the slider pro js file are loading as well as the slider pro css file
3) here is something real interesting......when the images do NOT show and you right click and try to get to "developer" options to see either the network waterfall or the code inspector then as soon as that developer screen appears (either on the bottom or the right side) the main screen size changes to make room for the developer options screen and the images suddenly reappear..  Any change in the main screen size makes the images appear.  So that gets me thinking it maybe something to do with responsiveness of either slider pro coding or responsive css file of the built in template 

So here are considerations:
1) the original owl carousel did not do this
2) in order to comply with google pagespeed i have made changes to try to defer the loading of css and js files.
-2a) i am using [defer] for the js files and ALL js files are at the bottom of the page
-2b) i am using [media="none" onload="if(media!='all')media='all'"] for all css files.
-2c) in do this it created a problem with the on page js config items.....this on page js config items for slider pro were loading BEFORE the deferred main slider pro js file.  so i had to move the on page slider pro config js into it's own separate js file and also defer it and have it load AFTER the main slider pro js file
-2d) the main slider pro min js file i moved into the main templates "custom.js" file where all the other main js files are located and this helps with google pagespeed by reducing the amount of js files
3) the entire slider runs fine.  so the config is working.  no problems on mobile device browsers and no problems on desktop firefox browser.  this random, intermittent, no displaying of images only happens so far on opera, vivaldi, and chrome.  even chrome and opera mobile devices work fine with no problem
-3a) so does this mean it is something in the slider pro responsive coding or the templates built in responsive css file?  does that css file need to load BEFORE or AFTER slider pro js files and css file?  As soon as the screen readjusts even 1 pixel vertically or horizontally the images magically reappear.
4) i did turn on the built in slider pro "expand to full screen option" and i tested it with that removed and the problem still happened.
5) template is a full Bootstrap 4 design
6) ***** after images fail to load i have been able to get into the developer screens when they were left open.  Under "Network" i checked for the waterfall loading sequence with the option to "disable cache" checked so it loads a full new screen and the waterfall sequence does seem to load exactly the same as when the images do load correctly
-6a) same with "Inspector"...... all div's and images are listed in the inspector coding as if they loaded.  if they did NOT show then we know the images were never created by slider pro
 **While inside "Inspector" Div class "sp-slides" IS CREATED and ALL PHOTOS loaded.  You can even see the javascript changing the images inside the inspector screen as the colors change for each slide on Div Class "sp-slide" which is assigned to each image.  So the carousel is acting like the images are there and is switching between each image but no images are output to the screen.**

Here is the working example to look at:
http://www.investorconstruction.com/v2-Webster/portfolio-single-02-2.html

**I have stripped out ALL the "defer" portions for css and js and the problem seems to have ended.  but it fails pretty much every aspect of google pagespeed.  so i need help with what part of the deferring is causing the problem.
http://www.investorconstruction.com/v2-Webster/portfolio-single-02-2a.html**

Here are screenshots.  look at the 3rd image.  photos failed to load but if you look at the top right corner of the slider you can see the arrow and expand to full screen logo actually loaded.

Image 1:  fully loaded and properly running with no issues
![1](https://user-images.githubusercontent.com/31579512/38594856-0c7cbcda-3d0e-11e8-8f8a-d596f7285f95.jpg)

Image 2:  hit refresh or even a clean page load and this is when images fail to load
![2](https://user-images.githubusercontent.com/31579512/38594866-1d5db48c-3d0e-11e8-8a0b-bea1f98bbf1e.jpg)

Image 3:  when images fail to load zoom in to top right corner and on hover the arrows and expand to full screen icons still load
![3](https://user-images.githubusercontent.com/31579512/38594892-403fa56e-3d0e-11e8-8dd5-41508d30068c.jpg)

**Comment by davidghi** [comment]
Hi. The images load and the functionality works, but the slider is collapsed because it has a height of 0 pixels; you can check this in the Inspector. This might happen because the slider and/or the slider's containers are hidden when the slider calculates its size, so it can't calculate it correctly. The solution is to resize the slider programatically, by calling $('#my-slider').sliderPro('resize'), as soon as the slider and/or the containers become visible. This method is called automatically when the browser window is resized, which is why the slider appears after you do that.

Cheers!

**Comment by walkoffhomerun** [comment]
David, since i am using "defer" for all the js files and "media none" for css files for deferred loading this is what is causing the problem.  taking those out i dont have the problem as i noted in the original post.  so, where do you recommend i add the "resize" you mention above?  on it's own at the bottom of the html page as inline scripting?  if i do i think it will run before the deferred scripts kick in.  it seems like the deferred js files might be loading before the delayed css files are loading so if it add your resize into a js file it is going to continue the same problem.  so i am not sure exactly where/when to call the resize ????

**Comment by davidghi** [comment]
Ideally you should call `resize` inside a callback function. For example, If there's a callback for when the page starts fading in, you could put the `resize` method in that callback.

**Comment by walkoffhomerun** [comment]
That did not work so i moved that last line into the main templates "custom.js" file which loads all the parameters for various js files and put it at the bottom and i noticed certain js files loaded last and came from this "custom.js" page so this would put the 'resize' as the very last onload to ever process for any page.

this DOES force all the images appear HOWEVER, it creates an issue where it makes certain images too short.  In my config file i set the height to 400 px.  The container created by slider pro is 466.67 px high and the images are set to 100%.  However, certain images that are probably the wrong aspect ratio are too short.  Slider pro is adding a negative (-) margin top of so many pixels to adjust for the height difference.  each image that is shorter in height has it's own different negative margin top.

So then i moved the entire on page slider pro config script into the very bottom of the "custom.js" file and the same problem is happening.

![4](https://user-images.githubusercontent.com/31579512/38774498-3fa8561c-4030-11e8-986c-b2966cbe1857.jpg)

**Comment by walkoffhomerun** [comment]
even after doing this i am now getting the original problem all over again which is images disappearing.  so the 'resize' must not be kicking in.  i am getting it chrome desktop and mobile browsers as well as vivaldi and opera.  but firefox renders correctly.

so back to the very start.  i must not have the 'resize' set up correctly

**Comment by davidghi** [comment]
Hi. I don't see the issue now. Do you still need help with this?
