### ISSUE TITLE
Disable touchswipe when gallery consists of single image

### ISSUE THREAD

**Issue by mediaBunker** [bqworks/slider-pro#242]
Hi,

May seem an odd request, but I'm using your plugin extensively on a clients website, where they can dynamically add as many images as they want to any given gallery.

The issue I'm seeing, is that if they have a gallery consisting of a single image, it can be dragged left and right on screen and does not snap back to the middle.

If I disable 'touchswipe', it fixes the problem but then it obviously does not work correctly on galleries with multiple images.

Here is the live website with 'touchswipe' enabled (try dragging the image left and right):
https://www.b2architects.com/our-team/pat-benjamin/

Here is my dev website with the 'touchswipe' disabled (the image won't move left and right when dragged): http://91.109.15.212/~b2dev/our-team/pat-benjamin/

Any ideas - I've looked at the documentation and cannot see any obvious fixes?

Thanks.

**Comment by davidghi** [comment]
Hi. You could block the moving of the slide with: 

```javascript
.no-swipe .sp-slides {
    transform: translate3d(0px, 0px, 0px) !important;
}
```

Of course, you also need to add the `no-swipe` or a different class if the slider will have only a slide.

Cheers!
