### ISSUE TITLE
Go to Slide on Mouseenter

### ISSUE THREAD

**Issue by oalabsi** [bqworks/slider-pro#244]
Hello,
Thank you for sharing this wonderful script.
I am trying to go to slide on mouse-enter rather than on click.
Could you please help 

Thanks

**Comment by davidghi** [comment]
Hi. You want to change the slide when the corresponding thumbnail is hovered? You can use this code:

```javascript
$( '.sp-thumbnail-container' ).on( 'mouseenter', function(){
     var thumbnail = $( this );
     thumbnail.parents( '.slider-pro' ).sliderPro( 'gotoSlide', $( this ).index() );
});
```

Cheers!
