### ISSUE TITLE
Changelog? Difference between 1.3 and 1.4 sliderpro js file

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#245]
i cannot find a changelog. I had no idea sliderpro updated from 1.3 to 1.4.  So what are the differences?  will this complicate existing usage if the main js file is updated to 1.4 from 1.3 or are there issues that have to be known about?

**Comment by davidghi** [comment]
Hi. You can see the code updates here: https://github.com/bqworks/slider-pro/commits/master The update consists of fixes and improvements, you shouldn't experience any problem if you update to 1.4.

Cheers
