### ISSUE TITLE
Lag on transitions

### ISSUE THREAD

**Issue by brunogiliberto** [bqworks/slider-pro#246]
Hello there,
I'm having a lag problem on mobile devices, the slide transition between screens is really lagging. First it loads a bigger size of sp-slider and then it takes too long to load all the small slides. I have enabled "lazy loading" but still.

http://weddings.brunogiliberto.com/scroll/

Probably it is because when the screen is smaller than 900px I destroy the slider and shows each image separately, like in a gallery? is there any way to improve the performance?

Thank you very much for your time!

**Comment by davidghi** [comment]
Hi. Are you referring to the transition animations or to the loading of the images?

**Comment by brunogiliberto** [comment]
to load the images, but also sometimes at the beginning you can see an image much bigher than the screen, sometime is just the text that you can see in a biger size.

**Comment by davidghi** [comment]
The images are all loaded at the same time, which can give a slower loading time for each individual image. Ideally, the images should be loaded only when the visitor scrolls down, but lazy loading works only in the slider's default layout.

**Comment by brunogiliberto** [comment]
thank you very much for your time @davidghi 

So there's no solution at the moment? I will try to find an external plugin to load only when the visitor scrolls down.

:)

**Comment by davidghi** [comment]
Unfortunately, there's no built-in solution at the moment because the plugin wasn't built to be used like this. Hopefully you can find an external plugin to handle this.

Cheers!

**Comment by brunogiliberto** [comment]
ok, thank you anyways.
:)

_
