### ISSUE TITLE
Lazy Loading - there are actually 2 Lazy Loads and Slider Pro Uses only 1

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#247]
slider pro successfully uses 1 of the lazy load methods and is there are a way to ADD the 2nd lazy load version?

Lazy Load technique 1: Lets call this a "right to left only" style of lazy load. This technique on carousels or sliders load images only when the image is next in the slide (to the right) BUT even the first image still loads EVEN IF the slider is lower in the page "below the fold".  This is the technique slider pro uses and i guess pretty much every carousel or slider uses.  The problem is that pages that have slider pro lower in the page "below the fold" the first image for sure still loads and if the carousel is set to layout option 2 is has to load EVERY image that is visible on that initial view (AND preview images if those layout options are used with low res preview images).  If the slider is set to Auto Play the carousel is moving and loading images even if the carousel is "below the fold" and not visible. So, even though the slider is NOT YET VISIBLE all of those images still load slowing down page load times.  This is a MAJOR hit now with Google's mobile first update hitting in June/July this year.

Lazy Load technique 2:  Lets call this a "top to bottom of page" style lazy load. This technique ONLY loads images within a "threshold" distance, usually 100 pixels away so the image or images only load as the screen is visible or within that "threshold" distance.  Something like B-Lazy image loading.  Carousel sliders not visible lower in the page or "below the fold" that are set to auto play may still move BUT if they are using inline base64 place holder images with the built in left to right lazy load as mentioned in method 1 above then none of the main images are actually loaded yet so no bandwidth hit and no extra http requests for images and for mobile devices so it greatly speeds up page load times and helps with Google's mobile first scoring when using their page speed insights test page.

So my question - is there a way to convert slider pro to the 2nd technique so that slider pro images will NOT load unless either visible on screen or within a threshold distance like 100 pixels from the visible screen size so it begins to download images ONLY if you scroll down far enough on the page?  This speeds up mobile loading times and comes into compliance with the new google standards on page scoring?

**Comment by davidghi** [comment]
Hi,

It's possible to delay the instantiation of the slider instead of instantiating it when the page loads. You can use the 'scroll' event to check if the slider comes into view while the page is scrolled:

```javascript
$( document ).on( 'scroll.sliderPro', function( event ) {
	if ( $( window ).scrollTop() > $( '#my-slider' ).position().top - $( window ).height() - 100 ) {
		$( document ).off( 'scroll.sliderPro' );
		$( '#my-slider' ).sliderPro({ width: 900, height: 500, arrows: true });
	}
} );
``` 

Cheers!

**Comment by walkoffhomerun** [comment]
in a preliminary test it works with 1 issue.  You did what i mentioned with the threshold but unlike a dedicated script such as B-Lazy if for some reason the slider pro gallery is slightly visible within the screen or i guess even the 100 pixel threshold you programmed in the entire slider does NOT show and you have to scroll down or up out of view then scroll back into view to make it work.

so your version seems perfect if the slider pro carousel is definitely out of view but if it is close to being in view it does not work as planned and requires a scrolling out of view then back into view.  is there a way to add a trigger that if it is already in view or within the threshold amount you programmed in that it loads?  other true lazy loads are able to calculate that somehow.

you are on the right track.  although not an exact lazy load it accomplishes the same thing but we need to figure out how to trigger it for carousels that may start out in view or within the threshold limit.

**Comment by walkoffhomerun** [comment]
David.....tip.....you are probably the most active carousel developer responding on github to your script and is one of the reasons i chose to use slider pro.  so many other carousels and other js have little to no support.

you have so many updates you have posted on github that you should show some of these on your main slider pro page in the form of extra examples.  the more examples you show of variations of the main 5 examples the more people will see how powerful slider pro is.  i guess the best at doing this is the fred carousel that shows something like 78 completely different examples but it helps show so many different uses for it.

i think that might be helpful to grow slider pro.....if that is something you want to do.

**Comment by davidghi** [comment]
Hi. Thank you for the suggestion! I will consider that.

Regarding the custom JS, it can be adjusted to check if the slider is in view when the page loads:

```javascript
function checkSlider() {
	if ( $( window ).scrollTop() > $( '#my-slider' ).position().top - $( window ).height() - 100 ) {
		$( document ).off( 'scroll.sliderPro' );
		$( '#my-slider' ).sliderPro({ width: 900, height: 500 });
	}
}

$( document ).on( 'scroll.sliderPro', checkSlider );
checkSlider();
```

Cheers!
