### ISSUE TITLE
Flickering on mobile

### ISSUE THREAD

**Issue by michas0602** [bqworks/slider-pro#249]
Hello, on my mobile the slider is heavily flickering.

I already found a solution:

`.sp-slide {
        -webkit-backface-visibility: hidden; /* Chrome, Safari, Opera */
        -webkit-transform: translate3d(0, 0, 0); 
        backface-visibility: hidden;        
}`

I am not sure if flickering is a problem of the Slider or if its a problem of my mobile/browser/webkit - but maybe this is useful for someone else as it took a while for me to find this solution.

**Comment by davidghi** [comment]
Thank you for your contribution!
