### ISSUE TITLE
Fade effect doesn't work

### ISSUE THREAD

**Issue by cimt** [bqworks/slider-pro#25]
Fade effect doesn't work (partially) in FF 35.0 - Win 7 and 8. 
Chrome and IE works!

**Comment by davidghi** [comment]
I just checked on two machines in FF 35 and the fade worked fine. What do you mean by 'partially'.

**Comment by cimt** [comment]
Hi David,
Here's an example:
***
            width: 1920,
            height: 800,
            fade: true,
            loop: false,
            arrows: true,
            buttons: true,
            autoplayDelay:5000,
            fadeDuration: 1200,
            fadeOutPreviousSlide: false,
            waitForLayers: true,
            autoplay: true
***

sorry, my english is not good!!
and thanks for the great slider!


2015-01-22 15:48 GMT+01:00 David Ghiurau <notifications@github.com>:

> I just checked on two machines in FF 35 and the fade worked fine. What do
> you mean by 'partially'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bqworks/slider-pro/issues/25#issuecomment-71030679>.
>



-- 
greets

mario

**Comment by davidghi** [comment]
Maybe that happens because the image is not loaded yet, in case you're using lazy loading. Please post a link to your page.

**Comment by cimt** [comment]
I have no example online -sorry, but here's the answer (the same bug - in ff) 
https://github.com/srobbin/jquery-backstretch/issues/399

**Comment by davidghi** [comment]
If it's a Firefox bug, as it was reported in the issue you linked to, then we'll have to wait for a fix from Mozilla. However, it doesn't occur when I test my examples.
