### ISSUE TITLE
Won't display when container is set to height:100%

### ISSUE THREAD

**Issue by cursor2000** [bqworks/slider-pro#250]
The slider still isn't appearing when its height is set to **any** percentage. It works when using <code>vh</code> or <code>px</code> but not when using a percentage. I can set its container to a percentage height or a pixel height but the slider does not appear and has a height of 0.

**Comment by davidghi** [comment]
Hi. This happens when the slider's parent elements doesn't have a defined height; if you set a height to it, the percentage height will work for the slider.

Cheers!

**Comment by cursor2000** [comment]
Here's my basic code (which doesn't work). When Slider-Pro is given a `%` height, it doesn't display. A `px `or `vh `height works.

```
<html>
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> 
	<script src="js/jquery.sliderPro.js"></script>
	<link rel="stylesheet" href="css/slider-pro.min.css"/>
	<script type="text/javascript">
		$( document ).ready(function( $ ) {
			$( '#my-slider' ).sliderPro({
				width: '100%',
				height: '100%',
				arrows: true,
				slideAnimationDuration: 500
			});
		});
	</script>
</head>

<body style="height:100%;width:100%;margin:0;padding:0;overflow:hidden;">
	<div class="slider-pro" id="my-slider">
		<div class="sp-slides">
			<div class="sp-slide">
				<img class="sp-image" src="images/01.jpg">
			</div>

			<div class="sp-slide">
				<img class="sp-image" src="images/02.jpg">
			</div>

			<div class="sp-slide">
				<img class="sp-image" src="images/03.jpg">
			</div>
		</div>
	</div>
</body>
</html>
```

**Comment by davidghi** [comment]
Setting the slider's height to a percentage will require using some additional CSS for setting the height of some inner slider elements, because of the same reason I mentioned above: using percentages requires that the parent elements also have a defined height, and this applies for all the elements, not only the slider's immediate parent element:

```css
.slider-pro, .sp-slides-container, .sp-slides {
    height: 100%;
}
```

This is why using `vh` is a better solution. Also, if you want to set both the `width` and `height` to 100%, you can instead set `forceSize` to `fullWindow`. Why do you need to use percentages?

Cheers!

**Comment by davidghi** [comment]
By the way, the example you posted still won't work because the `body` has a percentage height but the `html` doesn't have any height, so you will either need to set the `body` to a fixed or vh height, or set a height for `html` as well.

**Comment by cursor2000** [comment]
Thanks David. The `body `and `html` are now set at `100vh `and I have the desired effect. I have an issue with the slides not covering the whole width of the slider though. I've tried all the `imageScaleMode `options. The slide rescales to the height of the slider but not the width so I'm getting gaps on the left and right. Shall I raise a new issue?

**Comment by davidghi** [comment]
You're welcome. Setting `imageScaleMode` to `cover` should work, unless you use other options like `autoSlideSize: true` that would change the behaviour.

**Comment by cursor2000** [comment]
The only way I can get a slide to fit the entire width of the slider is to use `imageScaleMode: 'exact'` but this disproportionately scales the image in both directions. [Here's the site in question.](https://www.wyesite.co.uk/bruce)

**Comment by davidghi** [comment]
You could try to set `forceSize: 'fullWindow'`.
