### ISSUE TITLE
Hidden slides z-index

### ISSUE THREAD

**Issue by capegreg** [bqworks/slider-pro#253]
The hidden slides withing translate3d div cover controls left and right of the slide container making them inaccessible.  For example, I have a scrollbar that cannot be scrolled because the hidden slide is messing it up.

<div class="sp-slides" style="transform: translate3d(-570px, -550px, -550px);">

**Comment by davidghi** [comment]
Hi. Can you show me that in a live example?

**Comment by capegreg** [comment]
Hi davidghi,
I must have had the slider margin, width, etc. too wide for its container. I cleaned up my css and things are working now. Thanks.

![example](https://user-images.githubusercontent.com/1051118/42593156-b2bcc272-8519-11e8-8dde-23ac8e57c2ad.png)
