### ISSUE TITLE
Calls to Vimeo dependency fail over https

### ISSUE THREAD

**Issue by chronon** [bqworks/slider-pro#254]
The hardcoded, non-protocol specified url `//a.vimeocdn.com/js/froogaloop2.min.js` fails to load when called from a https sourced parent script due to a certificate error. Apparently [Froogaloop has been retired](https://github.com/vimeo/player.js#migrate-from-froogaloop). Would including the contents of `froogaloop2.min.js` as an internal slider-pro dependency be an option?

**Comment by davidghi** [comment]
Hi. You could put the contents of the script in a local file. The slider will check if the Froogaloop API is loaded and should work even if it's loaded from a different location. To eliminate the certificate error, you need to remove lines 660-663 from jquery.sliderPro.video.js:

```javascript
var tag = document.createElement('script');
tag.src = "//a.vimeocdn.com/js/froogaloop2.min.js";
var firstScriptTag = document.getElementsByTagName( 'script' )[0];
firstScriptTag.parentNode.insertBefore( tag, firstScriptTag );
```

**Comment by chronon** [comment]
Thanks, that works perfectly.
