### ISSUE TITLE
Chrome Warning On Mobile Touch

### ISSUE THREAD

**Issue by ryigit** [bqworks/slider-pro#255]
Warning Says:

`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

It can be seen on newer Chrome versions.

I think it's about CSS touch-action property. But I don't know what this property do.

**Comment by davidghi** [comment]
Hi! Thank you for letting me know! This is due to some changes in Chrome. The problem that it can cause in the slider is to allow page scrolling (up and down) while you swipe the slides. I will address the issue in the next update.

Cheers!
