### ISSUE TITLE
Sliderpro jquery width Issue

### ISSUE THREAD

**Issue by telic910** [bqworks/slider-pro#256]
Hi 

Am using sliderpro. onload slider taking default width:100px.
 But am giving 100%. 
Once opened the F12 or inspect Element slider working fine.

Thanks

**Comment by davidghi** [comment]
Hi. Maybe the slider is not visible or is inside a container that it's not visible when the slider is instantiated, so it can't calculate its size. The solution is to call the `resize` method after the slider is visible: `jQuery( '#my-slider' ).sliderPro( 'resize' )`. 

Cheers!
