### ISSUE TITLE
Destroy not working on resize

### ISSUE THREAD

**Issue by pixlogix** [bqworks/slider-pro#257]
while I am resized window destroy method is not working, can you please give an example of destroy method used

**Comment by davidghi** [comment]
Hi. Are you trying to use destroy while you resize the page? Can you show me the page?

Cheers!

**Comment by pixlogix** [comment]
Yes I need to destroy slider on greater 640px window size and Re init while window resize less then 640px screen 

let me share Code pen example for it.

https://codepen.io/pixlogix/pen/bjXXmE

**Comment by davidghi** [comment]
By the way, you should put some logs inside the IF...ELSE statements and see if the code inside is executed.
