### ISSUE TITLE
Clearing slides and thumbs using JQuery empty()

### ISSUE THREAD

**Issue by capegreg** [bqworks/slider-pro#258]
I am loading slides and thumbs when user clicks nav link. I need to clear both without refreshing the browser. Currently, empty() is working, but want to know if there is an api method available.

$("#myslider .sp-slides").empty();
$("#myslider .sp-thumbnails").empty();

**Comment by davidghi** [comment]
Hi. You can to that if you then add other slides in their place.

Cheers!
