### ISSUE TITLE
No fade out for caption

### ISSUE THREAD

**Issue by boducoscar** [bqworks/slider-pro#26]
Hi there,

Is there any config that disable caption fade effect when click next slide?

And when you swipe slider, there are a small space between 2 slide, how can i remove that space?

Many thanks,

**Comment by davidghi** [comment]
Hi,

For captions it's not possible to disable the fade because the current caption needs to be hidden in order to allow the new caption to appear. You could use static layers instead.

To remove the space, you need to set slideDistance to 0.
