### ISSUE TITLE
padding around slider

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#260]
how can i add padding around a slider?  I tried to add padding to the
`<div id="example2" class="slider-pro">`
and separately
`<div class="sp-slides">`
by adding bootstrap padding callouts since i am using bootstrap but the carousel disappeared and when opening element inspector in a browser i see slider pro adds some of it's own padding and margin stuff.

so i know it's possible but maybe in the CSS file?  part of the the javascript config file?  but i cannot find any padding in the api

**Comment by davidghi** [comment]
You can try this:

```css
.slider-pro {
    padding: 30px;
}
```

**Comment by walkoffhomerun** [comment]
i did.  slider disappears or nothing happens.  i mentioned that in the message above as something i previously tried.  what happens is that it successfully adds padding to the top, bottom, left side but the right side overhangs the container

**Comment by davidghi** [comment]
It works for me, so it might be a problem specific to your implementation. I can take a look if you post a link. Also, if you want the padding to be included in the size you've set for the slider, you need to add:

```css
.slider-pro {
    box-sizing: border-box;
}
```
