### ISSUE TITLE
Load Slider on Next/Prev Click

### ISSUE THREAD

**Issue by VivekanandSaraswati** [bqworks/slider-pro#266]
Hi Team,

I want to know that how to achieve below task:

I want to add slide on next/prev click, I am working on unlimited slide(8000), so I can't load all slide at a time. I want to load more slide on click via ajax. Is it possible with this slider?

Thank You,
Vivekanand Saraswati

**Comment by davidghi** [comment]
Hi, Vivekanand. It's possible, but I'm not sure how it would behave with that amount of slides. What you have to do is edit the HTML of the slider to add/remove the slides and then call the slider's `update` method.

Cheers

**Comment by walkoffhomerun** [comment]
wont lazy loading of images do the same thing?  just set the initial slide to a base64 clear 1x1 clear pixel like i do and then it only loads the images 1 image ahead when you click the right arrow button.  now 8,000 would probably crash just about any slider carousel.  i think with previous issues listed here having thumbnail images enabled with a bunch of images can make slider pro very sluggish so i would avoid thumbnails with that many images.

**Comment by gautamz07** [comment]
@walkoffhomerun how about using the ```update``` method.
