### ISSUE TITLE
Touch swipe on Safari iOS scrolls the page

### ISSUE THREAD

**Issue by andreyuv** [bqworks/slider-pro#267]
Hi,

This concerns Safari on iOS 12.
With touch swipe active, when I swipe the slides (horizontally) the whole page also scrolls (vertically).

Looking through the Slider Pro code, I can see there is a section that aims to stop this behavior from happening, but it doesn't seem to be working.

Is this a Safari bug, or a problem with Slider Pro?

**Comment by davidghi** [comment]
Hi. It appears to be an iOS bug: https://bugs.webkit.org/show_bug.cgi?id=184250, https://bugs.webkit.org/show_bug.cgi?id=185656

If you're using the latest release, only the first swipe will allow vertical scrolling; the following swipes should block it. However, vertical scrolling will be blocked only if the swipe is from the start horizontally. If you start with a vertical swipe and then swipe horizontally over the slider, both the slider and the page will be scrollable.
