### ISSUE TITLE
Conditional Images Art direction?

### ISSUE THREAD

**Issue by Allmedialab** [bqworks/slider-pro#269]
Hi,
Looked at the Conditional Images.
Would it be possible to specify art direction like you can in Farkas Lazy Sizes. For example to point out  that a specific image only has to be shown on a mobile phone in portrait mode? Like in this example:

`<source` media="(max-width: 475px) and (orientation: portrait)"
type="image/webp"
data-sizes="auto"
srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" 
data-srcset="
Slider-images/for-webp/600-500.webp 600w,
Slider-images/for-webp/800-500.webp 800w" class="lazyload">
<source media="(max-width: 475px) and (orientation: portrait)"
data-sizes="auto"
srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
data-srcset="
Slider-images/for-jpeg/600-500.jpg 600w,
Slider-images/for-jpeg/800-500.jpg 800w" class="lazyload"> `     

Regards & Thanks,
David

**Comment by davidghi** [comment]
Hi, David. The `conditional images` module uses only the slider's size; it's not possible to use the orientation of the device as a condition.

Cheers!
