### ISSUE TITLE
Change layer position with size (small-medium-large)

### ISSUE THREAD

**Issue by dantahoua** [bqworks/slider-pro#27]
Hello.
I would like to know how can I change the layer information when changing the size (responsive) of the viewport.
Exemple:
For large viewport I have:
<div class="sp-layer sp-black" data-position="bottomRight" data-horizontal="35%" data-vertical="148"
								     data-show-transition="left" data-show-delay="300" data-hide-transition="right">...
And I want for medium and small:
<div class="sp-layer sp-black" data-position="bottomRight" data-horizontal="0%" data-vertical="100"
								     data-show-transition="left" data-show-delay="300" data-hide-transition="right">...

Thanks

**Comment by davidghi** [comment]
Hi. There isn't a built-in method for this, but you could use JavaScript to detect the window size and then change the layer data attributes.

**Comment by dantahoua** [comment]
Ok, I did this for now, not the best, but it's working. Is there any function to force restarting the slider because the mod wont be applied to the current displayed slide?
$( window ).resize(function() {
			if ($(window).width() < 926) {
				$(".sp-layer").attr("data-position","bottomRight")
			}
		});

**Comment by davidghi** [comment]
It's quite an edge case to have to modify layer data based on screen size. If the position of the layer is what you want to change, then it's better to use CSS media queries instead of modifying the layer data. Anyway, to restart the slider you can 'destroy' it and then re-instantiate it.
