### ISSUE TITLE
Use multiple image sizes in thumbnails?

### ISSUE THREAD

**Issue by Allmedialab** [bqworks/slider-pro#272]
Hi,
Is it possible to use multiple images sizes for the thumbnails as well for example for high resolution screens like the normal images can?
Regards & Thanks,
David

**Comment by davidghi** [comment]
Hi, David. It's possible to use a "retina" version for the thumbnails with the `data-retina` attribute.

Cheers!

**Comment by Allmedialab** [comment]
Thanks! David
