### ISSUE TITLE
Add higher resolution for 3k, 4k and 5k screens

### ISSUE THREAD

**Issue by Allmedialab** [bqworks/slider-pro#273]
Hi,
At the moment we have:
smallSize: 500,
mediumSize: 1000,
largeSize: 3000,

Or what ever we add, but what if I need:
*Example:
smallSize: 500,
mediumSize: 1000,
largeSize: 2000,
3kScreen: 3200,
4kSceen: 4200,
5kScreen:5200,

I've been reading the documentation about the "retina module", but are not sure about the sizes I can use. Is it only doubling the size or can I use data-retina="path/to/image3@3x.jpg (x3)? Then I also see in the conditional images module:
data-retinasmall="path/to/image_retina_small.jpg"
data-retinamedium="path/to/image_retina_medium.jpg"
data-retinalarge="path/to/image_retina_large.jpg"/>

Could you please explain given the above *Example how to use the data-retina?

 Regards & Thanks,
David

**Comment by davidghi** [comment]
Hi David,

The `retina` version of the image will be used for all the high PPI screens but it will not differentiate between 3k, 4k or 5k. The 'smallSize', 'mediumSize' and 'largeSize' options refer to the size of the slider, and the images indicated for these will be used when the slider has those sizes.

Cheers!

**Comment by Allmedialab** [comment]
Hi David, Thanks for your reply! Would it be very difficult to add some more retina sizes to the script?
Regards,
David
