### ISSUE TITLE
Can't drag slider backwards

### ISSUE THREAD

**Issue by RyouMisaki** [bqworks/slider-pro#276]
Hi!
I noticed I can't drag sliders backwards on desktop, didn't try on mobile, but on Desktop when dragging to a previous slider, the slide just gets stuck and there's whitespace where there should be the other slide.
Dragging to the next slide makes it normal again, clicking on the arrows also does, but you can't go to the previous slider by dragging...
I tested in Firefox and chrome.

**Comment by davidghi** [comment]
Hi.
If there are only two slides in the slider, please see this: https://github.com/bqworks/slider-pro/issues/5

Cheers!
