### ISSUE TITLE
Loop set to false, but both arrows visible at start and end of slideshow when using gotoSlide

### ISSUE THREAD

**Issue by candlefish** [bqworks/slider-pro#279]
I have a slider with loop set to false. When I reach either end of the slideshow by using the arrows, the arrow which would loop is removed as you'd expect. However, I have optional text links which use the gotoSlide method, and if I reach the beginning or end of the slideshow using those, both arrows remain visible behave as if loop is set to true. Also, if I use gotoSlide to navigate to a slide in the middle of the slideshow, both arrows appear but the right arrow is disabled.

**Comment by davidghi** [comment]
Hi. I can't replicate the problem. Can you post a link to the page?
