### ISSUE TITLE
Amount of thumbails

### ISSUE THREAD

**Issue by soniktrooth** [bqworks/slider-pro#28]
Is it possible with config to change the amount of thumbnails that show?

**Comment by davidghi** [comment]
No, the thumbnail area will be as wide as the slider. Maybe if you use some custom CSS...

**Comment by soniktrooth** [comment]
yeah, that's what I've done. However it's not great because I have to hard code px widths. What I really want to do is be able to set a percentage width so I can know that X number of thumbnails will always be showing despite the size of the browser e.g. 33.33% for 3 thumbs, 25% for 4 thumbs, 20% for 5 thumbs etc.

**Comment by davidghi** [comment]
You can set the thumbnailWidth to a percentage value like '20%' (in this case it needs to be a string), but you'll also need some additional CSS to set the width of the thumbnails' container:

```
.sp-thumbnails {
    width: 100% !important;
}
```

**Comment by wpexplorer** [comment]
Any chance you could add a property to simply disable the scroller on the thumbnails? So when disabled the only thing that would run would be _gotoThumbnail

Thanks!

**Comment by davidghi** [comment]
Are you referring to disabling the dragging on the thumbnails? If so, that's possible by setting `thumbnailTouchSwipe ` to false.

**Comment by wpexplorer** [comment]
@davidghi - I mean disabling the carousel completely from the thumbnails. So it's just a thumbnail grid essentially.

**Comment by davidghi** [comment]
I see. That's possible with some custom CSS: `sp-thumbnails { width: 100% !important; }`

**Comment by wpexplorer** [comment]
@davidghi - of course, yes that's nice ;) But isn't the javascript running useless code?

**Comment by davidghi** [comment]
Yes, the javascript code will still try to arrange the thumbnails linearly but a JavaScript option is not available at this moment. I'll put it on the feature requests list.

**Comment by wpexplorer** [comment]
@davidghi - Awesome, thanks!

ps: Do you want people submitting commits or is that something that would bother you?

**Comment by davidghi** [comment]
I thought about it and I don't mind bug fixes or code improvements but when it comes to adding new features I would prefer the contributor to share his thoiught with me because I might not want to add a certain feature; I want to avoid feature bloat. However, sometimes it's possible to just create a new module for that feature.

**Comment by wpexplorer** [comment]
@davidghi - I agree 100% (I am the same way). So I won't bug you with any pull requests ;)

**Comment by davidghi** [comment]
Feature suggestions are welcomed, though :)

I'll close this thread for now because there haven't been updates for the initial topic.
