### ISSUE TITLE
Display only the first time

### ISSUE THREAD

**Issue by radiopenchi1976** [bqworks/slider-pro#281]
The first image is displayed, the slide from the second image is displayed, and when you go to the last slide,
I want to return to the second piece instead of the first piece and loop it repeatedly.
What should I do?

1st time slide 0, slide 1, slide 2, slide 3, slide 4
After this time slide 1, slide 2, slde 3, slide 4 (this loop)

**Comment by davidghi** [comment]
Hi. You could use the slider's API to remove the first slide at some point, so that only slides 1-4 remain in the slider. To remove a slide, first you need to remove the HTML of that slide and then call the `update` method. Let me know if you need further help.
