### ISSUE TITLE
Show tabs and text out side of slide before fully loaded

### ISSUE THREAD

**Issue by AndreasRogall** [bqworks/slider-pro#283]
I love the slider-pro! 
Incredible and fantastic piece of software! 

However, before the first slide is loaded the tabs and some text from the first slide is shown outside the slide! 

Can't figure out what is the cause for this. It's only for a split second that the content of the tabs and the text inside the slide will be displayed on the left side of the slide. Even the Company Logo on the Top Left corner isn't visible - only the alt text. 

I added 9 screenshots.  01 shows the messed up display and 02 the fully loaded slide.
All the other slides 03-09 showing the whole progress by frame (left bottom corner) advancement - captured by video. Note that slide 7 the content display is short by the size of one tab! 

http://www.fotowatch.com/index.htm
Looking at the source code - please use the 'slider-pro.css' instead of the minimized coded version which makes it easier to dig in deeper. 

Best regards,
Andreas
Webmaster

ATTACHMENTS
![01 - Outside Tabs and text](https://user-images.githubusercontent.com/43253622/54507501-1876ea80-4918-11e9-995b-3a8ebd8347be.jpg)
![02 - Complete Tabs and text](https://user-images.githubusercontent.com/43253622/54507507-1ad94480-4918-11e9-942d-2e8fbbdc517d.jpg)
![03 - Reload 1  Frame Tab and text](https://user-images.githubusercontent.com/43253622/54507510-1d3b9e80-4918-11e9-8bc7-fb12a0a2d7fc.jpg)
![04 - Reload Frame Text in Header - Tab and text](https://user-images.githubusercontent.com/43253622/54507513-1f9df880-4918-11e9-8f7a-f6de5a55e01c.jpg)
![05 - Reload Next Frame Tab and text](https://user-images.githubusercontent.com/43253622/54507517-2167bc00-4918-11e9-94e4-462e4faa341e.jpg)
![06 - Reload Frame Full Logo in Header - Tab and text](https://user-images.githubusercontent.com/43253622/54507520-23317f80-4918-11e9-9f49-82e84da51146.jpg)
![07 - Reload Frame Full Logo in Header - 1  Frame of text](https://user-images.githubusercontent.com/43253622/54507524-2462ac80-4918-11e9-82d0-826efde37a10.jpg)
![08 - Reload Frame Full Logo in Header - Nex Frame  full size of text](https://user-images.githubusercontent.com/43253622/54507526-26c50680-4918-11e9-8828-3379f4d6dd90.jpg)
![09 - Reload Frame Full Logo in Header - Nex Frame  full size of Blue text  last jump to left](https://user-images.githubusercontent.com/43253622/54507529-288eca00-4918-11e9-903b-322bc438aeb8.jpg)

**Comment by davidghi** [comment]
Hi Andreas,

The slider will appear unstyled before its JavaScript is executed, but you can improve its aspect with CSS, by hiding some of the elements, like the layers, or styling them:

```css
.sp-no-js .sp-layer {
    opacity: 0;
}
```

To use the `sp-no-js` class, you need to add it next to `slider-pro` and the slider will automatically remove it when the slider is instantiated, so any styling you add by using `sp-no-js` will be applied only before the slider's instantiation.

Please let me know if you need further help.

Best,
David

**Comment by AndreasRogall** [comment]
Hi David,
I could get rid of the Blue text - Thanks :)  it's already much better.

However, The Thumbnails are still first loaded on the left side as shown in the 1. screenshot attachment.
How could this be handled?

I tried to add the class to <div class="sp-thumbnails sp-layer">  but this didn't have any effect - as the 'slider-pro div' has these included already anyway.

Any solution? 

Best regards,
Andreas

**Comment by davidghi** [comment]
You could try to hide the thumbnails with this CSS:

```css
.sp-no-js .sp-thumbnails {
    opacity: 0;
}
```

They will become visible after the slider is instantiated and the `sp-no-js` class is removed.

Best,
David

**Comment by AndreasRogall** [comment]
Hi David,
You're the best - Now it displays perfectly. 

I only had to adjust the image (size) for the tag
<img class="sp-image" ... data-medium="images/sp_canvas_medium.jpg"
from 1000 pixel width to 1220 
and the mediumSize from 1000 to 1220 too,

as the slider initiates:       
width: 1220,
height: 500,
mediumSize: 1220,

That took care of the display issue shown in attachment 7.
Everything is now perfect!!

Best regards,
Andreas

**Comment by AndreasRogall** [comment]
Hi David,
FYI Update: In using the 

> .sp-no-js .sp-thumbnails {
    opacity: 0;
}

causing problems when scaling down. 

A) The total thumbnails (6) are no longer showing - only 2-3 depending on the View Point 
(aka  320 wide / 500 / 800 / < as the setting of the total canvas width 1220 pixel).

B) In addition, the sliding of the thumbnails wouldn't work either!

The displaying of the thumbnails while initiating (loading page) vertically was caused by using a layer background image smaller than 1220 pixel ( I had 1000 pixel wide images). Just changing the images to the right size ensured that the thumbnails are displayed horizontally (instead of vertically inside the canvas).

Best regards,
Andreas

**Comment by davidghi** [comment]
Hi Andreas,

A) The thumbnails are not scaled down proportionally with the slider, their size remains the same even if the slider's size decreases, so less thumbnails will be visible. You can decrease their size only by using breakpoints and changing the `thumbnailWidth` and `thumbnailHeight` in the breakpoint.

B) It seems to work for me when I test your slider and I see that you're using `.sp-no-js .sp-thumbnails {opacity: 0}`, unless you're referring to a different slider than the one from fotowatch.com

Best,
David

**Comment by AndreasRogall** [comment]
Hi David,

I do have breakpoints set 
`  breakpoints: {
        500: {
          thumbnailWidth: 120,
          thumbnailHeight: 50
 `
When I added  the sp-no-js to the div
`<div class="sp-thumbnails sp-no-js">`

and then reducing (resizing) the browser's size by hand or using the Web Developer - Responsive Design Mode with latest FF than the behavior of the Thumbnails changed - only 3 of 6 were displayed - even though there was enough place for one more - and I could not see any other nor slide the thumbnails to the other 3 no longer displayed. The other 3 were never displayed only the first 3 one - even while cycling through the 6 slides!

Only after removing the 'sp-no-js' from the thumbnails div everything went back to normal.
I still have the code in the CSS as you pointed it out - but it's no longer been used by the slider.

When you tested my slider the code 'sp-no-js' from the 'Thumbnails div' was already removed.

I hope this explains it a little bit better :)
However, everything is now in perfect working order.

Thanks a mill.
Fantastic product and customer service.
5 STAR rating.

Sincerely,
Andreas

**Comment by davidghi** [comment]
You're welcome, Andreas! I think I understand now... You added the `sp-no-js` class to the thumbnails' DIV element, but that is not necessary; you only need that class for the main slider DIV, where it currently is.

Best,
David
