### ISSUE TITLE
How to do to show the sliderpro after having loaded all the images?

### ISSUE THREAD

**Issue by kael9320** [bqworks/slider-pro#284]
Hi everyone!!

When loading the slider, it is seen badly.
How can I make the slider show once all the images have been loaded?

![sliderpro](https://user-images.githubusercontent.com/16750243/54842304-997b0c80-4c9f-11e9-9b12-292d47383d88.png)

Thanks

**Comment by davidghi** [comment]
Hi. Did you find a solution or still need help with this?
