### ISSUE TITLE
Image width does not adjust

### ISSUE THREAD

**Issue by hejke** [bqworks/slider-pro#286]
Hi, 

I try to use the slider-pro (Example 3), but I have problems with responsibility and height.

The image width does not automatically adjust to the height, so especially on smaller screens the image is not fully displayed, which is very inconvienient and ugly. Example: https://new.polarlichtexpress.de/test-slider.html... I also played with the settings, of course, but no improvements. Strangely, I use exactly settings on another page and there it works?! I do not understand what's wrong...

Here are the settings I used:
//Slide Show und Fancy Box
		$('#slider_single' ).sliderPro({
			height: 300,
			width: 300,
            buttons: false, /*navigation control wird entfernt*/
            slideDistance: 5, /*Abstand zwischen den Slides, Standard ist 10*/
			visibleSize: '100%',
			autoSlideSize: true,
			responsive: true,
			breakpoints: {
				767: {
					height: 200
				}
            }
		}); 

		
		// instantiate fancybox when a link is clicked
        $( ".slider-pro" ).each(function(){
			var slider = $( this );

			slider.find( ".sp-image" ).parent( "a" ).on( "click", function( event ) {
				event.preventDefault();
			
				if ( slider.hasClass( "sp-swiping" ) === false ) {
					var sliderInstance = slider.data( "sliderPro" ),
						isAutoplay = sliderInstance.settings.autoplay;

					$.fancybox.open( slider.find( ".sp-image" ).parent( "a" ), {
						index: $( this ).parents( ".sp-slide" ).index(),
						afterShow: function() {
							if ( isAutoplay === true ) {
								sliderInstance.settings.autoplay = false;
								sliderInstance.stopAutoplay();
							}
						},
						afterClose: function() {
							if ( isAutoplay === true ) {
								sliderInstance.settings.autoplay = true;
								sliderInstance.startAutoplay();
							}
						}
							
					});
				}
			});
		});

Help is appreciated, I have been struggling with this for quite a while... :)

**Comment by davidghi** [comment]
Hi,

You've set the CSS `position` for `.slider-pro a` to `absolute`. Please change it to `static` and it should fix this issue.

Let me know if you have further questions.

Best,
David

**Comment by hejke** [comment]
Thank you for your very quick hep, David. I appreciate that. You really found the problem, now it seems to work properly!

**Comment by davidghi** [comment]
You're welcome! I'm glad I could help.
