### ISSUE TITLE
Loop: false and thumbnailWidth doesn't work

### ISSUE THREAD

**Issue by soniktrooth** [bqworks/slider-pro#29]
Here's my set up:

```
  $('#media-player .slider-pro').sliderPro({
    buttons: false,
    autoplay: false,
    loop: false,
    thumbailWidth: '250',
    thumbnailHeight: '120'
  });
```

Despite this, the slideshow loops and the thumbnail width is unaffected. I'm able to force the thumbnail width with some heavy handed css, but the setting in the js doesn't seem to affect it.

Thumbnail containers end up looking like this: 

```
<div class="sp-thumbnail-container" style="width: 100px; height: 120px;" data-loaded="true">
<div class="sp-thumbnail" data-index="4" data-init="true" style="width: auto; height: 100%; margin-left: 0px; margin-top: 0px;">
        <p class="sp-thumbnail-text">Bay Area Bike Share</p>
        <img width="150" src="/images/media-gallery/aep_228b.jpg">
      </div>
</div>
```

As you can see the inline styling is setting the width to 100px, despite me setting it to 250. Also, interesting is that the thumbnailHeight seems to work fine.

**Comment by davidghi** [comment]
What do you mean by loop? That option enables the slider to scroll in an infinite loop as opposed to having a left or right edge.

Regarding the thumbnailWidth, try to remove the quotes from the numbers because those values need to be numbers, not strings.

Cheers.

**Comment by soniktrooth** [comment]
I will try with integers, thanks for the tip. 

Re: loop
Despite setting 'loop: false' my slideshow is scrolling in an infinite loop. I have 4 slides in my slideshow but as per #28 I have room for more than 4 thumbnails in the thumbnail section and it shows me 6 thumbs—the last two of which are duplicates of the first two. When navigating left/right, the slide show loops infinitely. My understanding was that setting 'loop: false' would limit the slide show to just the 4 slides and trying to navigate paste the first or last would be impossible.

**Comment by davidghi** [comment]
Setting `loop` to false determines the behavior you see in Example 5 where you can't scroll to the 'previous' slide if you're already on the first slide and you can't scroll to the 'next' slide if you're already on the last slide in the slider.
