### ISSUE TITLE
centerImage not working in 1.5.0?

### ISSUE THREAD

**Issue by ballmannweber** [bqworks/slider-pro#290]
we worked a lot with sliderpro in the last three years – 1.4.0 on most projects. on a new website with version 1.5.0 we noticed that with the very same slideshow code we usually use the images will no longer be centered, regardless if we use the property centerImage:true or not.

when we revert the js back to 1.4.0 everything centers as expected.

we also rebuild the html-code and left out all custom-css because we thought there were some changes to that but that didn’t make the difference. 

is that a bug?

**Comment by ballmannweber** [comment]
anybody listening?

**Comment by davidghi** [comment]
Hi. Are the images not centred inside the slide (individual slide) or is the selected slide not centred inside a carousel slider? In the first situation it could happen if the `autoHeight` option is enabled and in the second situation it could happen if `visibleSize` is not used to set the size/width of the entire carousel slider and `forceSize:fullWidth` is used instead.

Best,
David
