### ISSUE TITLE
Autoplay video not working.

### ISSUE THREAD

**Issue by brosoftsystem** [bqworks/slider-pro#291]
I am using **v1.5.0** libraries with YouTube slide.

But, on page load video not autoplay into slides.

```
//Video
reachVideoAction : 'playVideo',
leaveVideoAction : 'pauseVideo',
playVideoAction : 'none',
pauseVideoAction : 'startAutoplay',
endVideoAction : 'none',

```
There is no js error in console. Video start loading but not autoplay.
Any help appreciated.

Thanks

**Comment by davidghi** [comment]
Hi. In some browsers the videos will not autoplay, without user action, unless they are muted. This is a browser policy.

Best,
David
