### ISSUE TITLE
Layer Effects Not Working Right

### ISSUE THREAD

**Issue by richardblythe** [bqworks/slider-pro#292]
I have two text layers over my slide.  The first layer slides in from the left, then a second layer slides down from the top.  The layers do not remain visible like I have specified unless I quickly move the mouse over the slide at the beginning.  It's like the mouse event is triggering code that makes the layer effects behave properly.  Here's a short video that illustrates the problem:

https://youtu.be/oKce5qirOrA

**Comment by richardblythe** [comment]
I have created a hack that resolves the problem for now.  This is certainly not ideal but it works for now:

`$slider.sliderPro({
                    "init": function () {
                        $slider.css('visibility', 'visible');
                        $('#<?php echo $slider_loading_id; ?>').hide();
                        //hack to fix weird layers bug
                        setTimeout(function(){
                            $slider.trigger('mouseover');
                        },800);
                        setTimeout(function(){
                            $slider.trigger('mouseout');
                        },802);
                    },
                    "gotoSlide" : function () {
                        //hack to fix weird layers bug
                        setTimeout(function(){
                            $slider.trigger('mouseover');
                        },800);
                        setTimeout(function(){
                            $slider.trigger('mouseout');
                        },802);
                    }
});`

**Comment by davidghi** [comment]
Hi. Sorry for the late reply! If you post a link to the page, I could check if some setting is causing it to behave in this way.

Best,
David

**Comment by richardblythe** [comment]
Thanks for your reply and for your help.  Here's the site:
https://harvestnortheast.com/

**Comment by davidghi** [comment]
You're welcome! You can fix the issue without the hack by increasing the value of the `autoplayDelay` option (default value is 5000 ms) to 6000 or more. The current problem is that the slider tries to navigate to the next slide too early after the layers become visible.

**Comment by richardblythe** [comment]
Thank you so much!

**Comment by davidghi** [comment]
You're welcome!
