### ISSUE TITLE
full height and full width slider

### ISSUE THREAD

**Issue by boducoscar** [bqworks/slider-pro#30]
Hi,

I need to create slider which need to be 100% percent of window width. However, i put:
$('.photo_album').sliderPro({ width: '100%',height:'100%'});
it will not show the slider?

**Comment by davidghi** [comment]
Hi. Try `forceSize: 'fullWidth'`. Don't use `height: '100%'` unless the slider's container also has a set height, otherwise the slider will collapse with a 0 height, which is expected.

**Comment by boducoscar** [comment]
Hi,

I use forceSize: 'fullWidth' but then the image is not reponsive anymore. Do i need to do something more?

Thanks,

**Comment by davidghi** [comment]
Hi. Please take a look at Example 2. The slider is full-width and the images are still responsive. Nothing else is required for this to work.
