### ISSUE TITLE
Adjust fullscreen size

### ISSUE THREAD

**Issue by lexuanbach1992** [bqworks/slider-pro#300]
Hi,
I have a problem is that when i click on the fullscreen button the image is zoom in a lot. I found that the image is not calculated base on my screen size but it is base on the slide bar.

![Untitled](https://user-images.githubusercontent.com/30224214/70697033-637f2c00-1cf7-11ea-8e47-743ed0ddad60.png)

And here is when it is fullscreen
![Capture](https://user-images.githubusercontent.com/30224214/70697171-a0e3b980-1cf7-11ea-9d22-89f3d83a5be1.PNG)

Can please help me, thank you so much!

**Comment by davidghi** [comment]
Hi,

The fullscreen slider should take the size of the window, not the size of the whole page, but I'm not sure why it behaves in this way for you. I would need to take a look at your page.

Best,
David
