### ISSUE TITLE
How to reload slider with different data?

### ISSUE THREAD

**Issue by pokolokatepetl** [bqworks/slider-pro#302]
I would like to load new data that replaces the first one using a button. I've made such script:

$('.sp-slides').html(HTML);
var slider = $( '#sliderRecepti' ).data( 'sliderPro' );
slider.destroy();
init();

First new data is loaded to the sp-slides than the init function destroys and rebuilds slider but nothing is working, images are missing, thumbs kind of work (new ones), but it is not working ok.
I tried just replacing DIV contents and using update() but it also made a mess.

Any ideas what I am doing wrong?

**Comment by davidghi** [comment]
This should be possible unless there's a problem with the code. If you haven't fixed it yet, I can take a look if you post a link to the page.

Best,
David
