### ISSUE TITLE
Slider doesn't work when there are 2 images and loop: true

### ISSUE THREAD

**Issue by pokolokatepetl** [bqworks/slider-pro#305]
First of all, is this project dead? It has been 18 months without update and the author seems not to respond any longer. What a pitty if that is the case...

Something is wrong if the loop:true and there are only 2 slides for example, that there are less slides than half the slider width. Flicking back brings empty space and flicking forward doesn't scroll but brings second image from the right again.

Seems a bug in updateSlidesOrder function...

**Comment by davidghi** [comment]
Hi,

I dedicated less time for it lately, but it's not abandoned.

When you have only two or three slides, `loop` should be disabled. Please see this for more info: https://github.com/bqworks/slider-pro/issues/5

Best,
David

**Comment by pokolokatepetl** [comment]
Hi

Glad it is developed! I gladly pay for support, it is brilliant slider, the best!

Maybe in the future you look how many slides there are and disable the loop if there are only 2 slides...
