### ISSUE TITLE
slider-pro in a modal and when img {width:100%;} for all images on the site

### ISSUE THREAD

**Issue by beyz** [bqworks/slider-pro#308]
Hi,

I have two issues;
1) It will not display in bootstrap 4 when you first time click to view modal content, but it will show when you resize the screen.

2) img {width:100%;} for site wide responsiveness but this will also effect the slider-pro when screen is small, it will move image to the right as you make screen smaller. When I remove img {width:100%;}, it will work fine.

Thank you in advance.

**Comment by davidghi** [comment]
Hi,

Regarding the first issue, please see this: https://github.com/bqworks/slider-pro/issues/307
For the second issue, you could skip the slider images by using this selector: `img:not(.sp-image)`

Best,
David
