### ISSUE TITLE
How to make a thumbnail move on cursor click? 

### ISSUE THREAD

**Issue by AbeG888** [bqworks/slider-pro#315]
Would anybody happen to know how to make the thumbnails move on cursor click just like the slides move? 

If one hovers with the mouse over an unselected thumbnail and clicks, the unselected thumbnail should become active and move  by one slide - up on vertical thumbs, and to the left on horizontal thumbs -, so that with the mouse in the same position one should be able to click again and again on moving (unselected) thumbnails. 

Many thanks for any help.

**Comment by davidghi** [comment]
This happens by default if you click on the margin thumbnails and it happens in both ways: to the left or to the right. Are you referring to only advancing the thumbnails upon click on any thumbnail, not moving back as well?

**Comment by AbeG888** [comment]
Dear David,

many thanks for your reply. 

What I am looking for was something different, but I am not sure anymore if this is even possible. So I don’t want to bother you with half-baked ideas. 

Many thanks for your time & consideration,

Abe
