### ISSUE TITLE
Why your Website is Down?

### ISSUE THREAD

**Issue by awplige** [bqworks/slider-pro#317]
bqworks.com why is your website is down?

Any changes to get up? Are you okay David?

I hope you will up the site soon.

Thanks

**Comment by davidghi** [comment]
Hi,

I wanted to give up the business, so I put the plugins for free on bqworks.xyz. I had a difficult period. Now I'm trying to get back to maintaining the plugins.

**Comment by FARAZFRANK** [comment]
Let us know how can we help you?

The community will help you in, whatever you needed bro.

Thanks
Faraz

**Comment by davidghi** [comment]
I appreciate your kind intention and appreciative words, Faraz.

Best,
David

**Comment by michas0602** [comment]
@davidghi Thats good to hear, you´ve done an awesome job here and I really hope you keep it up. Best wishes and regards, Michael

**Comment by wpexplorer** [comment]
@davidghi - It's nice to see you are back! If you need any support to help keep this project alive let me know! I don't have much of a budget but I am willing to donate, link to your WP plugin (if it's still around), help with development, etc. Let me know. This script is the best out there!

- AJ

**Comment by davidghi** [comment]
Thank you both for the appreciative words! :)
