### ISSUE TITLE
How to change autoplayDelay value after some time

### ISSUE THREAD

**Issue by webprogrammierer** [bqworks/slider-pro#318]
How can I change the autoplayDelay value after the slider is already running, e.g. by clicking on a button?

I want to re-initialize the slider with different values/options after some time.

How to do this?

**Comment by davidghi** [comment]
You can try this:

```javascript
var slider = $( ".slider-pro" ).data( "sliderPro" );

slider.settings.autoplayDelay = 3000;
```

If you want to restart the autoplay, you can stop it first and then start it:

```javascript
var slider = $( ".slider-pro" ).data( "sliderPro" );

slider.stopAutoplay();
slider.startAutoplay();
```
