### ISSUE TITLE
Carousel Example?

### ISSUE THREAD

**Issue by wpexplorer** [bqworks/slider-pro#32]
First of all I love this slider, so far...awesome! Just started using it today ;)

Would you mind creating a simple carousel example for the docs?

I see the visibleSize and slideDistance properties and testing it out it seems to work somewhat well, I'd love to see an example though created by the author.

Thanks!

ps: I want to write a review of your WordPress plugin on my blog @wpexplorer just went out and got it.

**Comment by davidghi** [comment]
An example of the carousel layout is the second [example](http://bqworks.com/slider-pro/#example2). The bigger the `visibleSize` value is compared to the `width` value, the more slides will be visible. For example, if `visibleSize` is 900 and `width` is 300, three slides will be visible.

Cheers.

**Comment by wpexplorer** [comment]
@davidghi - Sorry, apparently I am blind ;)

Your slider is freaking amazing man.  Do you have a paypal I can donate to? Or would you rather I buy an extended version? I'd love to donate a bit more because I love this slider, it's the only one out there that isn't broken - lol.

**Comment by davidghi** [comment]
Thank you for the good intentions, but it's not necessary to donate or purchase an extended license, unless you plan to use it. However, any help in promoting the slider is much appreciated :)
