### ISSUE TITLE
Thumbnails and Slides scramble. 

### ISSUE THREAD

**Issue by Veil232425** [bqworks/slider-pro#320]
Hello. 

What is happening on my case is a little weird because the images scramble, the slide images and the thumbnail images. This happens randomly in the 9 sliders I have, sometimes scramble in one slider, sometimes in two or three. When I update the page, sometimes it is corrected, but there is always at least one that behaves that way.

This is an scrambled slider.
https://pasteboard.co/JYqfZG8.png

I've seen some of the issues presented here and I have tried the "CSS position" solution, but still the same.

         .sp-slide{
	   position: static !important;
	   }
	  .sp-thumbnails{
	   
            position: static !important;
		  
	   }
	   .sp-image{
	    position: static !important;
	   }
	   .sp-thumbnail {
		position: static !important;   
	   }

**Comment by davidghi** [comment]
Hi,

Please remove the custom CSS because it might not be fit for your issue and check if there are any JavaScript errors in the browser's Console.
