### ISSUE TITLE
Google indexing

### ISSUE THREAD

**Issue by michas0602** [bqworks/slider-pro#322]
Hi,
I am using your Slider-pro in combination with Fancybox3 and also have asked this question there, but no solution until now. I am trying around with alt-text for Google indexing since a while, but without success - Google just shows a few of my images, I assume I am doing something wrong and already have read that caroussell is a very complicated subject regarding Google.

[I use Facybox3 with Slider-Pro](https://www.nachtlicht-fotografie.de/portfolio/fotografie), in html initialized with

<div class="slider-pro" id="ms-Photos-Locations">
    <div class="sp-slides">
        

        <div class="sp-slide">
            <a href="url/example.jpg"
            data-caption="Berlin"> 
            <img class="sp-image" src="" 
            data-src="url/example.jpg" data-alt="Berlin" /></a>
        </div>
        
...

I assume my problems are caused by the usage of data-src for lazyload? However, does anyone have an idea how I could solve it?

I have 3 different Sliders on my page, all working the same - how do I ensure, that Google 100% find all "alt"-texts for every image (not just the lazyloaded first ones) for every image I have in my Sliders? Does Google recognize 'data-alt' at all or do I have to use just "alt" Whatever I try, nothing seems to to be recognized by Google. Changing the sitemap is also not possible with my 'hp-builder'.

Many thanks for ideas, your great work and with best regards,
Michael

**Comment by wpexplorer** [comment]
@michas0602 - Google will not recognize data-alt, all you need to do is include the alt attribute as well like such:

```
<div class="sp-slide">
    <a href="url/example.jpg"
    data-caption="Berlin">
    <img class="sp-image" src=""
    data-src="url/example.jpg" data-alt="Berlin" alt="Berlin" /></a>
</div>
<!-- Slide 2 -->
```
In fact, the data-alt isn't needed for anything. I'm not quite sure why you are adding that. Most likely you are using this data attribute to display a title in the slider itself, but you could target the standard alt attribute instead instead of having both.

**Comment by davidghi** [comment]
In addition to what AJ said, if your images still don't get indexed, you could try to use some thumbnail images as the default images, instead of a blank image.

Best,
David

**Comment by michas0602** [comment]
In the meanwhile some more of my images are found by Google.

Currently (since I started this issue) my html looks like this:

```
 <!-- Slide 1 -->

        <div class="sp-slide">
            <a href="https://image.jimcdn.com/app/cms/image/transf/dimension=2048x2048:format=jpg/path/s4354a59fbfee63e4/image/ibd29d513773268b3/version/1616265206/image.jpg" title="Moorpflanze"
            data-caption="Moorpflanze&lt;br&gt;2016/10/29, Sulingen&lt;br&gt;1/400 Sek.&lt;br&gt;f/2,8"><img class="sp-image" src="" data-src=
            "https://image.jimcdn.com/app/cms/image/transf/dimension=2048x2048:format=jpg/path/s4354a59fbfee63e4/image/ibd29d513773268b3/version/1616265206/image.jpg" alt="Moorpflanze" title=
            "Moorpflanze" /></a>
        </div>
```

And the result is here:
![2021-06-23-152845_1280x720_scrot](https://user-images.githubusercontent.com/29848666/123108142-73beae00-d43a-11eb-8831-112a955211a7.png)

But the results are not showing title or data-attributes in the search results...what could I try now, that Google shows something like the titles or data attributes in its search results?

Furthermore I've recognized that if I click any of my images in Google, I get forwardedd onto my page where the sliders are - is there anything I can do, that the clicked image open on my homepage directly in the slider?

Many thanks and with best wishes, Michael

**Comment by davidghi** [comment]
Thank you for sharing your results!
