### ISSUE TITLE
How to do when hover on thumbnail slider will change and when click thumbnail it will go to single blog

### ISSUE THREAD

**Issue by jamsjon009** [bqworks/slider-pro#323]

**Comment by davidghi** [comment]
To navigate to a slide on thumbnail hover, you can use this code:

```javascript
$( '.sp-thumbnail-container' ).on( 'mouseenter', function(){
     var thumbnail = $( this );
     thumbnail.parents( '.slider-pro' ).sliderPro( 'gotoSlide', $( this ).index() );
});
```

You can add the link for a thumbnail in the HTML code:

```html
<div class="sp-thumbnails">
	<a href="http://bqworks.net">
		<img class="sp-thumbnail" src="http://bqworks.net/slider-pro/images/image1_thumbnail.jpg"/>
	</a>
	<a href="http://bqworks.net">
		<img class="sp-thumbnail" src="http://bqworks.net/slider-pro/images/image2_thumbnail.jpg"/>
	</a>
	<img class="sp-thumbnail" src="http://bqworks.net/slider-pro/images/image3_thumbnail.jpg"/>
	<img class="sp-thumbnail" src="http://bqworks.net/slider-pro/images/image4_thumbnail.jpg"/>
</div>
```

**Comment by jamsjon009** [comment]
> To navigate to a slide on thumbnail hover, you can use this code:
> 
> ```js
> $( '.sp-thumbnail-container' ).on( 'mouseenter', function(){
>      var thumbnail = $( this );
>      thumbnail.parents( '.slider-pro' ).sliderPro( 'gotoSlide', $( this ).index() );
> });
> ```
> 
> You can add the link for a thumbnail in the HTML code:
> 
> ```
> <div class="sp-thumbnails">
> 	<a href="http://bqworks.net">
> 		<img class="sp-thumbnail" src="http://bqworks.net/slider-pro/images/image1_thumbnail.jpg"/>
> 	</a>
> 	<a href="http://bqworks.net">
> 		<img class="sp-thumbnail" src="http://bqworks.net/slider-pro/images/image2_thumbnail.jpg"/>
> 	</a>
> 	<img class="sp-thumbnail" src="http://bqworks.net/slider-pro/images/image3_thumbnail.jpg"/>
> 	<img class="sp-thumbnail" src="http://bqworks.net/slider-pro/images/image4_thumbnail.jpg"/>
> </div>
> ```

Thank you so much

**Comment by jamsjon009** [comment]
Finally its work

**Comment by jamsjon009** [comment]
@davidghi davidghi, Thanks bro

**Comment by davidghi** [comment]
You're welcome!

**Comment by wpexplorer** [comment]
@davidghi - You are really going out of your way to help people, which I really admire, but have you considered selling support licenses so you are paid for your valuable time?

**Comment by davidghi** [comment]
Yes, I've considered that. Now I'm doing some work on the WP plugins and putting them on wordpress.org and then I will think about monetization methods. Maybe I'll sell support licenses or I'll charge for extra work.

**Comment by AJAYSINGAL** [comment]
I would like to unsubscribe please.

Ajay Singal
Sent From my iPhone


On Jul 13, 2021, at 3:40 AM, David Ghiurau ***@***.***> wrote:

﻿

Yes, I've considered that. Now I'm doing some work on the WP plugins and putting them on wordpress.org and then I will think about monetization methods. Maybe I'll sell support licenses or I'll charge for extra work.
