### ISSUE TITLE
Full width slider

### ISSUE THREAD

**Issue by bdadev** [bqworks/slider-pro#33]
Sorry for the implementation that did in his slider, the designer asked things with CSS. [Here example](http://www.blanc1.com.br/web).

One thing that is happening I could not identify is that the exchange of the slide image is removed, see please print! 
![print](https://cloud.githubusercontent.com/assets/3835895/6060050/22aa140c-ad20-11e4-9484-5eab88165e68.jpg)

The only change I made was to put an opacity over the images in css and call the plugin used the init method to insert .sp-selected the item.

``` javascript
var target = $('#slider');

    target.sliderPro({
        width: '100%',
        height: 395,
        slideAnimationDuration: 900,
        arrows: true,
        buttons: true,
        visibleSize: '100%',
        forceSize: 'fullWidth',
        slideDistance: 0,
        imageScaleMode: 'contain',
        autoHeight: true,
        init: function() {
            if (!target.find(".sp-slide").first().hasClass('sp-selected')) {
                target.find(".sp-slide").first().addClass('sp-selected');
                // return;
            }
        }
    });
```

Please be I did something wrong?

**Comment by davidghi** [comment]
That happens because there are only 3 slides and the `loop` option is set to `true`. To avoid it, you  need to either add more slides or set `loop` to `false`.

**Comment by bdadev** [comment]
Okay, but if you use this option the slider starts empty on the left. That's right?

![err](https://cloud.githubusercontent.com/assets/3835895/6104057/39581280-b031-11e4-8712-a86373daea89.jpg)

**Comment by davidghi** [comment]
You could set `startSlide` to 1 (indexes start from 0), so that the second slide is selected by default. Or, if you have four slides or more, you can leave `loop` to `true`.

**Comment by bdadev** [comment]
ok friend! The truth is that we need a minimum of 5 slides, so why plugin calculates based on the maximum width set in css max-width.

Thanks for listening and for presenting us with this amazing plugin.
