### ISSUE TITLE
Lazy Load Doesn't Function When Using gotoSlide()

### ISSUE THREAD

**Issue by zadees** [bqworks/slider-pro#34]
Enjoy using this plugin and have started to implement it on a website that I am working on. Everything works great except for one issue with the lazy loading of the slider images. When You use the gotoSlide via javascript and go to a slide that hasn't loaded yet, the slide stays as the loading image and doesn't replace the source. Any ideas as to what is going on with this or how to fix it?

**Comment by davidghi** [comment]
I wasn't able to replicate the problem. For me the images load well even when using the `gotoSlide` method. Can you post a link to your page?

**Comment by zadees** [comment]
I emailed you the link, just don't want the link published. Thank you for your help.

**Comment by davidghi** [comment]
OK. I took a look at the page and I noticed that an error is thrown when you call gotoSlide(). You can see the error in the Console, in Developer Tools or Firebug. Please check what value is passed to gotoSlide and make sure it's an integer.

**Comment by zadees** [comment]
Thanks for the help David. I can't believe I didn't see that, spent hours testing this thing and never once realized that I was passing the numbers as a string.

Anyhow, anyone else facing the same issue make sure you use parseInt()

    imageID = parseInt(imageID);
    $('#sliderID').sliderPro('gotoSlide',imageID);
