### ISSUE TITLE
Disable Auto Height animation on init

### ISSUE THREAD

**Issue by wpexplorer** [bqworks/slider-pro#36]
I would love to have the auto-height animation between slides, but disable it on init, I can't quite figure out how to do and (and if possible) without modifying the core script. Any help would be greatly appreciated - thanks!

**Comment by davidghi** [comment]
You can start with `autoHeight` set to `false` and then set it to `true` at a later time: `$( '.slider-pro' ).sliderPro( 'autoHeight', true );`. However, I'm not sure if this will work for what you're trying to achieve. If you provide more details, maybe I can propose a different work-around.

Cheers.

**Comment by davidghi** [comment]
I assume you've figured out a way or abandoned it, so I'm closing this.

**Comment by wpexplorer** [comment]
Oh sorry didn't see the initial question. I think your solution would work, I'll try it out. Thanks!

Basically I don't like how when you first visit the page the slider animates, I would like the initial load to not have an animation but as soon as you transition to a new slide it does animate.

**Comment by davidghi** [comment]
If the height of the slider is the same with the height of the first slide, it won't animate when it loads. Maybe this would be a solution.

**Comment by jbcoder** [comment]
I'm having an issue with the same thing.

**Comment by davidghi** [comment]
@jbcoder, try the solutions I proposed above.

**Comment by jbcoder** [comment]
I got it working. As you said in another post, its width was 0 since it was set to "display: none" in my modal body. So, I made it so that when the user clicked the link for the modal, my script would set the modal to "display: block" and then your resize method would be called. Now it works perfectly. Thanks so much for your work on this. It's beautiful.

**Comment by wpexplorer** [comment]
@jbcoder - what I have been doing also instead of having a pre-loader is I display the first image of the slider while the other slides load then I hide it and show the slider. I think this usually looks a bit nicer then a blank space with a loader (but really depends on the design).
