### ISSUE TITLE
Auto play problem in Full-screen mode when  autoplayOnHover = pause.

### ISSUE THREAD

**Issue by janeks** [bqworks/slider-pro#37]
In full-screen mode can’t start auto play when  autoplayOnHover is set to pause.  
It seems that there is no way to move the mouse pointer outside the slider container to trigger startAutoplay().

**Comment by davidghi** [comment]
Well, when the slider is in full-screen mode, it occupies the entire screen, so you can't really move the mouse outside the slider area.

The solution is to disable the autoplayOnHover when the slider is in full-screen mode: `$( '.slider-pro' ).sliderPro( 'autoplayOnHover', false )`. Then, re-enable it when you exit the full-screen mode.

**Comment by janeks** [comment]
Changing the interface behavior between screens will confuse the users.
Is there a way to constrain the autoplayOnHover to sp-slides-container or sp-thumbnail-container div?

**Comment by davidghi** [comment]
You can listen for mouse over/out events on any element and then use the stopAutoplay() and startAutoplay() methods to stop/start the autoplay. You will also need to disable the autoplayOnHover option.

**Comment by janeks** [comment]
Added:
```javascript
var slider = $("#slider").data( "sliderPro" );
$( ".sp-thumbnails-container" ).on( "mouseleave", function() { slider.startAutoplay();});
$( ".sp-thumbnails-container" ).on( "mouseenter", function() { slider.stopAutoplay();});
```
Works but there are some issues:
1. Starts auto play when thumbnail is clicked. Even when mouse pointer is still hovering over thumbs container.
2. Won't start auto play when switched to full screen. Starts only after mouse is moved over thumbs container.

**Comment by davidghi** [comment]
Try this:

```
var slider = $("#slider");
$( ".sp-thumbnails-container" ).on( "mouseleave", function() { slider.sliderPro( 'autoplay', true ); } );
$( ".sp-thumbnails-container" ).on( "mouseenter", function() { slider.sliderPro( 'autoplay', false ); } );
```

**Comment by janeks** [comment]
Seems to be working. Thank You.

**Comment by davidghi** [comment]
You're welcome!
