### ISSUE TITLE
Thumbnails with variable width items

### ISSUE THREAD

**Issue by chaplin** [bqworks/slider-pro#40]
Is there a way to make the thumbnails with variable width of the items?

**Comment by prodesignmax** [comment]
sorry , when i hover on image the mouse icon show as move tool not open hand or close hand icon and the browser give me failed massage in ( jquery-1.11.0.min.js:3 ) and say :open hand not found + closehand

**Comment by davidghi** [comment]
@chaplin It's not fully supported. You could set the thumbnailWidth to 'auto' but then you would need to manually assign the width of the .sp-thumbnails element and set the width of the .sp-thumbnails-container element to 100%.

@prodesignmax If that happens in IE, it's expected. If it's in other browses you probably don't have the 'images' folder that contains the hand icons.

**Comment by chaplin** [comment]
thanks for your reply, and this is best slider plugins i've ever used.
