### ISSUE TITLE
better clickable arrows

### ISSUE THREAD

**Issue by hivre** [bqworks/slider-pro#42]
I noticed that only the arrows are clickable, not a vertical band on both sides of the slider.
This resulted on "mis-clicks", especially on smaller devices. Nuisance when people click and nothing happens, annoying when there's a link attached to the slide and the user gets send off to that location.

I forked the repo, and started to fix this, but am running in some issues. 
I'm not a JS-ninja, so this might be noob-territory, but how do I get the slideHeight from the current slide?

I now use: `var slideHeight = this.options.height;` in `arrows.js` but if a user hasn't set the height option it'll break the implementation. I'd rather use the current height of the slider (or is the mask gets auto-updated than that's fine as well)

On a related note, the arrows get ugly on fullScreen. How can I update/rerun the calculation from `_arrowsOnUpdate` whenever a user turns to fullScreen mode?

My forked repo: https://github.com/hivre/slider-pro/commit/5211db50c7411cb38aad46d09391ac22edcc0e22

**Comment by davidghi** [comment]
You can use $( '.sp-mask' ).height() to get the current height of the slides.

Please take a look at the FullScreen module to see how you can detect when the fullscreen state change.

**Comment by hivre** [comment]
hmm,  I'm always getting `0` returned when run within the `_arrowsOnUpdate: function()` function.
`$(this.$slideMask).height()` likewise returns 0. 

I also expected the `_arrowsOnUpdate` being run on every update (change of screensize, going full-screen etc.) but that isn't the case.

**Comment by davidghi** [comment]
It's better to detect the size of an element by listening to the 'resize' event. Also, the 'update' event is not triggered when the screen size or full screen state changes, it's triggered only when the slider's settings are changed. As you can see in the FullScreen module, I use the browser's 'fullscreenchange' event to detect fullscreen changes. Please take a look at that module for more details about the implementation.
