### ISSUE TITLE
Slider in browser full window instead of full screen

### ISSUE THREAD

**Issue by janeks** [bqworks/slider-pro#43]
Is there a way to display slider-pro in browser full window instead of full screen?
Example: http://abcfolio.com/demos/fullscreen-slides/image-metadata-captions/

**Comment by davidghi** [comment]
Yes: `forceSize: 'fullWindow'`

**Comment by janeks** [comment]
Maybe I'm missing something but the  <code>forceSize: 'fullWindow'</code> makes only the slider container 100%. It doesn't cover the full browser window. Website header and footer are still visible.

Slider-Pro container in fullWindow mode has style <code>style="margin: 0px 0px 0px -372.5px; width: 1920px;</code>.

The example I've provided a link to, has a slider container styled: <code>style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 10000;"</code>.  It fills up the whole browser window and stays on the top of any other content.

**Comment by davidghi** [comment]
When you set `forceSize: 'fullWindow'`, the slider's width and height will become equal to the window's size. In the link you posted, there isn't a header or footer or any other content besides the slider; use the slider in the same context and it will look exactly the same. If, however, you have other content in the page and you want to have the slider displayed in the background and visible on the entire page, that's something else and for that it's important in what container you insert the slider. You need some HTML and CSS knowledge for this. You can try it first with a simple image and after you achieved placing it properly you can replace the image with the slider.

**Comment by janeks** [comment]
As long as I know that <code>fullWindow</code> resizes only the holding container I’m OK with it. It’s easy to overwrite.

Contrary to your explanation styling container position as fixed and using large z-index creates the full window effect on any kind of content including the one with header and footer. 

Thank you for an excellent product and prompt support.
