### ISSUE TITLE
Flickering effect on initial load

### ISSUE THREAD

**Issue by saladj** [bqworks/slider-pro#45]
The photo gallery with the slider is displaying some flickering effect on the initial load. 
All the images seem to be loading in a vertical line and then in a few seconds the correct layout is rendered. Is there a way to ensure the gallery is displayed only once it is fully loaded if not what is the best way to handle this?

**Comment by davidghi** [comment]
That happens before the slider's JavaScript code is executed. You can add the 'sp-no-js' class to the slider and this class will be removed after the slider is instantiated, so you can use some CSS code that will be applied only before the slider is executed.

For example:
```
.sp-no-js {
    visible: hidden;
} 
```
