### ISSUE TITLE
Problems with portrait-oriented images

### ISSUE THREAD

**Issue by alexkuk** [bqworks/slider-pro#46]
Thanks for the good peace of software, I find it easy to run and customize. However I have at least two problems and I guess all are related to using portrait-oriented images. I have a slider, that uses a defined size images: 474x600px. These problems occur even when running default slider-pro, without options.
1. Touch sliding to a previous slide doesn't work. A current image follows my finger/cursor, but nothing happens, and it also doesn't return to an initial position, staying half-visible. However arrows navigation works well.
2. The full-screen mode stretches images by full width, and it cuts the bottom.
3. Would be great to have an option to set custom image source files for the fullscreen mode.

**Comment by boducoscar** [comment]
2. I fixed it by setting max height for the photo in slide if there are many photo have different size

**Comment by davidghi** [comment]
@alexkuk Please post a link to your page so I can see exactly what happens.

**Comment by alexkuk** [comment]
@davidghi here: http://ec2-54-154-71-74.eu-west-1.compute.amazonaws.com/slider-pro-1.2.1/examples/example_alexkuk.html

**Comment by davidghi** [comment]
The behavior you described is expected given your current configuration.

1. If you use only two images I recommend setting loop to false. If you add more images, you won't have this problem, which is actually expected in a setup with only two slides and infinite loop.

2. The imageScaleMode is set to 'cover' (the default value). You need to set it to 'contain' if you want the full image to be visible.

3. It's possible to use different images for different screen sizes, which is better than targeting directly full-screen mode.

**Comment by alexkuk** [comment]
@davidghi 1 and 2 - indeed your suggestions work, thank you very much!
Regarding the point 3, I don't agree. Let's say I have a slider that takes only a small part of a screen, and I don't need a big picture file there, 474x600 is totally OK there. When I go to the full-screen mode, my browser frame is not becoming much bigger, just toolbars disappear, but as the position and size of slider changes, I'd expect to have an option to provide a bigger picture, no matter what is the screen size. I don't think it's possible with current options, or do I miss something?
Thx

**Comment by davidghi** [comment]
Full-sceen might be of different sizes depending on the monitor screen, so I think it's better to target directly certain sizes than the full-screen mode. What if you set a 500X600 for your full-sceen mode, based on what you consider ideal on your monitor, but on a bigger monitor that full-sceen image will appear pixelated. Also, I need to make a correction: actually not screen sizes are targeted but slider sizes. Please read about the Conditional Images module.

**Comment by alexkuk** [comment]
@davidghi Cool! I was confused by "screen size", in my case screen size and slider size are not connected. Thank you!

**Comment by davidghi** [comment]
You're welcome!
