### ISSUE TITLE
Thumbnail position

### ISSUE THREAD

**Issue by rickysullivan** [bqworks/slider-pro#47]
RE: https://github.com/bqworks/slider-pro/blob/master/docs/modules.md#14-thumbnails

If I were to put the thumbnail inside the slide aka:
```
<img class="sp-image" src="path/to/image1.jpg"/>

<img class="sp-thumbnail" src="path/to/thumbnail.jpg"/>
``` 
Do I need to modify the CSS or should the thumbnails still work as per http://bqworks.com/slider-pro/#example3

I'm building a slideshow using PHP and was trying to minimise loops.

**Comment by davidghi** [comment]
You don't need to modify the CSS. It will work out of the box.
