### ISSUE TITLE
Slider Pro inside Foundation 5 structure

### ISSUE THREAD

**Issue by DOCSpeedFreak** [bqworks/slider-pro#49]
Hello from austria,

I´ve got a problem using this fabulous slider inside my foundation structure. I´d like to use a structure like this to show the slider on the left and the thumbnails in a 3col grid to the right. Markup inside foundation would be:
div.row
  div.col
    div.sp-slides
  /div
  div.col
    div.sp-thumbnails
  /div
/div

The problem is that the script always builds its own container outside of my col divs:
div.row
  div.col
  /div
  div.col   
  /div
  div.sp-slides-container
  /div
   div.sp-thumbnails-container
   /div
/div

Is there any way besides changing the source code that I can keep the containers inside my cols?
Thanks for your help

**Comment by davidghi** [comment]
Hi. Unfortunately it's not possible without some code changes.
