### ISSUE TITLE
Skipping Slides on Browser Resize

### ISSUE THREAD

**Issue by Murphy1976** [bqworks/slider-pro#50]
Here's a weird issue I ran into. The slider runs fine in ALL major browsers and is responsive in ALL major browsers as well, but I ran into an issue where then I resize the browser with the slider-pro displayed, and I let go of the corner or I turn the orientation of my mobile device, the slider will either skip entirely, or show the next slide for a split-second, then go to the slide after that.

When the slider comes around again to the slide is skipped, it will play fine.  I am wondering if there is a play/pause I can instill while resizing the browser window, that will pause the slider while I am resizing, and then start up again after I have stopped resizing the window.

**Comment by davidghi** [comment]
Hi. In the docs you can find some public methods to pause/play the slider programatically.
