### ISSUE TITLE
problem with click function and slider init

### ISSUE THREAD

**Issue by HansWill** [bqworks/slider-pro#52]
my slider div was filled with php 
i make a click Funktion on the link and i want load my filled div with jquery .load(link ' #mydiv')
to load it to an div,  the data (Pictures, videos, thumbs) are loaded but the init function not works so my div loos crazy. Here ar my two scripts can you tell me what is wrong? Thanks.
<script type="text/javascript">
    $(document).ready(function(){
			$('a.gal').on('click',  function(e) {
			e.preventDefault();				
			var link = $(this).attr('href');
			$('#topbox').html(link+ '  #slider');
			//console.log(link);
			return false;
		});
    });
</script>
<script type="text/javascript">
	$( document ).ready(function($) {
		$( '#slider' ).sliderPro({
			width: 900,
			height: 480,
			fade: true,
			arrows: true,
			buttons: false,
			fullScreen: true,
			shuffle: true,			
			thumbnailWidth: 160,
			thumbnailHeight: 82,
			thumbnailArrows: true,
			autoplay: false
		});
	});
</script>

**Comment by davidghi** [comment]
Make sure you instantiate the slider after it's loaded.

**Comment by HansWill** [comment]
i think i do it here are my scripts:
<script type="text/javascript">
    $(document).ready(function(){
			$('a.gal').on('click',  function(e) {
			e.preventDefault();				
			var link = $(this).attr('href');
			$('#topbox').html(link+ '  #slider');
			//console.log(link);
			return false;
		});
    });
</script>
<script type="text/javascript">
	$( document ).ready(function($) {
		$( '#slider' ).sliderPro({
			width: 900,
			height: 480,
			fade: true,
			arrows: true,
			buttons: false,
			fullScreen: true,
			shuffle: true,			
			thumbnailWidth: 160,
			thumbnailHeight: 82,
			thumbnailArrows: true,
			autoplay: false
		});
	});
</script>

**Comment by davidghi** [comment]
It's not clear what happens without knowing more details. Anyway, this doesn't seem to be a problem with the slider itself, but with your implementation, so I recommend keep testing and try to figure out what you're doing wrong.

**Comment by HansWill** [comment]
on ma php site i have links like this: a href=\"menue.php?s=overview&id=".$row['ID'].
i called this links with the jquery click Funktion so my slider div was loaded in an other div.
the slider loded fine but it found not the init so all all files are on each other and the first element style with: 900 height: 480 and sp-horizontal" was not found i use example 3

**Comment by davidghi** [comment]
I'm sure this is not a problem with the slider itself, but it has to do with your implementation. I can't tell you exactly where the problem is without seeing the whole page, but it's also outside the scope of this support area.

**Comment by HansWill** [comment]
ok simple thing make a div on a page and with a click function in jquery load the slider div from example3 then look on the result, thanks.
	$( document ).ready(function() {
		$('#link').on('click', 'a.tester', function(e) {	
		e.preventDefault();				
		var link = $(this).attr('href');		
		$('#top').load(link+ ' #example3');
		console.log(link);
		return false;			
	});
});
is there a way after load the div to reinit the scripts?

**Comment by HansWill** [comment]
ok i have found the solution you must reinit the script after ajaxload is complete.
	$( document ).ready(function() {
		$("a.gal").on("click", function(e) { 
		e.preventDefault(); 		
		var link = $(this).attr("href");		
		$("#topbox").load(link+ " #test");
		//console.log(link);
		return false;
	});
	$(document).ajaxComplete(function(event){ 
        $('#test').sliderPro({
			width: 900,
			height: 480,
			fade: true,
			arrows: true,
			buttons: false,
			fullScreen: true,
			shuffle: true,			
			thumbnailWidth: 160,
			thumbnailHeight: 82,
			thumbnailArrows: true,
			autoplay: false
		});
    });
});

**Comment by davidghi** [comment]
Glad you've worked it out. I suggested that in my first reply.

**Comment by HansWill** [comment]
yes thanks i missunterstand this a Little question i have i use example3 and when i click fullsize in ie 11 i see the thumbs on bottom but i dont see the thumbs on bottom in Firefox and Chrom what cant be wrong?
