### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by micker** [bqworks/slider-pro#53]
hello i try a first integration in joomla module but i have this error
TypeError: undefined is not a function
i try this
$document->addScriptDeclaration('
	$( document ).ready(function( $ ) {
		$( "#example1" ).sliderPro({
			width: 960,
			height: 500,
			arrows: true,
			buttons: false,
			waitForLayers: true,
			thumbnailWidth: 200,
			thumbnailHeight: 100,
			thumbnailPointer: true,
			autoplay: false,
			autoScaleLayers: false,
			breakpoints: {
				500: {
					thumbnailWidth: 120,
					thumbnailHeight: 50
				}
			}
		});
	});
');
or
$document->addScriptDeclaration('
	Jquery( document ).ready(function( ) {
		Jquery( "#example1" ).sliderPro({
			width: 960,
			height: 500,
			arrows: true,
			buttons: false,
			waitForLayers: true,
			thumbnailWidth: 200,
			thumbnailHeight: 100,
			thumbnailPointer: true,
			autoplay: false,
			autoScaleLayers: false,
			breakpoints: {
				500: {
					thumbnailWidth: 120,
					thumbnailHeight: 50
				}
			}
		});
	});
');

error is same do you have an idea ?

**Comment by davidghi** [comment]
Hi. Maybe you're not loading the slider's JavaScript file or you're loading multiple jQuery libraries.
