### ISSUE TITLE
Removing slides

### ISSUE THREAD

**Issue by Poyoman39** [bqworks/slider-pro#54]
Hi,
When a slide is removed with
```
$('#my-slider .mySlide').remove()
$('#my-slider').data('sliderPro').update();
```
The suppression is not raised to the thumbnail

And the following solution doesn't work too, because the update function re-generate the thumbnail : 
```
$('#my-slider .mySlide').remove()
$('#my-slider .myThumbnail').remove()
$('#my-slider').data('sliderPro').update();
```

Regards

**Comment by Poyoman39** [comment]
Ok I've found a way to skirt the problem, I use : 

```$('#my-slider .myThumbnail').parent().remove()```

instead of 

```$('#my-slider .myThumbnail').remove()```

But is it standard ?

Regards

**Comment by davidghi** [comment]
Hi. If you look in Developer Tools or Firebug to see the actual HTML structure of the slider, you will see that the thumbnails have a container. When you want to remove a thumbnail, you need to remove the container as well.

Cheers

**Comment by Poyoman39** [comment]
In fact the library show it's limits (for now), when trying to dynamically change the elements inside the slider.

For the project i'm working on, i need to toggle the presence of one slide, when toggling the full-screen mode.

For now i think it's impossible to reinsert the slide at his old place (without heavy manipulations), because the associated thumbnail reappear at last position (even if it is reinserted at the good position)

Regards
