### ISSUE TITLE
data-height probleme

### ISSUE THREAD

**Issue by sensukanta** [bqworks/slider-pro#56]
I have applied function in html page.

 $(document).ready(function ($) {
 $('#slider').sliderPro({
width: 960,																	
height: 1000,																		autoHeight: true,
 arrows: true,																		fadeArrows: false,
 buttons: true,																	touchSwipe:false,
waitForLayers: true,
 thumbnailWidth: 240,
  thumbnailHeight: 65,
thumbnailPointer: true,																			thumbnailsPosition: 'top',
 autoplay: false,
 updateHash: true   
                });
            });

Run time add elements not getting height properly. page is partially visible.
At on click event devexpress model popup is not showing. 
kindly help me.

**Comment by davidghi** [comment]
Hi. Please provide a live example.

**Comment by davidghi** [comment]
If you still need help with this, feel free to reopen the issue. I'm closing it for now.
