### ISSUE TITLE
Text wrapping with layers

### ISSUE THREAD

**Issue by cjd118** [bqworks/slider-pro#58]
Hi,

Do you have any advice on how to wrap text when using layers on the slider. On mobile devices there is no text wrapping at all. As it stands, with position absolute, it's impossible to get text to wrap without resorting to hacky &lt;br&gt;'s and media queries to show/hide them.

Thanks.

**Comment by davidghi** [comment]
Hi. If you set the layer's width to a percentage value, the layer will scale down as the slider scales down.

Cheers.

**Comment by davidghi** [comment]
If you still need help with this, feel free to reopen the issue. I'm closing it for now.
