### ISSUE TITLE
Weird layout glitch when slider loads

### ISSUE THREAD

**Issue by kevinleberge** [bqworks/slider-pro#59]
Hi!

I'm getting some weird glitchy behavior when the slider is loading.  Has anyone else seen anything like this?

http://medidermspa.kevinleberge.com

thanks

**Comment by davidghi** [comment]
It's not weird. Before the slider's JavaScript code is executed it's normal to have an "unstyled" look. However, you can control that look. For example, you could hide the slider completely until the JavaScript code is executed. For this, first you need to add the 'sp-no-js' class to the slider. This class will be removed when the slider is initialized so any CSS applied to that class will be in effect only before the slider's initialization. Then, to hide the slider before it's instantiated, you need this CSS:

```
.sp-no-js {
    visibility: hidden;
}
```
