### ISSUE TITLE
Destroy Method

### ISSUE THREAD

**Issue by keithweiss** [bqworks/slider-pro#60]
Hi there, I'm trying to implement the destroy method at a specific width for mobile, but would also like to re-initiate it on a browser resize... Could you help guide me by providing the code?

I've tried this but haven't got it working, 

if ($(window).width() < 540) {
$( '#my-slider' ).sliderPro( 'destroy' );
}

Thanks

**Comment by davidghi** [comment]
Try to replace `$( '#my-slider' ).sliderPro( 'destroy' );` with a simple `console.log('destroy')`. When you get that working, you can replace it with the actual code again. If you're having problems with that, I recommend asking on sites like Stackoverflow, as it's not something specific to the slider.

Anyway, to give you some pointers: you will need to run that code inside a setInterval. It's not sufficient to make the width check one time.

Cheers
