### ISSUE TITLE
Responsive not working when width is 100% and height fixed

### ISSUE THREAD

**Issue by Yalori** [bqworks/slider-pro#61]
Hi! Like the title pretty much describes, my slider isn't responsive when i set my width to '100%' and the height to a fixed value. 
When the width is also a fixed value it is responsive. 

Is this a bug or am i doing something wrong/missing something?

Hopefully someone can help me out, thanks!

**Comment by davidghi** [comment]
Hi. When using a percentage width you will need to manually set the aspect ratio which needs to be maintained when the slider is scaled down. This can be done by using the `aspectRatio` option. For example, you could set it to 1.5 or 2.

Cheers.

**Comment by Yalori** [comment]
Thanks! Works like a charm:) 

Really like this slider, it's clean, simple and has all the options i could think of. I just have to figure out how it works:p

Btw, is there a way to change the distance between the images? So far i couldn't find how the distance is made (no padding or no margins).

**Comment by davidghi** [comment]
You can use the slideDistance option for that.

**Comment by mbliok** [comment]
Hи guys,
I'm trying to use a percentage width and put parameters such as:

$( '#example5' ).sliderPro({
	width: '100%',
        thumbnailWidth: '33%',
        orientation: 'vertical'
       .....
The problem: slider become width 100%, but the sp-thumbnails-container disappears.
In this case  "thumbnailWidth" working only with "px" and not with 33%

Can you help me, please?

Maya

**Comment by davidghi** [comment]
Hi, Maya. You can set the thumbnailWidth to a percentage value like '20%' (it's important to put the value inside quotes), but you'll also need some additional CSS to set the width of the thumbnails' container:

```
.sp-thumbnails {
    width: 100% !important;
}
```

**Comment by mbliok** [comment]
Thanks David for the fast answer, I did exactly that, but I thought there's a better way
