### ISSUE TITLE
Thumbnail outside slider div

### ISSUE THREAD

**Issue by Yalori** [bqworks/slider-pro#63]
I didn't find a similaire issue about this, so i'll ask here. 
Is there a way to position the thumbnails outside de slider div? (so they are positioned somewhere else on the website)

Also i can't seem to figure out how i get my thumbnails vertical ?

This is what i'm trying to achieve:
- Horizontal slider
- Vertical thumbnail outside slider

Example: 
![untitled-1](https://cloud.githubusercontent.com/assets/10866247/8130745/6c9553b6-1115-11e5-9928-078fafd2d966.jpg)

**Comment by davidghi** [comment]
Hi. It's not possible to move the thumbnails outside the slider, but you can create your own thumbnails and trigger the slider to move (by using the slider's API) when those thumbnails are clicked.

Cheers
