### ISSUE TITLE
Problem with links inside text

### ISSUE THREAD

**Issue by borisw1** [bqworks/slider-pro#64]
I'am using slider pro with images and Text.
Inside Text there are links, but when i have tochswipe enabled, sometimes i have to click twice on a link to work. When touchswipe is disabled, there are no problems.
Here ist the url: www.happymax-lifestyle.de/Cosmetic-care.4.0.html
First silde, "more link to work".
Any hints?

Thanks

**Comment by davidghi** [comment]
Hi. Try to add the 'sp-selectable' class to those links.

Cheers.

**Comment by borisw1** [comment]
Thanks a lot, but it makes no difference, sorry.
 Any ideas?

Thanks

**Comment by davidghi** [comment]
I tested

**Comment by davidghi** [comment]
The link works in my tests. In which browser are you experiencing the problem?

**Comment by davidghi** [comment]
I assume you managed to work it out. If not, feel free to reopen the issue.
