### ISSUE TITLE
autoplayOnHover - Start?

### ISSUE THREAD

**Issue by BB2015** [bqworks/slider-pro#65]
Hi!

Anyway you can start the autoPlay on hover, and then stop it after the mouse is off the element? versus page load and then stop or pausing the carousel.

Big thanks!

**Comment by davidghi** [comment]
Hi. You can use the slider's API to start or stop the autoplay programmatically on any event.

Cheers!

**Comment by BB2015** [comment]
Hi, sorry for the late response! Big thanks.

**Comment by davidghi** [comment]
You're welcome!
