### ISSUE TITLE
Slider: images size

### ISSUE THREAD

**Issue by eat90** [bqworks/slider-pro#66]
Hi!, im having some trouble when i try to resize images inside the slider.

Examples always use "fullwidth" images with arrows inside too, so i cannot replicate the layout that im looking for. When i try to do it, the container or mask gets modified but not the images inside of it, they stay full width.

Any tip for resizing just this images? classes like ".sp-images" or ".sp-slide/s" are not working.

Thanks!

**Comment by davidghi** [comment]
Hi. I'm not sure what look you're trying to achieve. An example would help.

**Comment by davidghi** [comment]
I assume you managed to work it out. If not, feel free to reopen the issue.
