### ISSUE TITLE
"Swipe left" bug when have only two images.

### ISSUE THREAD

**Issue by victorgutierre** [bqworks/slider-pro#67]
Hi there! I'm having a problem when i have only one or two images in my slider. When i do the swipe to the left appears nothing and the swipe breaks. 

Here is a image of what's happening:

![issue](https://cloud.githubusercontent.com/assets/3110973/8569466/54ce0474-254e-11e5-8788-75c85b181eda.jpg)

Thanks.

**Comment by davidghi** [comment]
Hi. It's not a bug, although it might not be wanted behavior. You will need to either disable the `loop` option or add more than 2 slides. It has been discussed [here](https://github.com/bqworks/slider-pro/issues/5).

**Comment by victorgutierre** [comment]
Oh uh! Thank's for the heads up.
