### ISSUE TITLE
Problem with 2 slides

### ISSUE THREAD

**Issue by style-nes** [bqworks/slider-pro#69]
http://ilko.me/slider-pro-master/examples/example1.html

.slider-pro
	.sp-slides
		.sp-slide slide 1 
		.sp-slide slide 2

When slide 2 comming slide 1 just disappears.

**Comment by davidghi** [comment]
Hi. The issue is explained here: https://github.com/bqworks/slider-pro/issues/5

The solution is to either disable `loop` or add more than two slides.
