### ISSUE TITLE
container specific width on resize

### ISSUE THREAD

**Issue by Ximore** [bqworks/slider-pro#70]
Hello

First of all - great plugin.. It is really nice.. I am currently trying to adapt width to the slider based on a container width. I am setting the width to be the width of the container once I load the page, but when I resize the page, I would like to update tis width according to my frameworks media queries.

@media (min-width: 768px){

	.container {
        width: 750px
    }

}

@media (min-width: 992px){

	.container {
        width: 970px
    }

}

@media (min-width: 1200px){

	.container {
        width: 1170px
    }

}

I have tried to use the "breakpoints" the "resize" and "update" functions, but can't seem to make it work. Is there a way to set these?

Regards

Phill

**EDIT**

I am going for a layout based on example 2 in the demo content. So I want the middle slide to be the width of the container. (just to clarify). :)

**Comment by davidghi** [comment]
Hi. Have you tried to set visibleWidth to 100%?

**Comment by Ximore** [comment]
I spent several hours working this out only to realize that I haven't even wrapped the slider in the container element. It adapts automatically now which works great! i am sorry for the issue post, since it was my own mistake. :) But thanks for taking time to look at it anyway.. Great slider plugin mate! :+1:

**Comment by davidghi** [comment]
Glad you sorted it out! :)
