### ISSUE TITLE
Problem with destroy on resize

### ISSUE THREAD

**Issue by Matt23a** [bqworks/slider-pro#71]
I want to destroy the slider on resize and restart it with new options. However there are errors when I try to destroy and recreate it. Simple Example:

    $(window).resize(function() {
    var slider = $( '#my-slider' ).data( 'sliderPro' );
    slider.destroy();
    $( '#my-slider').sliderPro();
    });

Error: Uncaught TypeError: Cannot read property 'animatedLayers' of undefined

And on the next resize it is not possible to destroy the slider, because of that error:
Uncaught TypeError: Cannot read property 'destroy' of undefined

**Comment by davidghi** [comment]
This has been fixed in 1.2.2.

**Comment by jitendraharpalani22** [comment]
I am using version 1.3. Destroy doesn't seem to be working: 

Uncaught TypeError: Cannot read property '$slide' of undefined(…) 
For reference, it's on line 486 on unminified version
