### ISSUE TITLE
Lazy loading with scrset

### ISSUE THREAD

**Issue by waldbach** [bqworks/slider-pro#72]
Hi,
I was wondering if it'd be possible to combine lazyload  (by means of data-src) and srcset? Currently trying to implement [Responsive images with WordPress Advanced Custom Fields](https://nostrongbeliefs.com/responsive-images-with-wordpress-advanced-custom-fields/) .

I have no idea if I can combine this with Slider-Pro's Lazyloading method at all, or that I'd need to drop that option.

Thanks in advance!

**Comment by davidghi** [comment]
Hi. If you want to to specify different image sources, you can use the slider's [Conditional Images](https://github.com/bqworks/slider-pro/blob/master/docs/modules.md#6-conditional-images) module.

**Comment by waldbach** [comment]
Oh, cheers! Must've overlooked it. Thanks!
