### ISSUE TITLE
Touchswipe false doesn't work in breakpoint

### ISSUE THREAD

**Issue by wittewullem** [bqworks/slider-pro#74]
I using this code to disable touchSwipe disable in smaller screens:

$( '#Carousel' ).sliderPro({
	width: 200,
	height: 150,
	autoHeight: false,
	autoplay:false,
	fade: false,
	arrows: true,
	buttons: false,
	visibleSize: '100%',
	breakpoints: {
		500: {
			touchSwipe: false,
			fadeArrows: false,
		},
	},
 })

It doesn't work. What do I wrong?

**Comment by davidghi** [comment]
The touch-swipe feature can't be disabled if it's initially enabled. I didn't consider this as a necessity, as I think in most cases you want the touch-swipe to be active on smaller screens, which are usually touch-enabled screens.

Cheers

**Comment by wittewullem** [comment]
But, when I want to make a carousel with links, I can't open them. Is there a solution?

**Comment by davidghi** [comment]
If you're referring to text links, try to add the 'sp-selectable' class to them.

**Comment by wittewullem** [comment]
It helps. Thanks.
