### ISSUE TITLE
100% height of container

### ISSUE THREAD

**Issue by Invulner** [bqworks/slider-pro#75]
Hi!
I wondering if it's possible to update some options after window resize? For example I have a wrapper for slider, and height changes by media-queries. I want my slider to fit 100% height of this wrapper. I see option to fill viewport, but not container. I've tried to update the height of slider via JS after resize, but haven't find how to do it without re-init? Please advise! Thanks!

**Comment by davidghi** [comment]
Hi. If you set the height of the slider to 100%, it will adapt to the container's height but your container also needs to have a defined height. If the height is not defined on the container, its height will be considered 0px.

Cheers
