### ISSUE TITLE
Is it possible to add the wrapper div to thumbnails

### ISSUE THREAD

**Issue by pcvector** [bqworks/slider-pro#76]
For example a 
<p>&lt;div class = &quot;sp-thumbnails-inner&quot;&gt;</p>

#######
<p>&lt;div class=&quot;slider-pro&quot;&gt;</p>

<p>&nbsp;&nbsp;&nbsp; &lt;div class=&quot;sp-slides&quot;&gt;&lt;/div&gt;</p>

<p>&nbsp;&nbsp;&nbsp; &lt;div class=&quot;sp-thumbnails&quot;&gt;<br />
&lt;div class=&quot;sp-thumbnails-inner&quot;&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;img class=&quot;sp-thumbnail&quot; src=&quot;&quot;/&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;p class=&quot;sp-thumbnail&quot;&gt;Thumbnail 2&lt;/p&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;div class=&quot;sp-thumbnail&quot;&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;img class=&quot;sp-thumbnail-image&quot; src=&quot;&quot;/&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;p class=&quot;sp-thumbnail-text&quot;&gt;Tempor incididunt ut labore et dolore magna&lt;/p&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/div&gt;<br />
&lt;/div&gt;<br />
&nbsp;&nbsp;&nbsp; &lt;/div&gt;<br />
&lt;/div&gt;</p>

**Comment by davidghi** [comment]
It's not possible because it would break the functionality of the thumbnail scroller.

Cheers
