### ISSUE TITLE
Bug when there is only two images

### ISSUE THREAD

**Issue by Poyoman39** [bqworks/slider-pro#78]
Hey ! It's me again :)

I've found there is a bug when there is only 2 slides in the image gallery (or 1 as well)

When trying to swipe by hand to the left, the image does not change, and stay at the position it is released.

Good luck for this. If you need more help to reproduce this bug, just ask me :)

**Comment by davidghi** [comment]
Hi. It's not really a bug. Please see this issue: https://github.com/bqworks/slider-pro/issues/5

Cheers

**Comment by Poyoman39** [comment]
Ty for answer :) Would it be possible at least to make the image come back to position instead of freezing in this particular case ?

Ty :)

**Comment by davidghi** [comment]
You can do that by setting the `loop` property to `false`.

**Comment by Poyoman39** [comment]
Ty for help, and sorry for disturbing you with this so ...

**Comment by jiabinMWC** [comment]
@Poyoman39 @davidghi i love you both ;) it works!
