### ISSUE TITLE
prevent slide to be center

### ISSUE THREAD

**Issue by spostad7** [bqworks/slider-pro#80]
hi,
before anything I am so thank u for your brilliant work! I also recommended it to my other colleagues. 
I have a question,
I want to make a carousel slider in bootstrap framework with specific div width (here I want to use col-md-3 class for each slide). I want to show 4 slide at the same time in one row. here's my function:
```
$('#slide2').sliderPro({
    width:262.5,
    slideDistance:30,
    height: 300,
    autoHeight:true,
    visibleSize: '100%',
    arrows: true,
    buttons:false,
    centerImage:false,
    fade: true
});
```
everything is correct, but the problem is the active slide is always in the center of container. I mean for 4 slides, I want to see them completely in it's container but now because of that, some part of first and last slides is hidden.

the active slide is highlighted in picture below:
![capture](https://cloud.githubusercontent.com/assets/2351721/9653492/f7409c3c-5238-11e5-97bf-753a6cdf0a0e.PNG)

any help will be appreciated.

**Comment by davidghi** [comment]
Hi. There isn't a built-in method for that, but if the feature is necessary for you, you can edit the source code. What you need to do is comment out line 552 from jQuery.sliderPro.core.js. If you're not using Grunt, you can search for the same line of code in the jQuery.sliderPro.js and comment it out there and then re-minify the file.

Cheers

**Comment by spostad7** [comment]
sound's good to me! I have to try it ;)
tanx for your response

**Comment by tBaxter** [comment]
I think you may also be able to do it in the CSS by fiddling with the margin: 0 auto that's on the slide. Maybe.

**Comment by spostad7** [comment]
@tBaxter:
tanx, but it seems to need some changes in code not in css. I'd try your way, nothing happend
