### ISSUE TITLE
Image slides don't match with thumblenails

### ISSUE THREAD

**Issue by Misa-no** [bqworks/slider-pro#81]
I have 5 images along with 5 thumbnails which set in the right position of sides. The problem is that one of thumbnail doesn't appear on the image in order and none of information appears correctly.
I inserted  <div class="sp-thumbnail"><div> between first and second thumbnails on html for now. It shows ok on PC but not on touch screen devices.... I used your example5 and changed the look as follows;

<script type="text/javascript">
	$( document ).ready(function( $ ) {
		$( '#metabo_slider' ).sliderPro({
			width: '100%',
			height: 440,
			orientation: 'horizontal',
			buttons: true,
			arrows: true,
			updateHash: true,
			autoplayDelay: 5000,
			imageScaleMode: 'contain',
			forceSize:'fullWidth',
			thumbnailsPosition: 'right',
			thumbnailWidth: 630,
			thumbnailHeight: 440,
});
	});
</script>
Is this because I changed height of thumbnails to the same height of images? Could you help me on this? Thank you, David.

**Comment by davidghi** [comment]
Please post a link to your page, so I can have a better understanding of what's happening. Cheers.

**Comment by Misa-no** [comment]
Thanks David. This is a test page > http://misanodesign.com/HMT/metabolomics.html

**Comment by davidghi** [comment]
It seems that you have an empty thumbnail in the code (<div class="sp-thumbnail"><div>), which might be causing the problem.

Cheers

**Comment by Misa-no** [comment]
Thank you for looking into the problem, David. Yes, I put an empty thumbnail cos' without this code, slides doesn't match with thumbnails on PC (only work for normal loop, not ). My problem is that because of this, updateHash, thumbnailArrows and clicking backwards go wrong... If you have any solution not using the fake thumbnail, please advise. Thank you!

**Comment by davidghi** [comment]
Well, it's necessary not to add more or less thumbnails than needed; you need to have a thumbnail per slide. Not sure, though, about the problem you're referring to. Please provide more details.

**Comment by Misa-no** [comment]
Thank you for your response. I have kept the test site open without the extra tag <div class="sp-thumbnail"><div>. The followings are setting I have for the site. 

<div id="slider_name" class="slider-pro">
<div class="sp-slides">
<div class="sp-slide"><img class="sp-image" src="image.jpg" alt=""/></div>
   /*I have other sp-slide x 4 here*/     
</div></div>

<div class="sp-thumbnails">
<div class="sp-thumbnail">
<div class="sp-thumbnail-text">
<div class="sp-thumbnail-title">Thumbnail Title1</div>
<div class="sp-thumbnail-description">Thumbnail Description1</div>
<div class="links"><a href="#slider_name/1">Next</a></div>  
</div> 
</div>
   /*I have other sp-thumbnail x 4 here*/    
</div>
-----------------------------------------------------------------------------------------
<script type="text/javascript">
	$( document ).ready(function( $ ) {
		$( '#slider_name' ).sliderPro({
			width: '100%',
			height: 450,
			orientation: 'horizontal',
			buttons: true,
			arrows: true,
			slideDistance: 0,
			updateHash: true,
			autoplayDelay: 5000,
			imageScaleMode: 'contain',
			forceSize:'fullWidth',
			thumbnailsPosition: 'right',
			thumbnailWidth: 630,
			thumbnailHeight: 450,
                  });
        });
</script>

If you could help me to figure out the problem I have, that would be great. Thank you!

**Comment by davidghi** [comment]
Sorry for the delay. Unfortunately, it's not clear to me what the problem is when you use only as many thumbnails as slides. I don't understand the matching problem you're referring to.

**Comment by Misa-no** [comment]
Hi David

Thank you again for your response. 

I have 5 slides and 5 thumbnails in total, however, the only 2nd thumbnails skips and the 2nd slide shows 3rd thumbnail. To make the slides and thumbnails match with each other, I added a fake <div class="sp-thumbnail"><div> between 2nd and 3rd thumbnails.

I updated the test page without <div class="sp-thumbnail"><div> here. 
http://misanodesign.com/HMT/metabolomics.html

Hope this explains better:).

**Comment by davidghi** [comment]
I understand now what you're referring to and what causes this behavior. The thumbnail scroller will try to show as the last visible thumbnail the thumbnail that corresponds to the next slide, not the thumbnail that corresponds to the current slide. This makes perfect sense for the purpose for which the thumbnail scroller is intended.

My recommendation for you would be to create two sliders (without thumbnails) and have the synchronize. This is possible with the slider's API.

**Comment by Misa-no** [comment]
Hi David

Thank you for your great tip. I'll try to figure out synchronizing 2 sliders and keep you posted how it goes.

Thank you again!

**Comment by Misa-no** [comment]
Hi David

I have set up 2 sliders without thumbnails but couldn't figure out how to link them using buttons, arrows and the "NEXT" links (updateHash). If you have any tips please let me know. Thank you!

**Comment by davidghi** [comment]
Hi. You can use the `gotoSlide` callback to detect when the slide changes and when that happens call `gotoSlide( index )` on the other slider. You will also need to check if the selected slide of the two sliders differ and call `gotoSlide` only when that's the case.

Cheers.

**Comment by Misa-no** [comment]
Hi David
No success of adding callback function like below. Please advise any correct way to sync two slides, '#my-slider-one' and '#my-slider-two' ??

'$( '#my-slider-one' ).sliderPro({
    gotoSlide: function( event ) {
        console.log( event.index );
    },
    change: function() {
        console.log( event );
    },	
});

$( '#my-slider-one' ).on( 'change.gotoSlide', function( event ) {
   $('#my-slider-two' ).trigger('to.gotoSlide', [event.item.index,0,true]);
});
})'

Thank you again for your help!

**Comment by davidghi** [comment]
Hi. I would do it like this:

```
var firstSliderIndex = 0;
var secondSliderIndex = 0;

$( '#my-slider-one' ).on( 'gotoSlide', function( event ) {
    if ( event.index !== secondSliderIndex) {
        $('#my-slider-two' ).sliderPro( 'gotoSlide', event.index );
    }
});

$( '#my-slider-two' ).on( 'gotoSlide', function( event ) {
    if ( event.index !== firstSliderIndex) {
        $('#my-slider-one' ).sliderPro( 'gotoSlide', event.index );
    }
});
```

I haven't actually tested the code, but you can get the idea. Cheers.

**Comment by Misa-no** [comment]
Hi David

Many thanks for your idea. It starts working very well, although the first screens are still jammed when going backwards by buttons and arrows. If I set up `loop: false`, it goes completely wrong. Any ideas?? Thank you again.

**Comment by davidghi** [comment]
Hi. It seems that you've missed some parts from my code: `firstSliderIndex = event.index` and `secondSliderIndex = event.index`. Also, try to use console.log in your debugging, to see why some things are not working. Cheers.

**Comment by Misa-no** [comment]
Hi David
Apologize for my late action. I have added the codes you suggested, however when click through the navigation buttons, it still skips the 2nd slide and texts. This is the same problem I had with the original setting with one slide using thumbnail and couldn't figure out the problem using console.log too. Sorry again for the message after closing issue, but do you have any ideas?

**Comment by davidghi** [comment]
Hi. I did some debugging and discovered the problem, so I made a small modification to the code:

```
var firstSliderIndex = 0;
var secondSliderIndex = 0;

$( '#metabo_slider').on( 'gotoSlide', function( event ) {
    if ( event.index !== secondSliderIndex) {
        secondSliderIndex = firstSliderIndex = event.index;
        $( '#metabo_thumbnail' ).sliderPro( 'gotoSlide', event.index );
    }
});

$( '#metabo_thumbnail' ).on( 'gotoSlide', function( event ) {
    if ( event.index !== firstSliderIndex) {
        firstSliderIndex = secondSliderIndex = event.index;
        $( '#metabo_slider' ).sliderPro( 'gotoSlide', event.index );
    }
});
```

Cheers.

**Comment by Misa-no** [comment]
Hi David,

It worked perfect! Thank you again for all your hard work and saving me with your spark of genius!
