### ISSUE TITLE
Sliders on tabs

### ISSUE THREAD

**Issue by bdadev** [bqworks/slider-pro#82]
Hello!
Is there any chance to use instantiated sliders in tabs?
When the page loads the slider tab of the product is assembled correctly, but not in quality.
Have I done something wrong?
How do I initialize all sliders? Implentar tried to destroy and update methods, but only received error :(

``` html
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="#produto" aria-controls="produto" role="tab" data-toggle="tab">O Produto</a></li>
    <li role="presentation"><a href="#qualidade" aria-controls="qualidade" role="tab" data-toggle="tab">Qualidade</a></li>
    <li role="presentation"><a href="#marketing-kit" aria-controls="marketing-kit" role="tab" data-toggle="tab">Marketing Kit</a></li>
</ul>
<div role="tabpanel" class="tab-pane" id="produto"></div>
<div role="tabpanel" class="tab-pane" id="qualidade"></div>
<div role="tabpanel" class="tab-pane" id="marketing-kit"></div>
```
``` javascript
var gallerys = jQuery(".gallery-slider #gallery");

gallerys.each(function($each) {
    var $this = jQuery(this);
    $this.sliderPro({
        width: 800,
        height: 470,
        arrows: true,
        buttons: false,
        thumbnailArrows: true,
        autoplay: false,
        thumbnailWidth: 200,
        thumbnailHeight: 120
    });
});
```

**Comment by davidghi** [comment]
Hi. You need to resize the slider programmatically, by calling $( '#my-slider' ).sliderPro( 'resize' ),when a new tab is opened.

Cheers.

**Comment by bdadev** [comment]
Hey. Great.

At first it worked perfectly friend, but not boot properly thumbnails, has a margin-left 100px defined in the image.

I suspected that, and initializing the test resposnsivo your browser, but thought he had done something wrong. I suspected a bug mine.

``` javascript
$('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
     jQuery(".gallery-slider #gallery").sliderPro("resize");
});
```

**Comment by bdadev** [comment]
The solution to initialize the slider responded better. Thank you for your help!
This works for me.

```javascript
jQuery('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
    SliderPro.initSliderPro();
});
```
