### ISSUE TITLE
Cannot read property 'animatedLayers' of undefined on Chrome

### ISSUE THREAD

**Issue by namik-mesic** [bqworks/slider-pro#83]
Hello,

I am using sliderPro v1.2.2.

sliderPro initialization:

$('#gallery-slider').sliderPro({
    arrows: true,
    width: '100%',
    height: '350',
    autoplay: true,
    autoplayDelay: 4000
});

This is the only occurrence of sliderPro usage in my project files.

It's causing the following error on chrome:
"Cannot read property 'animatedLayers' of undefined."

On firefox this is working fine.
Could you please help me? :)

**Comment by davidghi** [comment]
Hi. That error is usually thrown when there are no slides inside the slider. If you're generating the content dynamically, check out the generated HTML and make sure that it's correct.

Cheers

**Comment by davidghi** [comment]
Hi. Please try to call the slider's `update` method after you add the new images. You could also try to `destroy` the slider and reinstantiate it with the new images.

Best,
David
