### ISSUE TITLE
Unexpected behavior when over 1000 slides are assigned

### ISSUE THREAD

**Issue by AJAYSINGAL** [bqworks/slider-pro#84]
First of all, thank you so much for this great piece of work!!

I am trying to create an image gallery using slider-pro to show images in full screen.  It works great if I populate it with 20-50 images.  But if I assign let's say 1000 images, I am experiencing issues such as:
1)  It takes the slider-pro approximately 3 minutes to show the screen
2)  Once the screen is shown, it is blank (no image displayed); just displaying the LEFT and RIGHT arrows for navigation.  If I swipe to the left using the mouse, the image shows up for 1 second and then disappears... showing the blank screen again.

The above behavior is not noted when slider-pro is loaded with 10-20 images using the same code.  I am using the "Lazy Loading" technique.  Should slider-pro be able to handle over 1000 images?  Is there a special technique/property that I should be using to load these images?

Thank you in advance for your time.

**Comment by davidghi** [comment]
That amount of images is too much for this slider and maybe for any slider, in general. Also, there's no point in adding so many images in a slider because no user will scroll through 1000 images. Maybe it would be a better idea to use a gallery with categories.

Cheers.

**Comment by AJAYSINGAL** [comment]
Hi David,  actually, I am using the gallery to show the thumbnails of various sizes.  I wanted to add a feature to show all images as fullscreen in a slide show.  For the full screen view, I had planned to use slider-pro.

I understand that 1000 images is too many to load.  Using slider-pro, can I implement pagination?  Maybe show 100 images at a time?  If yes, I am guessing I can load up slider-pro with first 100 images and then when the user clicks on "More" button, remove old 100 images and load new ones?

**Comment by davidghi** [comment]
There isn't built-in pagination in the sense you're referring to, but you can implement it if you have JavaScript skills.

**Comment by AJAYSINGAL** [comment]
Thank you for your suggestion.  My skill level in JavaScript is medium.  I have my application written in C#, MVC using KnockOut.

We have modified the code so that we are obtaining all 1000 images from the server.  Using KnockOut, we are keeping track of number of images loaded in slider-pro.  When the user views the last image, we change the contents of observable array to new set of images.

Now the issue is, slider-pro is not getting updated properly.  We are calling the update().  The old images are not being removed and only couple of the new images are being displayed.  At the time of going to NEXT image, slider-pro jumps to the last image and then back to first.

I will keep trying different scenarios.  If you have any ideas for me, please let me know.

**Comment by davidghi** [comment]
I'm not sure what code you're using to remove and add slides, but for me this is working fine. Anyway, you could also try to destroy the slider and then instantiate it with new content.
