### ISSUE TITLE
Slides not changing automatically while slider is in focus

### ISSUE THREAD

**Issue by ilaif** [bqworks/slider-pro#88]
Hey,
Great plugin!

I am trying to understand if this is an expected behaviour or not, although I didn't see any configuration for that. If I'm focusing on the slider (clicking somewhere on it) then it stops switching slides automatically. I want it to continue though.

I'm using version 1.2.2

Thanks in advance,
Ilai

**Comment by davidghi** [comment]
Hi. Thanks! By default, the autoplay will be paused when the slider is hovered. This behavior is controlled by the `autoplayOnHover` option. You can change that by setting it to `none`.

Cheers.

**Comment by ilaif** [comment]
Hey,

Thanks! Don't know how I missed it. (I set it to false though).
