### ISSUE TITLE
Change attributes when viewport width changes

### ISSUE THREAD

**Issue by ilaif** [bqworks/slider-pro#89]
Hey!

Let's say I want to have a layer with data-vertical="10%" if width is above 768 and data-vertical="40%" otherwise. How can I accomplish that?

Thanks,
Ilai

**Comment by davidghi** [comment]
Hi. For this purpose I would recommend CSS media queries and controlling the position directly with CSS.

Cheers.

**Comment by ilaif** [comment]
Thanks.
