### ISSUE TITLE
Slider margins in IE

### ISSUE THREAD

**Issue by wittewullem** [bqworks/slider-pro#90]
In IE images get sometimes a different inline style (see: margin-top value in code behind:)
   
```
 <div class="sp-slide" style="left: 3665px; width: 723px; height: 541.29px;" data-index="1" data-init="true" data-loaded="true">
    <div class="sp-image-container" style="width: 723px; height: 541.29px;">
         <img width="1280" height="960" class="sp-image" style="width: auto; height: 100%; margin-top: 0px; margin-left: 0.5px;" src="/images/machines/1.jpg" data-default="/images/1.jpg">
    </div> 
    </div>
    <div class="sp-slide" style="left: 4398px; width: 723px; height: 541.29px;" data-index="2" data-init="true" data-loaded="true">
     <div class="sp-image-container" style="width: 723px; height: 541.29px;">
       <img width="1280" height="960" class="sp-image" style="width: 100%; height: auto; margin-top: 207px; margin-left: 0px;" src="/images/machines/2.jpg" data-default="/images/2.jpg">
     </div> 
    </div>
```

This  is only in IE.

My code is:

$( '#slider' ).sliderPro({
	width: 1130,
	height: 846,
	autoplay: false,
	loop: false,
	arrows: true,
	buttons: false,
	fullScreen: true,
	thumbnailArrows: false,
	imageScaleMode: 'cover'
 });

What do i wrong?

**Comment by davidghi** [comment]
Please post a link to the page or try to replicate the problem in a different live example.

**Comment by wittewullem** [comment]
David,

Here is an example where the problem is:

http://www.gebrweststrate.nl/gebruikte-machines/New-Holland-8560-tractor-1996_199

On this page you can find more links to pages with the problem:

http://www.gebrweststrate.nl/gebruikte-machines/landbouwmachines

It's not on each page, maybe you must try more then one page. 

(After a page refresh, all the slides are right displayed)

**Comment by davidghi** [comment]
I tried 10-15 sliders from that page and I've never seen the issue. I used IE11 for testing.

**Comment by wittewullem** [comment]
The problem is solved. I have removed 'alt-tags' what i first have used for the images..
