### ISSUE TITLE
Option autoHeight doesn't work first time through (potential fix options inside)

### ISSUE THREAD

**Issue by the14thgod** [bqworks/slider-pro#91]
I was experiencing an issue where autoHeight did not work the first time the plugin animated the slides. I am producing an adaptive slider by manipulating the layer positions at different breakpoints and needed 'autoHeight' to be enabled on a phone break-point. Basically the slide changes to an image at the top followed by the headline and a button rather than headline, button and quote on top of the image.

Anyway, on load sliderPro would correctly animate the height on the first slide but subsequent slides were stuck at the height of just the image. When slidePro cycles again it properly animates the height of all the elements(image, headline and button). 

After investigating I saw that on load the layers are set to both: 'visibility: hidden' and 'display: none.' I did a quick test of "display:block !important' and that solved the issue. Alternatively removing 'display: none' from jquery.sliderrPro.layers.js @ line 333 or the minified version fixed the issue without the CSS bang declaration. 

I'm guessing sliderPro's get height equivalent fires before that style is removed so the height of those layers read as 0 the first time through. Once the slide is hidden it only maintains 'visibility: hidden' and 'opacity: 0' which will still return the true height. So that's another possible fix (i.e. make sure the style is removed before grabbing the height).

Not sure if this is the right place to post this but figured I'd let you know and also find out if there may be unforeseen-consequences of removing that bit of code? Setting 'display: block !important' on the layers will fix this for my purposes though.

Thanks for this awesome tool, way better than LayerSlider!
Justin

**Comment by the14thgod** [comment]
In a related matter... it appears that on load doesn't resize the layers which means the layers are overlapping and not entirely within the view-able area. However the next slides come in at the right size. 

It looks like there is no scale function happening on load but I can't seem to figure out how to trigger it. I can hard-code a number but can't get one dynamically(the scaleRatio defaults to 1). Is there a setting I am missing that can accomplish this? 

I have no example I can share at the moment but you can replicate it using 'example 1' when you download this plugin. Just remove the 'autoScaleLayers: false,' line from the options; refresh and scale the browser down; refresh and you will see the layer load in at it's original size rather than a reduced size.

**Comment by the14thgod** [comment]
I've coded a few plugins so I took a wack at it, I'm not sure if this would stand up though to the level of this plugin nor have I had enough time to really test to make sure 'everything' is still working but what do you think?

jquery.sliderPro.layers.js

Lines 76-124:
```javascript

    // After gathering the current scale ratio we need to scale each layer
    _layersOnResize: function() {
    var iScaleRatio = this.calculateScaleRatio();

        $.each( this.slides, function( index, slide ) {
            if ( typeof slide.layers !== 'undefined' ) {
                $.each( slide.layers, function( index, layer ) {
                    layer.scale( iScaleRatio );
                });
            }
        });
    },
    
    // When the slider resizes, try to scale down the layers proportionally. The automatic scaling
    // will make use of an option, 'autoScaleReference', by comparing the current width of the slider
    // with the reference width. So, if the reference width is 1000 pixels and the current width is
    // 500 pixels, it means that the layers will be scaled down to 50% of their size.
    calculateScaleRatio: function(){
        var that = this,
            autoScaleReference,
            useAutoScale = this.settings.autoScaleLayers,
            scaleRatio;
    
        if ( this.settings.autoScaleLayers === false ) {
            return 1;
        }
    
        // If there isn't a reference for how the layers should scale down automatically, use the 'width'
        // option as a reference, unless the width was set to a percentage. If there isn't a set reference and
        // the width was set to a percentage, auto scaling will not be used because it's not possible to
        // calculate how much should the layers scale.
        if ( this.settings.autoScaleReference === -1 ) {
            if ( typeof this.settings.width === 'string' && this.settings.width.indexOf( '%' ) !== -1 ) {
                useAutoScale = false;
            } else {
                autoScaleReference = parseInt( this.settings.width, 10 );
            }
        } else {
            autoScaleReference = this.settings.autoScaleReference;
        }
    
        if ( useAutoScale === true && this.slideWidth < autoScaleReference ) {
            scaleRatio = that.slideWidth / autoScaleReference;
        } else {
            scaleRatio = 1;
        }
    
        return scaleRatio;
    },
```

Line 314:

```javascript
    this.scaleRatio = $.proxy(Layers.calculateScaleRatio, Layers);
```

Lines 334-339:

```javascript
    _init: function() {
        this.$layer.attr( 'data-layer-init', true );

        this._setStyle();
        this.$layer.css({ 'visibility': 'hidden'});
    },
```

Thanks for your time and help!

**Comment by davidghi** [comment]
Hi, Justin. I will take a look at these two issues sometime this week and get back with comments and fixes. Cheers.

**Comment by the14thgod** [comment]
Sounds good, I'm not sure if this is personal preference or something you'd also think adds value to your plugin but I made it so that touchswipe events fire the layer out animation (best idea I had at the time):

```javascript
// jquery.sliderPro.touchSwipe.js lines 198-216
if ( this.settings.loop === true ) {
	// Run the hideLayers function if the layers may exist
	if(typeof this.layersGotoSlideReference !== 'undefined'){
		this.hideLayers( this.selectedSlideIndex );
	}
	this.gotoSlide( nextSlideIndex );
} else {
	if ( typeof nextSlideIndex !== 'undefined' ) {
		// Run the hideLayers function if the layers may exist
		if(typeof this.layersGotoSlideReference !== 'undefined'){
			this.hideLayers( this.selectedSlideIndex );
		}
		this.gotoSlide( nextSlideIndex );
	} else {
		this._moveTo( oldSlidesPosition );
	}
}
```

Secondly, I made it so that the link prevention code was a little more specific.When dealing with layers it is not uncommon to require a button rather than the whole slide being clickable. So I just made the main slide image's link follow your click handling but allow 'content links' to pass untouched:

```javascript
//jquery.sliderPro.touchSwipe.js lines 68-71
// Disable click events on the main slide image but allow content links to work
$( event.target ).parents( '.sp-slide' ).find('div.sp-image-container').find( 'a' ).one( 'click.' + NS, function( event ) {
	event.preventDefault();
});
```

**Comment by davidghi** [comment]
Hi Justin,

I've just released an update which contains fixes to the issues you've mentioned above.

Regarding "display: none", this CSS wasn't necessary. I reused some code from another plugin of mine where it was necessary for some calculations, but it wasn't necessary in this plugin, so I removed it.

Regarding the layers not being scaled properly on load, it was a bug introduced in the last version due to some code modifications I did, but I've fixed it now by delaying the `showLayers` call from the `_layersOnUpdate` handler. This ensures that the layers will be displayed after the scale ratio is calculated.

I've decided not to hide the layers during the slide transition, in order to ensure that the slide transition is as smooth as possible, but feel free to modify this as you would like. Also, please note that there is an option which sets the transition to wait until all the layers hide, and start the slide animation only after that. The option is called `waitForLayers`.

Regarding links, there is an undocumented "feature" that will allow clicks and other elements to maintain their default behavior: you need to add the `sp-selectable` class to that link/element.

Cheers.

**Comment by the14thgod** [comment]
David -
Thanks for the update and explanation and the undocumented feature trick. Everything seems to check out with the exception of the 'waitForLayers' setting with swiping(drag or touch). They remain visible until they animate away when cycling on its own or button/arrow presses. Any advice or tricks with that or should I stick with my custom solution above?

Thanks again for your help and this awesome plugin!

**Comment by davidghi** [comment]
You're welcome, and thank you for the compliment!

When the slides are swiped, `waitForLayers` will not have any effect; it's only for the other situations when a new slide is selected. There isn't a built-in solution to hide the layers during a touch-swipe gesture, so you should stick with your custom solution for that.

Cheers.

**Comment by the14thgod** [comment]
Alright, sounds good, thanks!
