### ISSUE TITLE
Fadein Images when the page loads

### ISSUE THREAD

**Issue by panphilos88** [bqworks/slider-pro#93]
Hello,

When the page loads, is there any way of loading all the images using a fadein effect (not talking about the transition). I've been trying many different ways of doing but are not working for the moment.

Thanks!

**Comment by davidghi** [comment]
Hi. You could do it with CSS transitions:

```
.sp-image {
	opacity: 0;
	transition: opacity 1s !important;
}

.sp-image[style] {
	opacity: 1;
}
```

We check if the `style` attribute exists on the image, which is an indication that the image was fully loaded, resized and positioned.

Cheers.
