### ISSUE TITLE
Set an height of 75%

### ISSUE THREAD

**Issue by labonneboite** [bqworks/slider-pro#95]
Hi,

I try to set the height of the slider to 75% of the height of the window but when I put a percent the slider become white and no images were played.

I try to put forceSize: 'fullWindow', that's don't work.

Can I have help please ?

**Comment by labonneboite** [comment]
I found the solution, I add : var sliderHeight = $(window).height() * 0.75;

$('#my-slider').sliderPro({
			height: sliderHeight,
		});

**Comment by labonneboite** [comment]
I found the solution, I add : var sliderHeight = $(window).height() * 0.75;

$('#my-slider').sliderPro({
height: sliderHeight,
});

**Comment by davidghi** [comment]
Hi. When you use a percentage height you need to make sure that the parent/container element has an explicit height assigned, otherwise it will be considered 0, and 75% out of 0 will be 0, resulting in the slider collapsing.

Cheers.
