### ISSUE TITLE
Flicker in Safari

### ISSUE THREAD

**Issue by Julesman** [bqworks/slider-pro#96]
In Safari the plugin causes fonts to change in weight on each slide change. The solution is to apply transform: translateZ(0); to the elements affected. Unfortunately this solution can't be applied globally or to any element that contains features which rely upon translate to function. 

Hoping there is a solution to this.

**Comment by davidghi** [comment]
Hi. This is a Safari bug and it occurs every time you have any CSS3 transition running in the page; it's not specific to this plugin. In general, it can be prevented with this CSS, by applying `-webkit-font-smoothing: subpixel-antialiased` globally, to the container that holds the affected elements.

Cheers.
