### ISSUE TITLE
Thumbnail Panel not scrolling on touch devices

### ISSUE THREAD

**Issue by superluminalK** [bqworks/slider-pro#97]
I believe I have discovered a bug in your until now exemplary piece of engineering! Can you please help me to solve it?

From what I can see it only occurs when its running on a touch device, which I am simulating in Chrome dev tools (F12). 

I have removed all my CSS in-case that is what's causing it but to no avail. I'm afraid I cant show you as the site is in development but here is the code and my init code and a trace of yours.

So, the offending lines are 1798 -> 1804

if ( previousThumbnailPosition < - this.thumbnailsPosition ) {
					newThumbnailsPosition =- previousThumbnailPosition;

// Move the thumbnail scroller to the calculated position
this._moveThumbnailsTo( newThumbnailsPosition );

Firstly, I'm not sure if its supposed to be a < - in the first set of brackets ? If I press on a thumbnail that is partially outside the container in a browser session, the thumbnail locates properly. But in Chrome when simulating say an iPad, or Nexus 10, the code before the first brackets runs but it is transformed into a 0 or -0 value which results in it not moving.

Interestingly, if I place these callbacks on with alerts it works correctly .....
     gotoThumbnail: function ( alert() ) 
     thumbnailsMoveComplete: function ( alert() ) 

I hope you can help, if you need more info let me know.

my init code is 
	        width: '100%',
	        height: 410,
	        arrows: true,
	        imageScaleMode: 'contain',
	        buttons: false,
	        autoplayDelay: 7000,
	        waitForLayers: true,
	        thumbnailsPosition: 'left',
	        thumbnailWidth: 290,
	        thumbnailHeight: 100,
	        thumbnailPointer: true,
	        autoScaleLayers: false,

I'm using bootstrap 3, the slider markup (only 1 slide for brevity) is 

        <div class="sp-slides">
                    	<div class="sp-slide">
				            <img class="sp-image" src="../src/css/images/blank.gif" data-src="Images/xxx/xxx.jpg" />
				            <div class="sp-caption">xxxxx </div>
			            </div>
                </div>

                <div class="sp-thumbnails">
                                    <div class="sp-thumbnail">
				                        <div class="sp-thumbnail-image-container">
					                        <img class="sp-thumbnail-image" src="Images/LogoVerySmall.png"/>
				                        </div>
				                        <div class="sp-thumbnail-text">
					                        <div class="sp-thumbnail-title">xxxxx</div>
					                        <div class="sp-thumbnail-description">xxxxx</div>
				                        </div>
			                        </div>
                 </div>

![code_grab](https://cloud.githubusercontent.com/assets/15245502/10689963/a1bdf038-7976-11e5-8e2c-20bba806110a.jpg)

**Comment by davidghi** [comment]
Hi. Did you test on a real touch device? I tested my online examples and they work fine. I also tested it in browserstack.com and Chrome emulator, and it works there as well. So, I think you either have a bug somewhere in your code or a misconfiguration in Chrome.

Cheers.

**Comment by superluminalK** [comment]
hi,

 

thanks for looking at this, I haven’t got any code added to your code, I am just instantiating as per my post, I don’t have Chrome configured in any other than vanilla way.

 

yes testing on a touchscreen Dell with 3k display…..

 

Could it be anything to do with my CSS ? 

 

thanks

 

Kieran

**Comment by superluminalK** [comment]
hi, 

 

been doing some more testing, it works fine on Safari, and Firefox on a touch device, so unless It’s the Chrome emulator, or another issue I don’t actually know.

 

Sorry to be a pain in your, just trying to help! thanks!

 

Kieran

**Comment by davidghi** [comment]
Try to test my online examples as well, to see if it's something in your implementation or if the problem is in the testing environment you're using (in case you have problems with my examples as well). On my side everything works well.

Cheers.
