### ISSUE TITLE
Touch Swipe Issues: iFrame video + double slide transitions

### ISSUE THREAD

**Issue by the14thgod** [bqworks/slider-pro#99]
David -
I've found a couple of issues that I believe are tied to touchswipe.

1: If you swipe to the previous slide and the video is in an iFrame(such as YouTube) the plugin will jump forward one slide once you click on 'play.' This behavior doesn't happen if you swipe to the next slide nor on subsequent previous swipes and play presses once the video has been loaded. This also only happens when the iFrame is in the DOM on load. SliderPro created iFrames from hyperlinks nor HTML5 video elements trigger this behavior.
*edit: This apparently only happens with YouTube. Vimeo and BrightCove videos do not trigger the above behavior.

2: This one I'm not sure is possible to fix to be honest as I've seen it in similar plugins as well. If you swipe while the next/previous slide transition is occurring you will skip a slide and proceed to the next in either direction. So if you're on slide 1 and swipe to go to slide 2 while mid-transition you will end on slide 3. It's more jarring when you have layers and more easily triggered because the window is larger. Do you have any ideas on this or is it just one of those things that we can't really do anything about?

Thanks!
Justin

**Comment by davidghi** [comment]
Hi Justin,

I wasn't able to reproduce 1. Maybe I didn't understand your explanation of the issue correctly. Can you offer some steps to reproduce it?

Regarding 2, this behavior allows the users to navigate quickly through slides if they want to, so I don't mind it. However, if you want to prevent it, you could use the `gotoSlide` and `gotoSlideComplete` events to detect when a transition is in the process and during that interval apply `z-index: -1` to the slider (this will disable mouse inputs).

Cheers.

**Comment by the14thgod** [comment]
I did a little more testing and found that issue 1 only occurs in Chrome.

Steps to Recreate:
1: Have 3 slides set up with a YouTube video embedded using the code in the video section: 
```
<iframe class="sp-video" src="http://www.youtube.com/embed/msIjWthwWwI?enablejsapi=1&amp;wmode=opaque" width="320" height="180" frameborder="0" allowfullscreen></iframe>
```
2: Load the page and swipe right to go 'back' (i.e. causing the slider to go to the last slide)
3: Immediately click play and the slider will attempt to go to slide 1 but gets misaligned. During my testing of this I notice that if you wait a second or two the error/bug doesn't happen. 

After doing this recreation I've started noticing it is inconsistent in that sometimes it doesn't trigger the misalignment issue. Unless if you have any insight into why this is happening I'm thinking this could be closed since it's rare and tricky to perform meaning most people won't trigger this error.

Thanks for your suggestion on the second issue, I'll take a look at it!

**Comment by davidghi** [comment]
I took a look at this issue some time ago but couldn't find any problem in the code despite what Chrome shows, and I also couldn't replicate the problem in other browser, so I assume it's an isolated problem in Chrome and might disappear with future Chrome updates. Also, since this is a rare scenario, it's probably  not worth trying to find a workaround.

Cheers.
